-- Script para inserir operadores na tabela users
-- Data: 2026-04-18
-- Total: 387 operadores

-- Primeiro, criar tabela de backup caso precise no futuro
CREATE TABLE IF NOT EXISTS operators_backup (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name TEXT NOT NULL,
  username TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  is_active BOOLEAN DEFAULT true
);

-- Inserir operadores na tabela users
-- Os operadores sem username definido serao ignorados (WHERE username != '')

INSERT INTO users (id, name, email, role, is_active, created_at)
VALUES
  (gen_random_uuid(), 'SABRINA NUNES DE MEDEIROS', 'sabmedeiros@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'FABIOLLA BUGADA', 'fbugada@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'NICHOLAS BERNARDO GRACIANO', 'nbgraciano@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ROBERT LEITE SANTOS', 'rolsantos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'THAYNARA DOS SANTOS SILVA', 'thaysilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'NOEMI REZENDE ESTEVAM', 'norezende@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'KAROLAINE OLIVEIRA SANTOS', 'kosantos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ANA PAULA GONCALVES LIMA', 'apglima@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ARTHUR DE SOUSA LEAL', 'asleal@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'PEDRO HENRIQUE COELHO PEREIRA', 'phcoelho@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'PAULA NATALIA SILVA SANTOS', 'pansantos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'CAIO HENRIQUE ARAUJO DE ALENCAR', 'chalencar@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'THAIS ANDRADE SANTOS', 'thandrade@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'FERNANDA BATISTA DA ROCHA', 'fbatista@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ANA FLAVIA GONCALVES DE AZEVEDO', 'afgavezedo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'NATHALY DA SILVA PELEGRINI', 'npelegrini@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'DANIELE DA SILVA', 'dandsilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'REGINE DE SOUSA SILVA', 'rdsousa@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MARINA PALETTI', 'mpapaletti@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'REBECA GABRIELI SOUZA AUGUSTO', 'regaugusto@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JULIANE ALVES EVANGELISTA DOS SANTOS', 'juevangelista@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GABRIEL SOARES DA SILVA PEREIRA', 'gaspereira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GABRIEL VINICIUS DOS SANTOS', 'gabvsantos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ALAN DANTAS SANTOS', 'adantas@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MARIA APARECIDA RODRIGUES FARIAS', 'maarodrogues@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'BRUNO NOVAIS DA SILVA', 'brnsilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'KARINA GONCIARENCO BELLA', 'kabella@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GIOVANNA VALERIA RODRIGUES', 'givrodrigues@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'BIANCA SOUSA NUNES', 'binunes@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LUANA DIAS DE SOUSA', 'luasousa@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LAIS MARQUES BRAVO', 'lbravo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GABRIEL GOMES QUEIROZ', 'ggqueiroz@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'AGATA BITTENCOURT BASAGLIA CUNHA', 'abasaglia@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JOAO DE LIMA MELO SOBRINHO', 'jlsobrinho@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JULIA ALEXANDRA SOUZA NASCIMENTO', 'janascimento@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'EDUARDO SANTOS DO NASCIMENTO', 'edunascimento@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'AMANDA SANTOS PORTO', 'amaporto@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'VITORIA EMANUELE GOMES DE SOUSA', 'visousa@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'TAINARA AMBROZIO MARTINS', 'taamartins@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MAYSA CARLA ALEIXO', 'maaleixo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GABRIEL MASCIARELLI FERREIRA MERGULHAO', 'gamergulhao@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ELDA REGIANE BALERO VIEIRA', 'elvieira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'RENATA CORDEIRO', 'recordeiro@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'NATALIA SILVA MIRANDA', 'namiranda@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'AUGUSTO FELIPE TAVARES DE CARVALHO', 'aucarvalho@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GABRIEL MOTTA HIDALGO', 'gahidalgo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MARIA CLAUDIA FERREIRA DO NASCIMENTO', 'mcferreirta@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'VERONICA APARECIDA DE SOUZA', 'vsouza@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'FRANCILENE MACIEL SOUSA', 'frsousa@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'INGRID DANIELA BENTO DA SILVA', 'idaniela@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'RAFAELA PEREIRA GONCALVES', 'ragoncalves@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'SARA DE BARROS MAGALHAES', 'samagalhaes@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'IGOR CHINELATO PEREIRA', 'igpereira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JULIA MARINHO LEITE', 'juleite@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ARTHUR CONDE RODRIGUES', 'arrodrigues@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GABRIELLA TONON FOLGOSI', 'gafolgosi@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'KATIA SANTOS ALVES', 'kalves@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'CRISTIANE NUNES DE OLIVEIRA', 'cnunes@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'NATASHA SILVA VERA', 'navera@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JAMILLY LIMA DA COSTA', 'jalicosta@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'THIELLY DE ARAUJO LIMA', 'thiaraujo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'BERNARDO DE PAIVA FREITAS', 'befreitas@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'THALIA APARECIDA DA SILVA', 'thadsilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JOAO VICTOR OLIVEIRA DIAS', 'jovdias@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GABRIELLA RODRIGUES OLIVEIRA', 'garoliveira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MICHELE KAYTHLYN FERREIRA RAMOS', 'miramos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GABRIEL SILVA DE OLIVEIRA', 'gasoliveira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'SEVERINA RIBEIRO DOS SANTOS', 'sesantos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'NAYARA PEREIRA DOS SANTOS', 'naypereira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'CRISLANE FERREIRA SILVA', 'criferreira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GEOVANA JERONIMO DE SOUSA', 'gejeronimo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ANA CAROLINE SILVA LUZ DE OLIVEIRA', 'anluz@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'OTAVIO VAILANT VITOR', 'otvitor@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'NATASHA ASSIS DOS SANTOS', 'nassis@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ALESSANDRA SANTOS DE MELO', 'alemelo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'BIANCA GOMES DOS SANTOS', 'bisantos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'NICOLY AMARAL DE FREITAS', 'nifreitas@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ITALO CARDOSO DA ROCHA ALENCAR', 'italencar@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ANA BEATRIZ DA SILVA', 'ansbeatriz@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ANE JAMILE CARDOSO PEREIRA', 'ancardoso@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'FRANCISCA NAZARIO DA COSTA', 'frcosta@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MATHEUS MANDRO BUSARANHO', 'mabusaranho@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'TIAGO IORI YONEMURA', 'tiyonemura@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'NATHYELLE PEREIRA SANTANA', 'natsantana@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GIOVANNA PAREJA ANZOLIN', 'gianzolin@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'KELLY BARBOSA OLIVEIRA PAULINO', 'kepaulino@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'BRUNA BONAVOLHA BASSI', 'brbassi@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JOYCE DINIZ SOUZA', 'jodiniz@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'HAYALA VITORIA SILVA PEREIRA', 'hapereira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'NATAN BONFANTI COSTA', 'nabonfanti@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ERICK ROCHA DA SILVA', 'erirocha@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LETICIA VITORIA RODRIGUES BOLLINI ROCHA', 'lerocha@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GEOVANA SOUZA DA SILVA', 'geosouza@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MARIA PAMELA SILVA DE CRISTO', 'macristo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ROBERT RODRIGUES MARTINS', 'romartins@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'PRISCILA CANDIDA DE OLIVEIRA SANTOS', 'prissantos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GUSTAVO FERREIRA SILVA', 'gufsilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'EMILLY MUNIZ TEIXEIRA', 'emteixeira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'KAROLAYNE CRISTINA BRESSI DA SILVA', 'kabressi@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'SANDRA LEOPOLDINO LEIRAS', 'saleiras@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GIOVANNA DA SILVA VARJAO', 'givarjao@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LAURA FERREIRA FAENSE', 'lafaense@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ALEXANDRINA FIGUEIREDO DE AQUINO', 'alaquina@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ROGERIO SILVA RODRIGUES', 'rogesilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MILENA MACENA OLIVEIRA', 'mimacena@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'OLIVIA ESTEVES MENESES', 'olmeneses@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'HENRIQUE SEVERINO DA SILVA', 'heseverino@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MICHELLY DA SILVA SANTOS', 'michessantos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'PALOMA MARQUES APOLIANO VAZ', 'pavaz@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ANA LUIZA DE OLIVEIRA GONCALVES', 'anluiza@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'SAMUEL RODRIGUES DO AMARAL', 'samuamaral@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'YARA RIBEIRO DE OLIVEIRA', 'yaribeiro@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GEOVANNA LEANDRO FERREIRA', 'geferreira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MURILO CAMPOLI DA SILVA', 'mucampoli@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'PAOLA CANDIDA BEZERRA', 'pcbezerra@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LUANA SILVA LELIS', 'lulelis@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'CLEIDE ROSA DOS SANTOS', 'clesantos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ELIANA FERNANDES DE LIMA', 'elflima@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LUIZ HENRIQUE DIAS BERNARDES', 'lubernardes@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'BRUNO DOS SANTOS RIBEIRO BORGES', 'bruborges@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'FABIANA MURARI GONCALVES', 'fabigoncalves@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JOSY TALITA GONCALVES DE SOUSA', 'josysousa@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ANGELO MAXIMO SILVA VIEIRA', 'angvieira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MARIA GENILDA DE ARAUJO LIMA', 'magelima@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ADRIANO PALMEIRA LOPES', 'adlopes@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LARISSA ARIADNE COUTINHO CARVALHO ALVES', 'larialves@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JEFFERSON DE SOUSA LEITE', 'jeleite@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'RENATA GOMES DOS ANJOS', 'reanjos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'NATELLY SALGADO DE OLIVEIRA', 'nateoliveira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'YASMIM LAIS SANTOS REIS MARQUES', 'yamarques@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JHONATAN MONTEIRO DA SILVA', 'jhonsilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JULIANA CERQUEIRA', 'jucerqueira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'YASMIM DA SILVA MELO', 'yamelo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MARIANE VITORIA GALDINO', 'magaldino@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'VERA MOURA DA SILVA', 'vemoura@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'KAROLINA DE OLIVEIRA SANTOS', 'karosantos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ISABELLY LIMA BARRETO', 'isbarreto@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'TAINA APARECIDA SALES DA SILVA', 'taasilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'RAISLENY DE CARVALHO', 'raycarvalho@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'NILVA MARIA RABISQUIM', 'nirabisquim@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MATHEUS ALVES ELLERN SCUCUGLIA', 'mascucuglia@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MARIA TEREZA FRETEGOTTO', 'mafretegotto@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'STHEU SCANCANI GALORO', 'stgaloro@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ELAINE BISPO SOARES LIMA', 'elblima@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JOSE CARLOS COSTA', 'joccosta@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GABRIELLA NASCIMENTO NEGRI', 'ganegri@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'VINICIUS DE ALMEIDA ROMAGNOLO', 'viromagnolo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GIULIA RIBEIRO TAVARES FARIAS MAGNO', 'gumagno@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'KAREN CARVALHO DE SA', 'kasa@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'RANIELLY SILVA LEITE FRANCISCO', 'rinfrancisco@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ARTHUR AVELINO CAMARGO', 'arcamargo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MAYARA THAYNA DE JESUS ALVES DA SILVA', 'majustino@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'VINICIUS DOS REIS PASSOS', 'vrpassos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MARISA DEMARCHI NOGUEIRA', 'marnogueira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'EMILLY GONCALVES DE LIMA', 'emlima@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JENNIFER CAMILA DOS SANTOS', 'jencsantos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JOYCE CRUZ DOS SANTOS', 'jocruz@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LEANNE SLENY FERREIRA FREITAS', 'leaferreira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LUIZA ROSA BISPO SOUSA', 'lubispo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GABRIELLA SILVESTRE ANNUNCIATO', 'gaannunciato@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GIOVANNA SILVESTRE ANNUNCIATO', 'giannunciato@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'EDUARDA DE OLIVEIRA MARTINS', 'edmartins@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GIOVANNA BRITO DA SILVA', 'gidabsilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'HELOISA BORGES DE LIMA', 'hebdlima@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LUCAS PEREIRA CLAUDINO DOS SANTOS', 'luclsantos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'INES PEREIRA DOS SANTOS', 'inpsantos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'CINTHIA DE OLIVEIRA SOTOCORNO', 'cisotocorno@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'THALIA XAVIER DE ALMEIDA', 'thxalmeida@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MARIA JOSE SILVA DE MELO', 'majmelo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LAYANE SANTOS VITOR SILVA', 'laynsilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'RUI SOBREIRA LOPES', 'rulopes@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'CINTIA DANIEL LIMA', 'cilima@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GYOVANNA DOS SANTOS SALES', 'gysales@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LEONARDO GUSTAVO GOMES LINCEVICIUS', 'lelincevicius@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'STEFANIE CAROLINE OLIVEIRA CISTERNAS', 'stcisterna@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'DAVI MEDEIROS DA COSTA', 'dadcosta@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ALICE SANTOS DE ALMEIDA VIEIRA', 'alvieira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'VANESSA TOSSATO', 'vatossato@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MONIQUE MESQUITA DA SILVA PAIXAO', 'mopaixao@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'VERONICA GONZAGA LEITE', 'veleite@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GESSICA FERNANDES DA CRUZ', 'gefcruz@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LUANY SALES DE FREITAS', 'lusfreitas@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MARIA EDUARDA LIMA GOMES', 'malgomes@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'YANNE KARYNE FREITAS DO NASCIMENTO', 'yanascimento@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'SABRINA BARBOSA LEAO', 'saleao@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ALINE CAMPOS RAIMUNDO', 'alraimundo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GABRIELA PAOLA DE CARVALHO', 'gapcarvalho@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GUILHERME CAETANO BARBOZA DE LIMA', 'guclima@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ELIANE JOSEFA DIAS', 'eldias@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'VICTOR FREITAS XALEGA', 'vixalega@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'CAUAN BOAVISTA DE FREITAS', 'cabfreitas@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ANA MARIA DE OLIVEIRA FONSECA', 'anfonseca@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'NAIOBI SAPONHOS DE AGUIAR SOARES', 'nasoares@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ALEXANDRE MARQUES DA SILVA GUERRA', 'alguerra@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MARIA STEFANE MENDS FEITOSA', 'mafeitosa@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LUCAS VELOSO SILVA', 'lucveloso@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MILLENA DOS SANTOS SILVA', 'missilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ANNA CLARA STORTI CAMILO', 'ancamilo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'EMILLY KAMILLY SIQUEIRA DA SILVA', 'emsiqueira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JENIFER MAIRA LIMA DA SILVA', 'jemsilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'YARA RIBEIRO SOUZA', 'yasouza@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'FERNANDA DE OLIVEIRA VIANA', 'feviana@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'STELLA SOUZA FREITAS', 'stfreitas@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LARICE BENTO GARCIA', 'lagarcia@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ANA JULIA SOARES DE MELO', 'anjmelo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'NICOLE PIONA COSTA RODRIGUES', 'nicpiona@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JULYA DA SILVA PEREIRA', 'julpereira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JENNIFER LIZ DE ALMEIDA VIEIRA', 'jenvieira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'KETHLEEN NATHALIA DOS SANTOS MORINI', 'kemorini@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'RAYANE SOUSA DA SILVA', 'rayasilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ROSANE CORREA SANTOS ALVES', 'rosalves@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GABRIELLA DO NASCIMENTO SILVA', 'gabnascimento@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ANA SARA RODRIGUES SILVA', 'annsilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MARLEIZE ERDEI PARRINI', 'maparrini@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'BRUNO RAFAEL DOS SANTOS ABRAO', 'brabrao@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'SILVANA COSTA BERTOLUCCI', 'sibertolucci@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'DEBORA MACHADO', 'demachado@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LENILZA ANSELMO REIS SANTOS', 'leanselmo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'YURI CRISPIM DE LIMA', 'yulima@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LUAN SANTOS MOTA', 'lumota@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MATEUS BARREIROS MARQUES DE SOUZA', 'mabasouza@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'KALIL DE ALMEIDA VIEIRA', 'kaalvieira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MARIA EDUARDA LIMA SILVA', 'malisilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'KAUAI RODRIGUES BARBOSA', 'kabarbosa@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'BEATRIZ SOUZA SILVA', 'besosilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JOVANA ESTEFANE NOGUEIRA DA SILVA', 'joessilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JENIFFER LOUREANO BOSSI DE BARROS', 'jebarros@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'EMILI DOS SANTOS SILVA', 'emsimoura@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'VANESSA GOMES DE FREITAS', 'vafreitas@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'DEBORA PEREIRA SANTOS', 'depesantos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'RAUL SABINO SOLERA', 'rasolera@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GYOVANNA PASCHOAL FULINI RIBEIRO', 'gyribeiro@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GERUSIA MARTA FERNADES LINHARES', 'gelinhares@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'KELLY CRISTINA PINTO SILVEIRA', 'kesilveira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LEANY MARIA CAETANO OLIVEIRA', 'leaoliveira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'RAPHAEL CORREIA NEVES', 'racneves@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LUCAS FERREIRA DA SILVA', 'lucferreira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LUCAS TAMASHIRO UJLAKI', 'luujlaki@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'RYAN CAVINATO BAZAN', 'rybazan@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MURILO ESTEVAM DE SOUZA', 'mursouza@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LUCAS FERNANDES BARROS', 'lubarros@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GIOVANNA GONCALVES CABRAL', 'gigcabral@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'VICTOR HUGO GONCALVES SANTOS', 'vihsantos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'KEZIA LEAL', 'keleal@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MARIA EDUARDA GUIMARAES LOPES', 'marlopes@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'VITORIA CAMPOS AGUIAR', 'viaguiar@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'BENTO DE LIMA ALVES', 'betalves@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'YASMIN LIMA BARBOSA', 'yalbarbosa@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'YASMIM GUIMARAES CORDEIRO DOS SANTOS', 'yascordeiro@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'SARA SILVA SANTOS', 'ssasantos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ANDREIA ALBERTO FURTADO FERREIRA', 'andrferreira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MANOELLA SENA BARBOSA', 'masbarbosa@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ESTHER SILVA', 'esthsilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'NIVEA KATIA DA SILVA BOAVENTURA', 'niboaventura@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MARIA EDUARDA SOUZA DE LIMA', 'madulima@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'TATIANA SIQUEIRA DE MOURA', 'tatimoura@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'VITOR FERREIRA MORAIS', 'vimorais@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GIOVANA FERREIRA DA SILVA', 'gifsilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'FABIANA ABDALLA', 'faabdalla@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'THAIS REZENDE SILVA', 'threzende@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LUCAS DA SILVA PEDROSA', 'ludpedrosa@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'FELIPE AGUIAR MENDES DO NASCIMENTO', 'feaguiar@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ANA KATIA DA SILVA', 'ankatia@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'CATARINA ALVES SILVA', 'catsilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'PEDRO HENRIQUE LAVORATO', 'pelavorato@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'EDER NASCIMENTO ALVES', 'edalves@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MELISSA BALBINO DA SILVA GOMES', 'megomes@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LARISSA NASARIO PEREIRA', 'lapereira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'RENAN DA SILVA BULGARELLI', 'rebulgarelli@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ANA CAROLINE SOUZA OLIVIA', 'anolivia@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'PEDRO HENRIQUE NASCIMENTO DA SILVA', 'phenrique@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LIVIA NOBREGA PIGHIN', 'lipighin@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'KARINA MUNIZ VIEIRA', 'kamuniz@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'VITOR HUGO ALVARENGA FACCIOLO', 'vifacciolo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'BRENDA MORGAN ESTRELA DA SILVA', 'brestrela@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GABRIELLY SANTOS OLIVEIRA', 'gbsoliveira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JADE ALVES DE ARAUJO', 'jaaraujo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ISABELA CRISTINA DE SOUZA', 'iscsouza@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'AMANDA CUER FERREIRA', 'amferreira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ANA KAROLINA PEREIRA CRUZ', 'ankcruz@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LETICIA SIQUEIRA BISPO', 'lebispo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'KAUE RAMOS PEREIRA', 'kapereira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'DANIELLE LIMA DA COSTA', 'dacosta@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'NADJA GAMA DOS SANTOS', 'ngama@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MAYSA DOS SANTOS NERES', 'maneres@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'TAMIRES NEVES DOS SANTOS', 'tansantos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MAXINE LUARA RODRIGUES BATISTA DA SILVA', 'maluara@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'FABIANA APARECIDA BASILIO', 'fabasilio@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'STEFANIE PAMPOLINI DE ASSIS', 'stassis@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LUANA DIAS BRAZ', 'lubraz@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'FRANCIELE QUERCIA DE OLIVEIRA DOS REIS', 'frreis@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'YASMIN MACHADO DA SILVA', 'yasmachado@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'DAVI JOSE NIETTO DE SOUZA', 'danietto@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'VITOR MENDONCA LOPES', 'vilopes@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'CAROLINA NUNES DA SILVA', 'carsnunes@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'PRISCILA FONTES DE AZEVEDO', 'prazevedo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ERIKA MACIEL PEREIRA', 'ermpereira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MARCOS VINICIUS DE LIMA COSTA', 'mavcosta@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'THAIS SANTOS LOURENCO', 'thlourenco@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'DEISY KIMBERLLY SATILITE ARAUJO', 'dearaujo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'BRENO ALVES NOGUEIRA', 'brenogueira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'DANIELLE DA SILVA WENCESLAU', 'dawenceslau@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'FABIO EISHIMA DE CASTRO GUIRRA', 'faguirra@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GEOVANA SILVA MATARUCO DE GODOY', 'gegodoy@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'HAYANE DE MOURA GOMES', 'hagomes@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'DANIELA MOURA ANDRADE', 'daneto@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'CARLOS VINICIUS DIAS DA SILVA', 'cavinicius@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GEOVANA DE JESUS SANTOS', 'geovjesus@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GIOVANNA FERRAIULI', 'giferraiuli@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MARIA EDUARDA SARAIVA BARBOSA', 'marsaraiva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MARINA SOARES DA SILVA', 'marisoares@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'REBECA CIARELLI GUERRA TERTO', 'reterto@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'CAMILLY VITORIA SILVA', 'casvitoria@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'AMANDA LUIZA DIAS SANTOS', 'amsantos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'KAYLLANE MYRELLE MOTA SILVA', 'kaylsilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'CRISTIANE PAIZ LYRA', 'crpaiz@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GUSTAVO HENRIQUE NASCIMENTO DE SOUZA', 'gutsouza@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GABRIEL DA SILVA SANDRAN', 'gasandran@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JULIA CAVALCANTI DA COSTA', 'jucavalcante@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'VERONICA CAVALCANTE LAGE', 'velage@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'PEDRO FERREIRA DE FREITAS', 'pefreitas@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MARIANI SILVA DE LIMA', 'marilima@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ELETICIA SOUZA DA SILVA', 'elesilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'BIANCA FARIAS DE OLIVEIRA', 'bifoliveira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'NICOLAS WITKOWSKI', 'niwitkowaki@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MIRELLA DE ARAUJO AMARAL', 'miamaral@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'KAUANY SILVA LIMA', 'kanslima@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'QUEZIA SILVA DOS SANTOS', 'quezsantos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JENIFER MARTINS DA SILVA', 'jenisilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'SIMONE DE CARVALHO SILVA', 'sicarvalho@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GISELE NERI RIBEIRO', 'gineribeiro@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'THAINA LORRANNE NICOLAU BEZERRA', 'thbezerra@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'TAMARA PEREIRA SANTOS', 'tapsantos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ANDREY MATOS FERREIRA DA SILVA', 'anmasilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'CAROLINA VITORIA DE ARAUJO SANTOS', 'cavisantos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'KARIN FIRMO DE LIMA', 'kaflima@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'CAMILA FIRMO DE LIMA', 'calima@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'HENRIQUE LINO DA SILVA', 'helisilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'INGRID ANISIO DA SILVA', 'inanisilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ANA PAULA RODRIGUES', 'anparodrigues@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'DERICK RIBEIRO DE SALES', 'desales@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'KATHELLYN IASMIM ROSA SANTANA', 'kasantana@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LAURA AMURIM ESTAPINA MOLLER', 'lamoller@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'FLAVIA BERNARDES STOLFO DOS SANTOS', 'flsantos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'VANESSA PINTO', 'vapereira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'STEPHANIE GOMES SOARES', 'stgsoares@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GRAZIELLI CRISTINA PEREIRA DE OLIVEIRA', 'groliveira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JACKSON CINTRA RAIMUNDO', 'jaraimundo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LUCIANA BARBOSA DA SILVA SANTOS', 'lubarsantos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'FATIMA CRISTINA SILVA DE JESUS', 'fajesus@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'NOEMY BESERRA DA SILVA DE SOUSA', 'nosousa@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'EDUARDA SILVA DE TOLEDO PINTO', 'edtoledo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JOSE CARLOS DA SILVA', 'jclsilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MARIA LUIZA FREITAS DOS SANTOS', 'mrlfreitas@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'DEBORA DA SILVA TELLES', 'detelles@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'VINICIUS DOS SANTOS PEREIRA POMPEU', 'vipompeu@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JOAQUIM RODRIGUES ZARBINATI', 'jozarbinati@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'VITOR GABRIEL BRANDAO RODRIGUES', 'vgrodrigues@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JOICE VITAL CAETANO', 'jocaetano@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'EVELLYN SILVA PEREIRA', 'evspereira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GIOVANNA LAMBIASI DE ARAUJO', 'glaraujo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LETICIA ANTUNES VIEIRA', 'levieira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'SILMEIA SANTANA NEVES', 'sineves@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'SIRLEI APARECIDA MOTA', 'simota@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'AMANDA FERNANDES DA SILVA SOUZA', 'amsouza@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MARIA DE FATIMA FLORENCIO DE ATHAYDE', 'maathayde@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'STEPHANIE XAVIER DE OLIVEIRA', 'stexavier@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'TABATA SAMANTHA AGUIAR BUSTOS', 'tabustos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'TALITA REBECA ALBUQUERQUE DE LIMA', 'trebeca@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'VITOR DA SILVA OLIVEIRA', 'vitsilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'RENATA HORVATH', 'rehorvath@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'RICHARD MENDES LUCINDO', 'rilucindo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LARISSA OLIVEIRA CARVALHO', 'larcsilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LETICIA RANY MENDES LUCINDO', 'lelucindo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LUCAS DELLA BIANCA ABREU', 'luabreu@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MARIA SUSYANE DO NASCIMENTO', 'msusyane@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GUILHERME MODESTO LOPES DA SILVA', 'gmodesto@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MARIA EDUARDA DE BRITO SILVA', 'mbrito@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'BRUNA ONTIVEROS JESUS', 'bontiveros@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'CARLOS EDUARDO LUNGUINHO DE OLIVEIRA', 'clunguinho@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ERIC CATINO RFATO', 'errfato@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ARTUR ALVES ADEO', 'aradeo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'BEATRIZ CAMILLO SANCIULIS', 'besanciulis@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'BEATTRIZ PENACCHIO RIBEIRO SILVA', 'bpenacchio@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GABRIELLA POSSEBOM LOPES', 'gapossebom@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LUIS FERNANDO OSUNA SOLDA', 'lusolda@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GABRIELA TEIXEIRA DO NASCIMENTO', 'gabrteixeira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ANA LARISSA EVANGELISTA DA SILVA', 'anevangelista@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'DENISE DA SILVA', 'denisilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MARCOS VINICIUS JOVINO DOS SANTOS', 'majovino@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'RUAN PABLO DA SILVA', 'rupablo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'SOPHIA ANDRADE PEREIRA', 'sopereira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ANDRE DA ROCHA BARRETO', 'anbarreto@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'BEATRIZ DORINE YUSMY DA SILVA', 'beyusmy@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'CARINA SIMOES', 'casimoes@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ISADORA DE OLIVEIRA FERREIRA', 'isaferreira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'THAINA GUIMARAES FERREIRA', 'thferreira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'KAUAN DURAES DE ABREU', 'kaabreu@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GEOVANNA APARECIDA ALMEIDA DA SILVA', 'gealmeida@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ALINE TEIXEIRA DE AMORIM', 'alamorim@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'INGRID LARA CESAR LIMA', 'inlima@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'RITA DE CASSIA DOS SANTOS', 'risantos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'SARA SARTORIO ALVES GARCIA', 'sagarcia@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LOHANY DO NASCIMENTO LEOCADIO JUVINO', 'lojuvino@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LORENA FACHINCONI DA SILVA', 'lachinconi@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GIULIANA CAVLAK NAVARRO', 'ginavaro@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'KATHLLEN LIMA DE MELO', 'kamelo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'BIANCA ARRIATE DA SILA FLAMINIO', 'biflaminio@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JHENNYFER PEGO FERNANDES', 'jhfernandes@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LUCIANA RAPOZO NEVES', 'luneves@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MONIQUE CORREIA', 'mocorreia@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'PEDRO LUIGI PALMA SANCHES', 'pesanches@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'RICHARD VITOR SILVA DOS REIS', 'rireis@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'KEYANE VELOSO PAIVA', 'kepaiva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'SILVIA REGINA DE OLIVEIRA', 'sioliveira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'YASMIN YOUSSEF ABOU OSMAN', 'yaosman@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MARISA FRANCIS GUILHERME TARTARI', 'matartari@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MATHEUS DE MARTIN XIMENES', 'maximenes@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'PEDRO HENRYQUE SILVA', 'pehesilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'PRISCILA NUNES LEITE', 'prleite@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'PRISCILA PRATES', 'prprates@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'KETILY CRISTINI DA SILVA LIMA', 'ketlima@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LARISSA GONCALVES ORLANDO', 'laorlando@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LUCAS DE SOUSA MELO', 'lumelo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LUCAS EIRISDAN OLIVEIRA LIMA', 'lueilima@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JOAO PEDRO MARVALHO GALINDO', 'jogalindo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ANDRESSA ROCHA ARAUJO', 'androcha@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ARTUR LUCIANO CASAL', 'arcasal@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'VITOR FRANCIA MATANO', 'vimatano@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ANA VITORIA DOS SANTOS OLIVEIR', 'anoliveir@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'EVELLYN SOARES MARTINEZ', 'evmartinez@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'PRISCILA PEREIRA', 'prpereira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ANNA CLARA PAWLUK', 'anpawluk@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GABRIEL POSTIGO', 'gapostigo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GLEICE QUELLI CONCEICAO DOS SA', 'glsa@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'EMMANUELLE ALEIXO BRITO', 'embrito@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'FELIPE ZULEGER RABETTI', 'ferabetti@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'HELOISA FREITAS DOS SANTOS', 'hefrsantos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LILIAN CRISTINA REZENDE', 'lirezende@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'RAUL ANTONIO ROQUE E SILVA', 'rarosilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'RYAN MATA DA SILVA', 'rymsilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'SUZANA SANTOS ARAUJO', 'suaraujo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'TAINA SANTOS DE OLIVEIRA', 'tasoliveira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'TALITA FERNANDA DA SILVA DE JE', 'taje@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'THAYNA PEREIRA COSTA', 'thpecosta@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'VANESSA LIMA DA COSTA', 'valicosta@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JOSE EMERSON VARJAO', 'jovarjao@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'BRUNO LORENZO RODRIGUES', 'brlorodrigues@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'DAVID RANGEL GONCALVES DE SOUS', 'dasous@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'CAMILA MICAELE GONCALVES', 'camigoncalves@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ADRISIA SANTOS DE OLIVEIRA', 'adroliveira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JESSICA DA CONCEICAO MARTINS', 'jemartins@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LARISSA MYUKI OLIVEIRA SOUZA', 'lamysouza@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LUCAS ARAUJO HOFER', 'luhofer@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MARIA CRISTINA GRECCO MOURA PI', 'mapi@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'MATHEUS APARECIDO ANDREOTTI', 'maandreotti@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'REBECA NOGUEIRA DA SILVA', 'rbnogueira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'RENATA SILVA ROCHA', 'rerocha@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'RYAN DE SOUSA BERNARDINO', 'rybernardino@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'VIVIANE SILVA COSTA', 'vivcosta@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'YASMIN MATTAR DOS SANTOS LOPES', 'yalopes@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ISABELA PEREIRA DA SILVA', 'ispsilva@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JADSON CONCEICAO SANTOS', 'jadsantos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JOAO VICTOR FONOLOSA DE OLIVEIRA', 'jovoliveira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JULIA SILVESTRE YETIKA', 'juyetika@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'KAREN CRISTINA SOARES', 'kcrsoares@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'KEMELLY GONCALVES DA SILVA', 'kmgoncalves@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LUANA JANUARIO SANTOS DE ALMEIDA', 'lualmeida@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'DAVI HIDALGO DA SILVA', 'dahidalgo@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GABRIELLA SCAVONE BRITO', 'gsbrito@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'BRUNA APARECIDA SILVA SANTOS', 'bnsantos@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'BRUNA MOURA PINTO DE SOUZA', 'bmsouza@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'GIOVANNA RIBEIRO FOGATO PEREIRA', 'grpereira@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'JAQUELINE DELLVALD FARIAS', 'jafarias@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'ARTHUR LISBOA CAIRES', 'arcaires@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'DANIEL TELES JUNIOR', 'dajunior@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'LARISSA DA SILVA FRAGA', 'lafraga@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'NATHALIA REGINA SILVA NOVAES', 'nanovaes@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'NICOLE CAVALCANTE DE ALBUQUERQUE', 'nialbuquerque@gruporoveri.com', 'operator', true, NOW()),
  (gen_random_uuid(), 'VITORIA SILVA BATISTA', 'vtrbatista@gruporoveri.com', 'operator', true, NOW())
ON CONFLICT (email) DO NOTHING;

-- Tambem inserir na tabela de backup
INSERT INTO operators_backup (full_name, username)
VALUES
  ('SABRINA NUNES DE MEDEIROS', 'sabmedeiros'),
  ('FABIOLLA BUGADA', 'fbugada'),
  ('NICHOLAS BERNARDO GRACIANO', 'nbgraciano'),
  ('ROBERT LEITE SANTOS', 'rolsantos'),
  ('THAYNARA DOS SANTOS SILVA', 'thaysilva'),
  ('NOEMI REZENDE ESTEVAM', 'norezende'),
  ('KAROLAINE OLIVEIRA SANTOS', 'kosantos'),
  ('ANA PAULA GONCALVES LIMA', 'apglima'),
  ('ARTHUR DE SOUSA LEAL', 'asleal'),
  ('PEDRO HENRIQUE COELHO PEREIRA', 'phcoelho'),
  ('PAULA NATALIA SILVA SANTOS', 'pansantos'),
  ('CAIO HENRIQUE ARAUJO DE ALENCAR', 'chalencar'),
  ('THAIS ANDRADE SANTOS', 'thandrade'),
  ('FERNANDA BATISTA DA ROCHA', 'fbatista'),
  ('ANA FLAVIA GONCALVES DE AZEVEDO', 'afgavezedo'),
  ('NATHALY DA SILVA PELEGRINI', 'npelegrini'),
  ('DANIELE DA SILVA', 'dandsilva'),
  ('REGINE DE SOUSA SILVA', 'rdsousa'),
  ('MARINA PALETTI', 'mpapaletti'),
  ('REBECA GABRIELI SOUZA AUGUSTO', 'regaugusto'),
  ('JULIANE ALVES EVANGELISTA DOS SANTOS', 'juevangelista'),
  ('GABRIEL SOARES DA SILVA PEREIRA', 'gaspereira'),
  ('GABRIEL VINICIUS DOS SANTOS', 'gabvsantos'),
  ('ALAN DANTAS SANTOS', 'adantas'),
  ('MARIA APARECIDA RODRIGUES FARIAS', 'maarodrogues'),
  ('BRUNO NOVAIS DA SILVA', 'brnsilva'),
  ('KARINA GONCIARENCO BELLA', 'kabella'),
  ('GIOVANNA VALERIA RODRIGUES', 'givrodrigues'),
  ('BIANCA SOUSA NUNES', 'binunes'),
  ('LUANA DIAS DE SOUSA', 'luasousa'),
  ('LAIS MARQUES BRAVO', 'lbravo'),
  ('GABRIEL GOMES QUEIROZ', 'ggqueiroz'),
  ('AGATA BITTENCOURT BASAGLIA CUNHA', 'abasaglia'),
  ('JOAO DE LIMA MELO SOBRINHO', 'jlsobrinho'),
  ('JULIA ALEXANDRA SOUZA NASCIMENTO', 'janascimento'),
  ('EDUARDO SANTOS DO NASCIMENTO', 'edunascimento'),
  ('AMANDA SANTOS PORTO', 'amaporto'),
  ('VITORIA EMANUELE GOMES DE SOUSA', 'visousa'),
  ('TAINARA AMBROZIO MARTINS', 'taamartins'),
  ('MAYSA CARLA ALEIXO', 'maaleixo'),
  ('GABRIEL MASCIARELLI FERREIRA MERGULHAO', 'gamergulhao'),
  ('ELDA REGIANE BALERO VIEIRA', 'elvieira'),
  ('RENATA CORDEIRO', 'recordeiro'),
  ('NATALIA SILVA MIRANDA', 'namiranda'),
  ('AUGUSTO FELIPE TAVARES DE CARVALHO', 'aucarvalho'),
  ('GABRIEL MOTTA HIDALGO', 'gahidalgo'),
  ('MARIA CLAUDIA FERREIRA DO NASCIMENTO', 'mcferreirta'),
  ('VERONICA APARECIDA DE SOUZA', 'vsouza'),
  ('FRANCILENE MACIEL SOUSA', 'frsousa'),
  ('INGRID DANIELA BENTO DA SILVA', 'idaniela'),
  ('RAFAELA PEREIRA GONCALVES', 'ragoncalves'),
  ('SARA DE BARROS MAGALHAES', 'samagalhaes'),
  ('IGOR CHINELATO PEREIRA', 'igpereira'),
  ('JULIA MARINHO LEITE', 'juleite'),
  ('ARTHUR CONDE RODRIGUES', 'arrodrigues'),
  ('GABRIELLA TONON FOLGOSI', 'gafolgosi'),
  ('KATIA SANTOS ALVES', 'kalves'),
  ('CRISTIANE NUNES DE OLIVEIRA', 'cnunes'),
  ('NATASHA SILVA VERA', 'navera'),
  ('JAMILLY LIMA DA COSTA', 'jalicosta'),
  ('THIELLY DE ARAUJO LIMA', 'thiaraujo'),
  ('BERNARDO DE PAIVA FREITAS', 'befreitas'),
  ('THALIA APARECIDA DA SILVA', 'thadsilva'),
  ('JOAO VICTOR OLIVEIRA DIAS', 'jovdias'),
  ('GABRIELLA RODRIGUES OLIVEIRA', 'garoliveira'),
  ('MICHELE KAYTHLYN FERREIRA RAMOS', 'miramos'),
  ('GABRIEL SILVA DE OLIVEIRA', 'gasoliveira'),
  ('SEVERINA RIBEIRO DOS SANTOS', 'sesantos'),
  ('NAYARA PEREIRA DOS SANTOS', 'naypereira'),
  ('CRISLANE FERREIRA SILVA', 'criferreira'),
  ('GEOVANA JERONIMO DE SOUSA', 'gejeronimo'),
  ('ANA CAROLINE SILVA LUZ DE OLIVEIRA', 'anluz'),
  ('OTAVIO VAILANT VITOR', 'otvitor'),
  ('NATASHA ASSIS DOS SANTOS', 'nassis'),
  ('ALESSANDRA SANTOS DE MELO', 'alemelo'),
  ('BIANCA GOMES DOS SANTOS', 'bisantos'),
  ('NICOLY AMARAL DE FREITAS', 'nifreitas'),
  ('ITALO CARDOSO DA ROCHA ALENCAR', 'italencar'),
  ('ANA BEATRIZ DA SILVA', 'ansbeatriz'),
  ('ANE JAMILE CARDOSO PEREIRA', 'ancardoso'),
  ('FRANCISCA NAZARIO DA COSTA', 'frcosta'),
  ('MATHEUS MANDRO BUSARANHO', 'mabusaranho'),
  ('TIAGO IORI YONEMURA', 'tiyonemura'),
  ('NATHYELLE PEREIRA SANTANA', 'natsantana'),
  ('GIOVANNA PAREJA ANZOLIN', 'gianzolin'),
  ('KELLY BARBOSA OLIVEIRA PAULINO', 'kepaulino'),
  ('BRUNA BONAVOLHA BASSI', 'brbassi'),
  ('JOYCE DINIZ SOUZA', 'jodiniz'),
  ('HAYALA VITORIA SILVA PEREIRA', 'hapereira'),
  ('NATAN BONFANTI COSTA', 'nabonfanti'),
  ('ERICK ROCHA DA SILVA', 'erirocha'),
  ('LETICIA VITORIA RODRIGUES BOLLINI ROCHA', 'lerocha'),
  ('GEOVANA SOUZA DA SILVA', 'geosouza'),
  ('MARIA PAMELA SILVA DE CRISTO', 'macristo'),
  ('ROBERT RODRIGUES MARTINS', 'romartins'),
  ('PRISCILA CANDIDA DE OLIVEIRA SANTOS', 'prissantos'),
  ('GUSTAVO FERREIRA SILVA', 'gufsilva'),
  ('EMILLY MUNIZ TEIXEIRA', 'emteixeira'),
  ('KAROLAYNE CRISTINA BRESSI DA SILVA', 'kabressi'),
  ('SANDRA LEOPOLDINO LEIRAS', 'saleiras'),
  ('GIOVANNA DA SILVA VARJAO', 'givarjao'),
  ('LAURA FERREIRA FAENSE', 'lafaense'),
  ('ALEXANDRINA FIGUEIREDO DE AQUINO', 'alaquina'),
  ('ROGERIO SILVA RODRIGUES', 'rogesilva'),
  ('MILENA MACENA OLIVEIRA', 'mimacena'),
  ('OLIVIA ESTEVES MENESES', 'olmeneses'),
  ('HENRIQUE SEVERINO DA SILVA', 'heseverino'),
  ('MICHELLY DA SILVA SANTOS', 'michessantos'),
  ('PALOMA MARQUES APOLIANO VAZ', 'pavaz'),
  ('ANA LUIZA DE OLIVEIRA GONCALVES', 'anluiza'),
  ('SAMUEL RODRIGUES DO AMARAL', 'samuamaral'),
  ('YARA RIBEIRO DE OLIVEIRA', 'yaribeiro'),
  ('GEOVANNA LEANDRO FERREIRA', 'geferreira'),
  ('MURILO CAMPOLI DA SILVA', 'mucampoli'),
  ('PAOLA CANDIDA BEZERRA', 'pcbezerra'),
  ('LUANA SILVA LELIS', 'lulelis'),
  ('CLEIDE ROSA DOS SANTOS', 'clesantos'),
  ('ELIANA FERNANDES DE LIMA', 'elflima'),
  ('LUIZ HENRIQUE DIAS BERNARDES', 'lubernardes'),
  ('BRUNO DOS SANTOS RIBEIRO BORGES', 'bruborges'),
  ('FABIANA MURARI GONCALVES', 'fabigoncalves'),
  ('JOSY TALITA GONCALVES DE SOUSA', 'josysousa'),
  ('ANGELO MAXIMO SILVA VIEIRA', 'angvieira'),
  ('MARIA GENILDA DE ARAUJO LIMA', 'magelima'),
  ('ADRIANO PALMEIRA LOPES', 'adlopes'),
  ('LARISSA ARIADNE COUTINHO CARVALHO ALVES', 'larialves'),
  ('JEFFERSON DE SOUSA LEITE', 'jeleite'),
  ('RENATA GOMES DOS ANJOS', 'reanjos'),
  ('NATELLY SALGADO DE OLIVEIRA', 'nateoliveira'),
  ('YASMIM LAIS SANTOS REIS MARQUES', 'yamarques'),
  ('JHONATAN MONTEIRO DA SILVA', 'jhonsilva'),
  ('JULIANA CERQUEIRA', 'jucerqueira'),
  ('YASMIM DA SILVA MELO', 'yamelo'),
  ('MARIANE VITORIA GALDINO', 'magaldino'),
  ('VERA MOURA DA SILVA', 'vemoura'),
  ('KAROLINA DE OLIVEIRA SANTOS', 'karosantos'),
  ('ISABELLY LIMA BARRETO', 'isbarreto'),
  ('TAINA APARECIDA SALES DA SILVA', 'taasilva'),
  ('RAISLENY DE CARVALHO', 'raycarvalho'),
  ('NILVA MARIA RABISQUIM', 'nirabisquim'),
  ('MATHEUS ALVES ELLERN SCUCUGLIA', 'mascucuglia'),
  ('MARIA TEREZA FRETEGOTTO', 'mafretegotto'),
  ('STHEU SCANCANI GALORO', 'stgaloro'),
  ('ELAINE BISPO SOARES LIMA', 'elblima'),
  ('JOSE CARLOS COSTA', 'joccosta'),
  ('GABRIELLA NASCIMENTO NEGRI', 'ganegri'),
  ('VINICIUS DE ALMEIDA ROMAGNOLO', 'viromagnolo'),
  ('GIULIA RIBEIRO TAVARES FARIAS MAGNO', 'gumagno'),
  ('KAREN CARVALHO DE SA', 'kasa'),
  ('RANIELLY SILVA LEITE FRANCISCO', 'rinfrancisco'),
  ('ARTHUR AVELINO CAMARGO', 'arcamargo'),
  ('MAYARA THAYNA DE JESUS ALVES DA SILVA', 'majustino'),
  ('VINICIUS DOS REIS PASSOS', 'vrpassos'),
  ('MARISA DEMARCHI NOGUEIRA', 'marnogueira'),
  ('EMILLY GONCALVES DE LIMA', 'emlima'),
  ('JENNIFER CAMILA DOS SANTOS', 'jencsantos'),
  ('JOYCE CRUZ DOS SANTOS', 'jocruz'),
  ('LEANNE SLENY FERREIRA FREITAS', 'leaferreira'),
  ('LUIZA ROSA BISPO SOUSA', 'lubispo'),
  ('GABRIELLA SILVESTRE ANNUNCIATO', 'gaannunciato'),
  ('GIOVANNA SILVESTRE ANNUNCIATO', 'giannunciato'),
  ('EDUARDA DE OLIVEIRA MARTINS', 'edmartins'),
  ('GIOVANNA BRITO DA SILVA', 'gidabsilva'),
  ('HELOISA BORGES DE LIMA', 'hebdlima'),
  ('LUCAS PEREIRA CLAUDINO DOS SANTOS', 'luclsantos'),
  ('INES PEREIRA DOS SANTOS', 'inpsantos'),
  ('CINTHIA DE OLIVEIRA SOTOCORNO', 'cisotocorno'),
  ('THALIA XAVIER DE ALMEIDA', 'thxalmeida'),
  ('MARIA JOSE SILVA DE MELO', 'majmelo'),
  ('LAYANE SANTOS VITOR SILVA', 'laynsilva'),
  ('RUI SOBREIRA LOPES', 'rulopes'),
  ('CINTIA DANIEL LIMA', 'cilima'),
  ('GYOVANNA DOS SANTOS SALES', 'gysales'),
  ('LEONARDO GUSTAVO GOMES LINCEVICIUS', 'lelincevicius'),
  ('STEFANIE CAROLINE OLIVEIRA CISTERNAS', 'stcisterna'),
  ('DAVI MEDEIROS DA COSTA', 'dadcosta'),
  ('ALICE SANTOS DE ALMEIDA VIEIRA', 'alvieira'),
  ('VANESSA TOSSATO', 'vatossato'),
  ('MONIQUE MESQUITA DA SILVA PAIXAO', 'mopaixao'),
  ('VERONICA GONZAGA LEITE', 'veleite'),
  ('GESSICA FERNANDES DA CRUZ', 'gefcruz'),
  ('LUANY SALES DE FREITAS', 'lusfreitas'),
  ('MARIA EDUARDA LIMA GOMES', 'malgomes'),
  ('YANNE KARYNE FREITAS DO NASCIMENTO', 'yanascimento'),
  ('SABRINA BARBOSA LEAO', 'saleao'),
  ('ALINE CAMPOS RAIMUNDO', 'alraimundo'),
  ('GABRIELA PAOLA DE CARVALHO', 'gapcarvalho'),
  ('GUILHERME CAETANO BARBOZA DE LIMA', 'guclima'),
  ('ELIANE JOSEFA DIAS', 'eldias'),
  ('VICTOR FREITAS XALEGA', 'vixalega'),
  ('CAUAN BOAVISTA DE FREITAS', 'cabfreitas'),
  ('ANA MARIA DE OLIVEIRA FONSECA', 'anfonseca'),
  ('NAIOBI SAPONHOS DE AGUIAR SOARES', 'nasoares'),
  ('ALEXANDRE MARQUES DA SILVA GUERRA', 'alguerra'),
  ('MARIA STEFANE MENDS FEITOSA', 'mafeitosa'),
  ('LUCAS VELOSO SILVA', 'lucveloso'),
  ('MILLENA DOS SANTOS SILVA', 'missilva'),
  ('ANNA CLARA STORTI CAMILO', 'ancamilo'),
  ('EMILLY KAMILLY SIQUEIRA DA SILVA', 'emsiqueira'),
  ('JENIFER MAIRA LIMA DA SILVA', 'jemsilva'),
  ('YARA RIBEIRO SOUZA', 'yasouza'),
  ('FERNANDA DE OLIVEIRA VIANA', 'feviana'),
  ('STELLA SOUZA FREITAS', 'stfreitas'),
  ('LARICE BENTO GARCIA', 'lagarcia'),
  ('ANA JULIA SOARES DE MELO', 'anjmelo'),
  ('NICOLE PIONA COSTA RODRIGUES', 'nicpiona'),
  ('JULYA DA SILVA PEREIRA', 'julpereira'),
  ('JENNIFER LIZ DE ALMEIDA VIEIRA', 'jenvieira'),
  ('KETHLEEN NATHALIA DOS SANTOS MORINI', 'kemorini'),
  ('RAYANE SOUSA DA SILVA', 'rayasilva'),
  ('ROSANE CORREA SANTOS ALVES', 'rosalves'),
  ('GABRIELLA DO NASCIMENTO SILVA', 'gabnascimento'),
  ('ANA SARA RODRIGUES SILVA', 'annsilva'),
  ('MARLEIZE ERDEI PARRINI', 'maparrini'),
  ('BRUNO RAFAEL DOS SANTOS ABRAO', 'brabrao'),
  ('SILVANA COSTA BERTOLUCCI', 'sibertolucci'),
  ('DEBORA MACHADO', 'demachado'),
  ('LENILZA ANSELMO REIS SANTOS', 'leanselmo'),
  ('YURI CRISPIM DE LIMA', 'yulima'),
  ('LUAN SANTOS MOTA', 'lumota'),
  ('MATEUS BARREIROS MARQUES DE SOUZA', 'mabasouza'),
  ('KALIL DE ALMEIDA VIEIRA', 'kaalvieira'),
  ('MARIA EDUARDA LIMA SILVA', 'malisilva'),
  ('KAUAI RODRIGUES BARBOSA', 'kabarbosa'),
  ('BEATRIZ SOUZA SILVA', 'besosilva'),
  ('JOVANA ESTEFANE NOGUEIRA DA SILVA', 'joessilva'),
  ('JENIFFER LOUREANO BOSSI DE BARROS', 'jebarros'),
  ('EMILI DOS SANTOS SILVA', 'emsimoura'),
  ('VANESSA GOMES DE FREITAS', 'vafreitas'),
  ('DEBORA PEREIRA SANTOS', 'depesantos'),
  ('RAUL SABINO SOLERA', 'rasolera'),
  ('GYOVANNA PASCHOAL FULINI RIBEIRO', 'gyribeiro'),
  ('GERUSIA MARTA FERNADES LINHARES', 'gelinhares'),
  ('KELLY CRISTINA PINTO SILVEIRA', 'kesilveira'),
  ('LEANY MARIA CAETANO OLIVEIRA', 'leaoliveira'),
  ('RAPHAEL CORREIA NEVES', 'racneves'),
  ('LUCAS FERREIRA DA SILVA', 'lucferreira'),
  ('LUCAS TAMASHIRO UJLAKI', 'luujlaki'),
  ('RYAN CAVINATO BAZAN', 'rybazan'),
  ('MURILO ESTEVAM DE SOUZA', 'mursouza'),
  ('LUCAS FERNANDES BARROS', 'lubarros'),
  ('GIOVANNA GONCALVES CABRAL', 'gigcabral'),
  ('VICTOR HUGO GONCALVES SANTOS', 'vihsantos'),
  ('KEZIA LEAL', 'keleal'),
  ('MARIA EDUARDA GUIMARAES LOPES', 'marlopes'),
  ('VITORIA CAMPOS AGUIAR', 'viaguiar'),
  ('BENTO DE LIMA ALVES', 'betalves'),
  ('YASMIN LIMA BARBOSA', 'yalbarbosa'),
  ('YASMIM GUIMARAES CORDEIRO DOS SANTOS', 'yascordeiro'),
  ('SARA SILVA SANTOS', 'ssasantos'),
  ('ANDREIA ALBERTO FURTADO FERREIRA', 'andrferreira'),
  ('MANOELLA SENA BARBOSA', 'masbarbosa'),
  ('ESTHER SILVA', 'esthsilva'),
  ('NIVEA KATIA DA SILVA BOAVENTURA', 'niboaventura'),
  ('MARIA EDUARDA SOUZA DE LIMA', 'madulima'),
  ('TATIANA SIQUEIRA DE MOURA', 'tatimoura'),
  ('VITOR FERREIRA MORAIS', 'vimorais'),
  ('GIOVANA FERREIRA DA SILVA', 'gifsilva'),
  ('FABIANA ABDALLA', 'faabdalla'),
  ('THAIS REZENDE SILVA', 'threzende'),
  ('LUCAS DA SILVA PEDROSA', 'ludpedrosa'),
  ('FELIPE AGUIAR MENDES DO NASCIMENTO', 'feaguiar'),
  ('ANA KATIA DA SILVA', 'ankatia'),
  ('CATARINA ALVES SILVA', 'catsilva'),
  ('PEDRO HENRIQUE LAVORATO', 'pelavorato'),
  ('EDER NASCIMENTO ALVES', 'edalves'),
  ('MELISSA BALBINO DA SILVA GOMES', 'megomes'),
  ('LARISSA NASARIO PEREIRA', 'lapereira'),
  ('RENAN DA SILVA BULGARELLI', 'rebulgarelli'),
  ('ANA CAROLINE SOUZA OLIVIA', 'anolivia'),
  ('PEDRO HENRIQUE NASCIMENTO DA SILVA', 'phenrique'),
  ('LIVIA NOBREGA PIGHIN', 'lipighin'),
  ('KARINA MUNIZ VIEIRA', 'kamuniz'),
  ('VITOR HUGO ALVARENGA FACCIOLO', 'vifacciolo'),
  ('BRENDA MORGAN ESTRELA DA SILVA', 'brestrela'),
  ('GABRIELLY SANTOS OLIVEIRA', 'gbsoliveira'),
  ('JADE ALVES DE ARAUJO', 'jaaraujo'),
  ('ISABELA CRISTINA DE SOUZA', 'iscsouza'),
  ('AMANDA CUER FERREIRA', 'amferreira'),
  ('ANA KAROLINA PEREIRA CRUZ', 'ankcruz'),
  ('LETICIA SIQUEIRA BISPO', 'lebispo'),
  ('KAUE RAMOS PEREIRA', 'kapereira'),
  ('DANIELLE LIMA DA COSTA', 'dacosta'),
  ('NADJA GAMA DOS SANTOS', 'ngama'),
  ('MAYSA DOS SANTOS NERES', 'maneres'),
  ('TAMIRES NEVES DOS SANTOS', 'tansantos'),
  ('MAXINE LUARA RODRIGUES BATISTA DA SILVA', 'maluara'),
  ('FABIANA APARECIDA BASILIO', 'fabasilio'),
  ('STEFANIE PAMPOLINI DE ASSIS', 'stassis'),
  ('LUANA DIAS BRAZ', 'lubraz'),
  ('FRANCIELE QUERCIA DE OLIVEIRA DOS REIS', 'frreis'),
  ('YASMIN MACHADO DA SILVA', 'yasmachado'),
  ('DAVI JOSE NIETTO DE SOUZA', 'danietto'),
  ('VITOR MENDONCA LOPES', 'vilopes'),
  ('CAROLINA NUNES DA SILVA', 'carsnunes'),
  ('PRISCILA FONTES DE AZEVEDO', 'prazevedo'),
  ('ERIKA MACIEL PEREIRA', 'ermpereira'),
  ('MARCOS VINICIUS DE LIMA COSTA', 'mavcosta'),
  ('THAIS SANTOS LOURENCO', 'thlourenco'),
  ('DEISY KIMBERLLY SATILITE ARAUJO', 'dearaujo'),
  ('BRENO ALVES NOGUEIRA', 'brenogueira'),
  ('DANIELLE DA SILVA WENCESLAU', 'dawenceslau'),
  ('FABIO EISHIMA DE CASTRO GUIRRA', 'faguirra'),
  ('GEOVANA SILVA MATARUCO DE GODOY', 'gegodoy'),
  ('HAYANE DE MOURA GOMES', 'hagomes'),
  ('DANIELA MOURA ANDRADE', 'daneto'),
  ('CARLOS VINICIUS DIAS DA SILVA', 'cavinicius'),
  ('GEOVANA DE JESUS SANTOS', 'geovjesus'),
  ('GIOVANNA FERRAIULI', 'giferraiuli'),
  ('MARIA EDUARDA SARAIVA BARBOSA', 'marsaraiva'),
  ('MARINA SOARES DA SILVA', 'marisoares'),
  ('REBECA CIARELLI GUERRA TERTO', 'reterto'),
  ('CAMILLY VITORIA SILVA', 'casvitoria'),
  ('AMANDA LUIZA DIAS SANTOS', 'amsantos'),
  ('KAYLLANE MYRELLE MOTA SILVA', 'kaylsilva'),
  ('CRISTIANE PAIZ LYRA', 'crpaiz'),
  ('GUSTAVO HENRIQUE NASCIMENTO DE SOUZA', 'gutsouza'),
  ('GABRIEL DA SILVA SANDRAN', 'gasandran'),
  ('JULIA CAVALCANTI DA COSTA', 'jucavalcante'),
  ('VERONICA CAVALCANTE LAGE', 'velage'),
  ('PEDRO FERREIRA DE FREITAS', 'pefreitas'),
  ('MARIANI SILVA DE LIMA', 'marilima'),
  ('ELETICIA SOUZA DA SILVA', 'elesilva'),
  ('BIANCA FARIAS DE OLIVEIRA', 'bifoliveira'),
  ('NICOLAS WITKOWSKI', 'niwitkowaki'),
  ('MIRELLA DE ARAUJO AMARAL', 'miamaral'),
  ('KAUANY SILVA LIMA', 'kanslima'),
  ('QUEZIA SILVA DOS SANTOS', 'quezsantos'),
  ('JENIFER MARTINS DA SILVA', 'jenisilva'),
  ('SIMONE DE CARVALHO SILVA', 'sicarvalho'),
  ('GISELE NERI RIBEIRO', 'gineribeiro'),
  ('THAINA LORRANNE NICOLAU BEZERRA', 'thbezerra'),
  ('TAMARA PEREIRA SANTOS', 'tapsantos'),
  ('ANDREY MATOS FERREIRA DA SILVA', 'anmasilva'),
  ('CAROLINA VITORIA DE ARAUJO SANTOS', 'cavisantos'),
  ('KARIN FIRMO DE LIMA', 'kaflima'),
  ('CAMILA FIRMO DE LIMA', 'calima'),
  ('HENRIQUE LINO DA SILVA', 'helisilva'),
  ('INGRID ANISIO DA SILVA', 'inanisilva'),
  ('ANA PAULA RODRIGUES', 'anparodrigues'),
  ('DERICK RIBEIRO DE SALES', 'desales'),
  ('KATHELLYN IASMIM ROSA SANTANA', 'kasantana'),
  ('LAURA AMURIM ESTAPINA MOLLER', 'lamoller'),
  ('FLAVIA BERNARDES STOLFO DOS SANTOS', 'flsantos'),
  ('VANESSA PINTO', 'vapereira'),
  ('STEPHANIE GOMES SOARES', 'stgsoares'),
  ('GRAZIELLI CRISTINA PEREIRA DE OLIVEIRA', 'groliveira'),
  ('JACKSON CINTRA RAIMUNDO', 'jaraimundo'),
  ('LUCIANA BARBOSA DA SILVA SANTOS', 'lubarsantos'),
  ('FATIMA CRISTINA SILVA DE JESUS', 'fajesus'),
  ('NOEMY BESERRA DA SILVA DE SOUSA', 'nosousa'),
  ('EDUARDA SILVA DE TOLEDO PINTO', 'edtoledo'),
  ('JOSE CARLOS DA SILVA', 'jclsilva'),
  ('MARIA LUIZA FREITAS DOS SANTOS', 'mrlfreitas'),
  ('DEBORA DA SILVA TELLES', 'detelles'),
  ('VINICIUS DOS SANTOS PEREIRA POMPEU', 'vipompeu'),
  ('JOAQUIM RODRIGUES ZARBINATI', 'jozarbinati'),
  ('VITOR GABRIEL BRANDAO RODRIGUES', 'vgrodrigues'),
  ('JOICE VITAL CAETANO', 'jocaetano'),
  ('EVELLYN SILVA PEREIRA', 'evspereira'),
  ('GIOVANNA LAMBIASI DE ARAUJO', 'glaraujo'),
  ('LETICIA ANTUNES VIEIRA', 'levieira'),
  ('SILMEIA SANTANA NEVES', 'sineves'),
  ('SIRLEI APARECIDA MOTA', 'simota'),
  ('AMANDA FERNANDES DA SILVA SOUZA', 'amsouza'),
  ('MARIA DE FATIMA FLORENCIO DE ATHAYDE', 'maathayde'),
  ('STEPHANIE XAVIER DE OLIVEIRA', 'stexavier'),
  ('TABATA SAMANTHA AGUIAR BUSTOS', 'tabustos'),
  ('TALITA REBECA ALBUQUERQUE DE LIMA', 'trebeca'),
  ('VITOR DA SILVA OLIVEIRA', 'vitsilva'),
  ('RENATA HORVATH', 'rehorvath'),
  ('RICHARD MENDES LUCINDO', 'rilucindo'),
  ('LARISSA OLIVEIRA CARVALHO', 'larcsilva'),
  ('LETICIA RANY MENDES LUCINDO', 'lelucindo'),
  ('LUCAS DELLA BIANCA ABREU', 'luabreu'),
  ('MARIA SUSYANE DO NASCIMENTO', 'msusyane'),
  ('GUILHERME MODESTO LOPES DA SILVA', 'gmodesto'),
  ('MARIA EDUARDA DE BRITO SILVA', 'mbrito'),
  ('BRUNA ONTIVEROS JESUS', 'bontiveros'),
  ('CARLOS EDUARDO LUNGUINHO DE OLIVEIRA', 'clunguinho'),
  ('ERIC CATINO RFATO', 'errfato'),
  ('ARTUR ALVES ADEO', 'aradeo'),
  ('BEATRIZ CAMILLO SANCIULIS', 'besanciulis'),
  ('BEATTRIZ PENACCHIO RIBEIRO SILVA', 'bpenacchio'),
  ('GABRIELLA POSSEBOM LOPES', 'gapossebom'),
  ('LUIS FERNANDO OSUNA SOLDA', 'lusolda'),
  ('GABRIELA TEIXEIRA DO NASCIMENTO', 'gabrteixeira'),
  ('ANA LARISSA EVANGELISTA DA SILVA', 'anevangelista'),
  ('DENISE DA SILVA', 'denisilva'),
  ('MARCOS VINICIUS JOVINO DOS SANTOS', 'majovino'),
  ('RUAN PABLO DA SILVA', 'rupablo'),
  ('SOPHIA ANDRADE PEREIRA', 'sopereira'),
  ('ANDRE DA ROCHA BARRETO', 'anbarreto'),
  ('BEATRIZ DORINE YUSMY DA SILVA', 'beyusmy'),
  ('CARINA SIMOES', 'casimoes'),
  ('ISADORA DE OLIVEIRA FERREIRA', 'isaferreira'),
  ('THAINA GUIMARAES FERREIRA', 'thferreira'),
  ('KAUAN DURAES DE ABREU', 'kaabreu'),
  ('GEOVANNA APARECIDA ALMEIDA DA SILVA', 'gealmeida'),
  ('ALINE TEIXEIRA DE AMORIM', 'alamorim'),
  ('INGRID LARA CESAR LIMA', 'inlima'),
  ('RITA DE CASSIA DOS SANTOS', 'risantos'),
  ('SARA SARTORIO ALVES GARCIA', 'sagarcia'),
  ('LOHANY DO NASCIMENTO LEOCADIO JUVINO', 'lojuvino'),
  ('LORENA FACHINCONI DA SILVA', 'lachinconi'),
  ('GIULIANA CAVLAK NAVARRO', 'ginavaro'),
  ('KATHLLEN LIMA DE MELO', 'kamelo'),
  ('BIANCA ARRIATE DA SILA FLAMINIO', 'biflaminio'),
  ('JHENNYFER PEGO FERNANDES', 'jhfernandes'),
  ('LUCIANA RAPOZO NEVES', 'luneves'),
  ('MONIQUE CORREIA', 'mocorreia'),
  ('PEDRO LUIGI PALMA SANCHES', 'pesanches'),
  ('RICHARD VITOR SILVA DOS REIS', 'rireis'),
  ('KEYANE VELOSO PAIVA', 'kepaiva'),
  ('SILVIA REGINA DE OLIVEIRA', 'sioliveira'),
  ('YASMIN YOUSSEF ABOU OSMAN', 'yaosman'),
  ('MARISA FRANCIS GUILHERME TARTARI', 'matartari'),
  ('MATHEUS DE MARTIN XIMENES', 'maximenes'),
  ('PEDRO HENRYQUE SILVA', 'pehesilva'),
  ('PRISCILA NUNES LEITE', 'prleite'),
  ('PRISCILA PRATES', 'prprates'),
  ('KETILY CRISTINI DA SILVA LIMA', 'ketlima'),
  ('LARISSA GONCALVES ORLANDO', 'laorlando'),
  ('LUCAS DE SOUSA MELO', 'lumelo'),
  ('LUCAS EIRISDAN OLIVEIRA LIMA', 'lueilima'),
  ('JOAO PEDRO MARVALHO GALINDO', 'jogalindo'),
  ('ANDRESSA ROCHA ARAUJO', 'androcha'),
  ('ARTUR LUCIANO CASAL', 'arcasal'),
  ('VITOR FRANCIA MATANO', 'vimatano'),
  ('ANA VITORIA DOS SANTOS OLIVEIR', 'anoliveir'),
  ('EVELLYN SOARES MARTINEZ', 'evmartinez'),
  ('PRISCILA PEREIRA', 'prpereira'),
  ('ANNA CLARA PAWLUK', 'anpawluk'),
  ('GABRIEL POSTIGO', 'gapostigo'),
  ('GLEICE QUELLI CONCEICAO DOS SA', 'glsa'),
  ('EMMANUELLE ALEIXO BRITO', 'embrito'),
  ('FELIPE ZULEGER RABETTI', 'ferabetti'),
  ('HELOISA FREITAS DOS SANTOS', 'hefrsantos'),
  ('LILIAN CRISTINA REZENDE', 'lirezende'),
  ('RAUL ANTONIO ROQUE E SILVA', 'rarosilva'),
  ('RYAN MATA DA SILVA', 'rymsilva'),
  ('SUZANA SANTOS ARAUJO', 'suaraujo'),
  ('TAINA SANTOS DE OLIVEIRA', 'tasoliveira'),
  ('TALITA FERNANDA DA SILVA DE JE', 'taje'),
  ('THAYNA PEREIRA COSTA', 'thpecosta'),
  ('VANESSA LIMA DA COSTA', 'valicosta'),
  ('JOSE EMERSON VARJAO', 'jovarjao'),
  ('BRUNO LORENZO RODRIGUES', 'brlorodrigues'),
  ('DAVID RANGEL GONCALVES DE SOUS', 'dasous'),
  ('CAMILA MICAELE GONCALVES', 'camigoncalves'),
  ('ADRISIA SANTOS DE OLIVEIRA', 'adroliveira'),
  ('JESSICA DA CONCEICAO MARTINS', 'jemartins'),
  ('LARISSA MYUKI OLIVEIRA SOUZA', 'lamysouza'),
  ('LUCAS ARAUJO HOFER', 'luhofer'),
  ('MARIA CRISTINA GRECCO MOURA PI', 'mapi'),
  ('MATHEUS APARECIDO ANDREOTTI', 'maandreotti'),
  ('REBECA NOGUEIRA DA SILVA', 'rbnogueira'),
  ('RENATA SILVA ROCHA', 'rerocha'),
  ('RYAN DE SOUSA BERNARDINO', 'rybernardino'),
  ('VIVIANE SILVA COSTA', 'vivcosta'),
  ('YASMIN MATTAR DOS SANTOS LOPES', 'yalopes'),
  ('ISABELA PEREIRA DA SILVA', 'ispsilva'),
  ('JADSON CONCEICAO SANTOS', 'jadsantos'),
  ('JOAO VICTOR FONOLOSA DE OLIVEIRA', 'jovoliveira'),
  ('JULIA SILVESTRE YETIKA', 'juyetika'),
  ('KAREN CRISTINA SOARES', 'kcrsoares'),
  ('KEMELLY GONCALVES DA SILVA', 'kmgoncalves'),
  ('LUANA JANUARIO SANTOS DE ALMEIDA', 'lualmeida'),
  ('DAVI HIDALGO DA SILVA', 'dahidalgo'),
  ('GABRIELLA SCAVONE BRITO', 'gsbrito'),
  ('BRUNA APARECIDA SILVA SANTOS', 'bnsantos'),
  ('BRUNA MOURA PINTO DE SOUZA', 'bmsouza'),
  ('GIOVANNA RIBEIRO FOGATO PEREIRA', 'grpereira'),
  ('JAQUELINE DELLVALD FARIAS', 'jafarias'),
  ('ARTHUR LISBOA CAIRES', 'arcaires'),
  ('DANIEL TELES JUNIOR', 'dajunior'),
  ('LARISSA DA SILVA FRAGA', 'lafraga'),
  ('NATHALIA REGINA SILVA NOVAES', 'nanovaes'),
  ('NICOLE CAVALCANTE DE ALBUQUERQUE', 'nialbuquerque'),
  ('VITORIA SILVA BATISTA', 'vtrbatista')
ON CONFLICT (username) DO NOTHING;
