-- Script SQL para criar tabela de operadores (apenas @gruporoveri.com)
-- Este script pode ser usado para recriar a tabela se necessário

-- Criar tabela de operadores (se não existir)
CREATE TABLE IF NOT EXISTS operators (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  username VARCHAR(100) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Limpar dados existentes (opcional - descomente se quiser limpar)
-- TRUNCATE TABLE operators;

-- Inserir operadores com domínio @gruporoveri.com
INSERT INTO operators (name, username, email) VALUES
  ('SABRINA NUNES DE MEDEIROS', 'sabmedeiros', 'sabmedeiros@gruporoveri.com'),
  ('FABIOLLA BUGADA', 'fbugada', 'fbugada@gruporoveri.com'),
  ('NICHOLAS BERNARDO GRACIANO', 'nbgraciano', 'nbgraciano@gruporoveri.com'),
  ('ROBERT LEITE SANTOS', 'rolsantos', 'rolsantos@gruporoveri.com'),
  ('THAYNARA DOS SANTOS SILVA', 'thaysilva', 'thaysilva@gruporoveri.com'),
  ('NOEMI REZENDE ESTEVAM', 'norezende', 'norezende@gruporoveri.com'),
  ('KAROLAINE OLIVEIRA SANTOS', 'kosantos', 'kosantos@gruporoveri.com'),
  ('ANA PAULA GONCALVES LIMA', 'apglima', 'apglima@gruporoveri.com'),
  ('ARTHUR DE SOUSA LEAL', 'asleal', 'asleal@gruporoveri.com'),
  ('PEDRO HENRIQUE COELHO PEREIRA', 'phcoelho', 'phcoelho@gruporoveri.com'),
  ('PAULA NATALIA SILVA SANTOS', 'pansantos', 'pansantos@gruporoveri.com'),
  ('CAIO HENRIQUE ARAUJO DE ALENCAR', 'chalencar', 'chalencar@gruporoveri.com'),
  ('THAIS ANDRADE SANTOS', 'thandrade', 'thandrade@gruporoveri.com'),
  ('FERNANDA BATISTA DA ROCHA', 'fbatista', 'fbatista@gruporoveri.com'),
  ('ANA FLAVIA GONCALVES DE AZEVEDO', 'afgavezedo', 'afgavezedo@gruporoveri.com'),
  ('NATHALY DA SILVA PELEGRINI', 'npelegrini', 'npelegrini@gruporoveri.com'),
  ('DANIELE DA SILVA', 'dandsilva', 'dandsilva@gruporoveri.com'),
  ('REGINE DE SOUSA SILVA', 'rdsousa', 'rdsousa@gruporoveri.com'),
  ('MARINA PALETTI', 'mpapaletti', 'mpapaletti@gruporoveri.com'),
  ('REBECA GABRIELI SOUZA AUGUSTO', 'regaugusto', 'regaugusto@gruporoveri.com'),
  ('JULIANE ALVES EVANGELISTA DOS SANTOS', 'juevangelista', 'juevangelista@gruporoveri.com'),
  ('GABRIEL SOARES DA SILVA PEREIRA', 'gaspereira', 'gaspereira@gruporoveri.com'),
  ('GABRIEL VINICIUS DOS SANTOS', 'gabvsantos', 'gabvsantos@gruporoveri.com'),
  ('ALAN DANTAS SANTOS', 'adantas', 'adantas@gruporoveri.com'),
  ('MARIA APARECIDA RODRIGUES FARIAS', 'maarodrogues', 'maarodrogues@gruporoveri.com'),
  ('BRUNO NOVAIS DA SILVA', 'brnsilva', 'brnsilva@gruporoveri.com'),
  ('KARINA GONCIARENCO BELLA', 'kabella', 'kabella@gruporoveri.com'),
  ('GIOVANNA VALERIA RODRIGUES', 'givrodrigues', 'givrodrigues@gruporoveri.com'),
  ('BIANCA SOUSA NUNES', 'binunes', 'binunes@gruporoveri.com'),
  ('LUANA DIAS DE SOUSA', 'luasousa', 'luasousa@gruporoveri.com'),
  ('LAIS MARQUES BRAVO', 'lbravo', 'lbravo@gruporoveri.com'),
  ('GABRIEL GOMES QUEIROZ', 'ggqueiroz', 'ggqueiroz@gruporoveri.com'),
  ('AGATA BITTENCOURT BASAGLIA CUNHA', 'abasaglia', 'abasaglia@gruporoveri.com'),
  ('JOAO DE LIMA MELO SOBRINHO', 'jlsobrinho', 'jlsobrinho@gruporoveri.com'),
  ('JULIA ALEXANDRA SOUZA NASCIMENTO', 'janascimento', 'janascimento@gruporoveri.com'),
  ('EDUARDO SANTOS DO NASCIMENTO', 'edunascimento', 'edunascimento@gruporoveri.com'),
  ('AMANDA SANTOS PORTO', 'amaporto', 'amaporto@gruporoveri.com'),
  ('VITORIA EMANUELE GOMES DE SOUSA', 'visousa', 'visousa@gruporoveri.com'),
  ('TAINARA AMBROZIO MARTINS', 'taamartins', 'taamartins@gruporoveri.com'),
  ('MAYSA CARLA ALEIXO', 'maaleixo', 'maaleixo@gruporoveri.com'),
  ('GABRIEL MASCIARELLI FERREIRA MERGULHAO', 'gamergulhao', 'gamergulhao@gruporoveri.com'),
  ('ELDA REGIANE BALERO VIEIRA', 'elvieira', 'elvieira@gruporoveri.com'),
  ('RENATA CORDEIRO', 'recordeiro', 'recordeiro@gruporoveri.com'),
  ('NATALIA SILVA MIRANDA', 'namiranda', 'namiranda@gruporoveri.com'),
  ('AUGUSTO FELIPE TAVARES DE CARVALHO', 'aucarvalho', 'aucarvalho@gruporoveri.com'),
  ('GABRIEL MOTTA HIDALGO', 'gahidalgo', 'gahidalgo@gruporoveri.com'),
  ('MARIA CLAUDIA FERREIRA DO NASCIMENTO', 'mcferreirta', 'mcferreirta@gruporoveri.com'),
  ('VERONICA APARECIDA DE SOUZA', 'vsouza', 'vsouza@gruporoveri.com'),
  ('FRANCILENE MACIEL SOUSA', 'frsousa', 'frsousa@gruporoveri.com'),
  ('INGRID DANIELA BENTO DA SILVA', 'idaniela', 'idaniela@gruporoveri.com'),
  ('RAFAELA PEREIRA GONCALVES', 'ragoncalves', 'ragoncalves@gruporoveri.com'),
  ('SARA DE BARROS MAGALHAES', 'samagalhaes', 'samagalhaes@gruporoveri.com'),
  ('IGOR CHINELATO PEREIRA', 'igpereira', 'igpereira@gruporoveri.com'),
  ('JULIA MARINHO LEITE', 'juleite', 'juleite@gruporoveri.com'),
  ('ARTHUR CONDE RODRIGUES', 'arrodrigues', 'arrodrigues@gruporoveri.com'),
  ('GABRIELLA TONON FOLGOSI', 'gafolgosi', 'gafolgosi@gruporoveri.com'),
  ('KATIA SANTOS ALVES', 'kalves', 'kalves@gruporoveri.com'),
  ('CRISTIANE NUNES DE OLIVEIRA', 'cnunes', 'cnunes@gruporoveri.com'),
  ('NATASHA SILVA VERA', 'navera', 'navera@gruporoveri.com'),
  ('JAMILLY LIMA DA COSTA', 'jalicosta', 'jalicosta@gruporoveri.com'),
  ('THIELLY DE ARAUJO LIMA', 'thiaraujo', 'thiaraujo@gruporoveri.com'),
  ('BERNARDO DE PAIVA FREITAS', 'befreitas', 'befreitas@gruporoveri.com'),
  ('THALIA APARECIDA DA SILVA', 'thadsilva', 'thadsilva@gruporoveri.com'),
  ('JOAO VICTOR OLIVEIRA DIAS', 'jovdias', 'jovdias@gruporoveri.com'),
  ('GABRIELLA RODRIGUES OLIVEIRA', 'garoliveira', 'garoliveira@gruporoveri.com'),
  ('MICHELE KAYTHLYN FERREIRA RAMOS', 'miramos', 'miramos@gruporoveri.com'),
  ('GABRIEL SILVA DE OLIVEIRA', 'gasoliveira', 'gasoliveira@gruporoveri.com'),
  ('SEVERINA RIBEIRO DOS SANTOS', 'sesantos', 'sesantos@gruporoveri.com'),
  ('NAYARA PEREIRA DOS SANTOS', 'naypereira', 'naypereira@gruporoveri.com'),
  ('CRISLANE FERREIRA SILVA', 'criferreira', 'criferreira@gruporoveri.com'),
  ('GEOVANA JERONIMO DE SOUSA', 'gejeronimo', 'gejeronimo@gruporoveri.com'),
  ('ANA CAROLINE SILVA LUZ DE OLIVEIRA', 'anluz', 'anluz@gruporoveri.com'),
  ('OTAVIO VAILANT VITOR', 'otvitor', 'otvitor@gruporoveri.com'),
  ('NATASHA ASSIS DOS SANTOS', 'nassis', 'nassis@gruporoveri.com'),
  ('ALESSANDRA SANTOS DE MELO', 'alemelo', 'alemelo@gruporoveri.com'),
  ('BIANCA GOMES DOS SANTOS', 'bisantos', 'bisantos@gruporoveri.com'),
  ('NICOLY AMARAL DE FREITAS', 'nifreitas', 'nifreitas@gruporoveri.com'),
  ('ITALO CARDOSO DA ROCHA ALENCAR', 'italencar', 'italencar@gruporoveri.com'),
  ('ANA BEATRIZ DA SILVA', 'ansbeatriz', 'ansbeatriz@gruporoveri.com'),
  ('ANE JAMILE CARDOSO PEREIRA', 'ancardoso', 'ancardoso@gruporoveri.com'),
  ('FRANCISCA NAZARIO DA COSTA', 'frcosta', 'frcosta@gruporoveri.com'),
  ('MATHEUS MANDRO BUSARANHO', 'mabusaranho', 'mabusaranho@gruporoveri.com'),
  ('TIAGO IORI YONEMURA', 'tiyonemura', 'tiyonemura@gruporoveri.com'),
  ('NATHYELLE PEREIRA SANTANA', 'natsantana', 'natsantana@gruporoveri.com'),
  ('GIOVANNA PAREJA ANZOLIN', 'gianzolin', 'gianzolin@gruporoveri.com'),
  ('KELLY BARBOSA OLIVEIRA PAULINO', 'kepaulino', 'kepaulino@gruporoveri.com'),
  ('BRUNA BONAVOLHA BASSI', 'brbassi', 'brbassi@gruporoveri.com'),
  ('JOYCE DINIZ SOUZA', 'jodiniz', 'jodiniz@gruporoveri.com'),
  ('HAYALA VITORIA SILVA PEREIRA', 'hapereira', 'hapereira@gruporoveri.com'),
  ('NATAN BONFANTI COSTA', 'nabonfanti', 'nabonfanti@gruporoveri.com'),
  ('ERICK ROCHA DA SILVA', 'erirocha', 'erirocha@gruporoveri.com'),
  ('LETICIA VITORIA RODRIGUES BOLLINI ROCHA', 'lerocha', 'lerocha@gruporoveri.com'),
  ('GEOVANA SOUZA DA SILVA', 'geosouza', 'geosouza@gruporoveri.com'),
  ('MARIA PAMELA SILVA DE CRISTO', 'macristo', 'macristo@gruporoveri.com'),
  ('ROBERT RODRIGUES MARTINS', 'romartins', 'romartins@gruporoveri.com'),
  ('PRISCILA CANDIDA DE OLIVEIRA SANTOS', 'prissantos', 'prissantos@gruporoveri.com'),
  ('GUSTAVO FERREIRA SILVA', 'gufsilva', 'gufsilva@gruporoveri.com'),
  ('EMILLY MUNIZ TEIXEIRA', 'emteixeira', 'emteixeira@gruporoveri.com'),
  ('KAROLAYNE CRISTINA BRESSI DA SILVA', 'kabressi', 'kabressi@gruporoveri.com'),
  ('SANDRA LEOPOLDINO LEIRAS', 'saleiras', 'saleiras@gruporoveri.com'),
  ('GIOVANNA DA SILVA VARJAO', 'givarjao', 'givarjao@gruporoveri.com'),
  ('LAURA FERREIRA FAENSE', 'lafaense', 'lafaense@gruporoveri.com'),
  ('ALEXANDRINA FIGUEIREDO DE AQUINO', 'alaquina', 'alaquina@gruporoveri.com'),
  ('ROGERIO SILVA RODRIGUES', 'rogesilva', 'rogesilva@gruporoveri.com'),
  ('MILENA MACENA OLIVEIRA', 'mimacena', 'mimacena@gruporoveri.com'),
  ('OLIVIA ESTEVES MENESES', 'olmeneses', 'olmeneses@gruporoveri.com'),
  ('HENRIQUE SEVERINO DA SILVA', 'heseverino', 'heseverino@gruporoveri.com'),
  ('MICHELLY DA SILVA SANTOS', 'michessantos', 'michessantos@gruporoveri.com'),
  ('PALOMA MARQUES APOLIANO VAZ', 'pavaz', 'pavaz@gruporoveri.com'),
  ('ANA LUIZA DE OLIVEIRA GONCALVES', 'anluiza', 'anluiza@gruporoveri.com'),
  ('SAMUEL RODRIGUES DO AMARAL', 'samuamaral', 'samuamaral@gruporoveri.com'),
  ('YARA RIBEIRO DE OLIVEIRA', 'yaribeiro', 'yaribeiro@gruporoveri.com'),
  ('GEOVANNA LEANDRO FERREIRA', 'geferreira', 'geferreira@gruporoveri.com'),
  ('MURILO CAMPOLI DA SILVA', 'mucampoli', 'mucampoli@gruporoveri.com'),
  ('PAOLA CANDIDA BEZERRA', 'pcbezerra', 'pcbezerra@gruporoveri.com'),
  ('LUANA SILVA LELIS', 'lulelis', 'lulelis@gruporoveri.com'),
  ('CLEIDE ROSA DOS SANTOS', 'clesantos', 'clesantos@gruporoveri.com'),
  ('ELIANA FERNANDES DE LIMA', 'elflima', 'elflima@gruporoveri.com'),
  ('LUIZ HENRIQUE DIAS BERNARDES', 'lubernardes', 'lubernardes@gruporoveri.com'),
  ('BRUNO DOS SANTOS RIBEIRO BORGES', 'bruborges', 'bruborges@gruporoveri.com'),
  ('FABIANA MURARI GONCALVES', 'fabigoncalves', 'fabigoncalves@gruporoveri.com'),
  ('JOSY TALITA GONCALVES DE SOUSA', 'josysousa', 'josysousa@gruporoveri.com'),
  ('ANGELO MAXIMO SILVA VIEIRA', 'angvieira', 'angvieira@gruporoveri.com'),
  ('MARIA GENILDA DE ARAUJO LIMA', 'magelima', 'magelima@gruporoveri.com'),
  ('ADRIANO PALMEIRA LOPES', 'adlopes', 'adlopes@gruporoveri.com'),
  ('LARISSA ARIADNE COUTINHO CARVALHO ALVES', 'larialves', 'larialves@gruporoveri.com'),
  ('JEFFERSON DE SOUSA LEITE', 'jeleite', 'jeleite@gruporoveri.com'),
  ('RENATA GOMES DOS ANJOS', 'reanjos', 'reanjos@gruporoveri.com'),
  ('NATELLY SALGADO DE OLIVEIRA', 'nateoliveira', 'nateoliveira@gruporoveri.com'),
  ('YASMIM LAIS SANTOS REIS MARQUES', 'yamarques', 'yamarques@gruporoveri.com'),
  ('JHONATAN MONTEIRO DA SILVA', 'jhonsilva', 'jhonsilva@gruporoveri.com'),
  ('JULIANA CERQUEIRA', 'jucerqueira', 'jucerqueira@gruporoveri.com'),
  ('YASMIM DA SILVA MELO', 'yamelo', 'yamelo@gruporoveri.com'),
  ('MARIANE VITORIA GALDINO', 'magaldino', 'magaldino@gruporoveri.com'),
  ('VERA MOURA DA SILVA', 'vemoura', 'vemoura@gruporoveri.com'),
  ('KAROLINA DE OLIVEIRA SANTOS', 'karosantos', 'karosantos@gruporoveri.com'),
  ('ISABELLY LIMA BARRETO', 'isbarreto', 'isbarreto@gruporoveri.com'),
  ('TAINA APARECIDA SALES DA SILVA', 'taasilva', 'taasilva@gruporoveri.com'),
  ('RAISLENY DE CARVALHO', 'raycarvalho', 'raycarvalho@gruporoveri.com'),
  ('NILVA MARIA RABISQUIM', 'nirabisquim', 'nirabisquim@gruporoveri.com'),
  ('MATHEUS ALVES ELLERN SCUCUGLIA', 'mascucuglia', 'mascucuglia@gruporoveri.com'),
  ('MARIA TEREZA FRETEGOTTO', 'mafretegotto', 'mafretegotto@gruporoveri.com'),
  ('STHEU SCANCANI GALORO', 'stgaloro', 'stgaloro@gruporoveri.com'),
  ('ELAINE BISPO SOARES LIMA', 'elblima', 'elblima@gruporoveri.com'),
  ('JOSE CARLOS COSTA', 'joccosta', 'joccosta@gruporoveri.com'),
  ('GABRIELLA NASCIMENTO NEGRI', 'ganegri', 'ganegri@gruporoveri.com'),
  ('VINICIUS DE ALMEIDA ROMAGNOLO', 'viromagnolo', 'viromagnolo@gruporoveri.com'),
  ('GIULIA RIBEIRO TAVARES FARIAS MAGNO', 'gumagno', 'gumagno@gruporoveri.com'),
  ('KAREN CARVALHO DE SA', 'kasa', 'kasa@gruporoveri.com'),
  ('RANIELLY SILVA LEITE FRANCISCO', 'rinfrancisco', 'rinfrancisco@gruporoveri.com'),
  ('ARTHUR AVELINO CAMARGO', 'arcamargo', 'arcamargo@gruporoveri.com'),
  ('MAYARA THAYNA DE JESUS ALVES DA SILVA', 'majustino', 'majustino@gruporoveri.com'),
  ('VINICIUS DOS REIS PASSOS', 'vrpassos', 'vrpassos@gruporoveri.com'),
  ('MARISA DEMARCHI NOGUEIRA', 'marnogueira', 'marnogueira@gruporoveri.com'),
  ('EMILLY GONCALVES DE LIMA', 'emlima', 'emlima@gruporoveri.com'),
  ('JENNIFER CAMILA DOS SANTOS', 'jencsantos', 'jencsantos@gruporoveri.com'),
  ('JOYCE CRUZ DOS SANTOS', 'jocruz', 'jocruz@gruporoveri.com'),
  ('LEANNE SLENY FERREIRA FREITAS', 'leaferreira', 'leaferreira@gruporoveri.com'),
  ('LUIZA ROSA BISPO SOUSA', 'lubispo', 'lubispo@gruporoveri.com'),
  ('GABRIELLA SILVESTRE ANNUNCIATO', 'gaannunciato', 'gaannunciato@gruporoveri.com'),
  ('GIOVANNA SILVESTRE ANNUNCIATO', 'giannunciato', 'giannunciato@gruporoveri.com'),
  ('EDUARDA DE OLIVEIRA MARTINS', 'edmartins', 'edmartins@gruporoveri.com'),
  ('GIOVANNA BRITO DA SILVA', 'gidabsilva', 'gidabsilva@gruporoveri.com'),
  ('HELOISA BORGES DE LIMA', 'hebdlima', 'hebdlima@gruporoveri.com'),
  ('LUCAS PEREIRA CLAUDINO DOS SANTOS', 'luclsantos', 'luclsantos@gruporoveri.com'),
  ('INES PEREIRA DOS SANTOS', 'inpsantos', 'inpsantos@gruporoveri.com'),
  ('CINTHIA DE OLIVEIRA SOTOCORNO', 'cisotocorno', 'cisotocorno@gruporoveri.com'),
  ('THALIA XAVIER DE ALMEIDA', 'thxalmeida', 'thxalmeida@gruporoveri.com'),
  ('MARIA JOSE SILVA DE MELO', 'majmelo', 'majmelo@gruporoveri.com'),
  ('LAYANE SANTOS VITOR SILVA', 'laynsilva', 'laynsilva@gruporoveri.com'),
  ('RUI SOBREIRA LOPES', 'rulopes', 'rulopes@gruporoveri.com'),
  ('CINTIA DANIEL LIMA', 'cilima', 'cilima@gruporoveri.com'),
  ('GYOVANNA DOS SANTOS SALES', 'gysales', 'gysales@gruporoveri.com'),
  ('LEONARDO GUSTAVO GOMES LINCEVICIUS', 'lelincevicius', 'lelincevicius@gruporoveri.com'),
  ('STEFANIE CAROLINE OLIVEIRA CISTERNAS', 'stcisterna', 'stcisterna@gruporoveri.com'),
  ('DAVI MEDEIROS DA COSTA', 'dadcosta', 'dadcosta@gruporoveri.com'),
  ('ALICE SANTOS DE ALMEIDA VIEIRA', 'alvieira', 'alvieira@gruporoveri.com'),
  ('VANESSA TOSSATO', 'vatossato', 'vatossato@gruporoveri.com'),
  ('MONIQUE MESQUITA DA SILVA PAIXAO', 'mopaixao', 'mopaixao@gruporoveri.com'),
  ('VERONICA GONZAGA LEITE', 'veleite', 'veleite@gruporoveri.com'),
  ('GESSICA FERNANDES DA CRUZ', 'gefcruz', 'gefcruz@gruporoveri.com'),
  ('LUANY SALES DE FREITAS', 'lusfreitas', 'lusfreitas@gruporoveri.com'),
  ('MARIA EDUARDA LIMA GOMES', 'malgomes', 'malgomes@gruporoveri.com'),
  ('YANNE KARYNE FREITAS DO NASCIMENTO', 'yanascimento', 'yanascimento@gruporoveri.com'),
  ('SABRINA BARBOSA LEAO', 'saleao', 'saleao@gruporoveri.com'),
  ('ALINE CAMPOS RAIMUNDO', 'alraimundo', 'alraimundo@gruporoveri.com'),
  ('GABRIELA PAOLA DE CARVALHO', 'gapcarvalho', 'gapcarvalho@gruporoveri.com'),
  ('GUILHERME CAETANO BARBOZA DE LIMA', 'guclima', 'guclima@gruporoveri.com'),
  ('ELIANE JOSEFA DIAS', 'eldias', 'eldias@gruporoveri.com'),
  ('VICTOR FREITAS XALEGA', 'vixalega', 'vixalega@gruporoveri.com'),
  ('CAUAN BOAVISTA DE FREITAS', 'cabfreitas', 'cabfreitas@gruporoveri.com'),
  ('ANA MARIA DE OLIVEIRA FONSECA', 'anfonseca', 'anfonseca@gruporoveri.com'),
  ('NAIOBI SAPONHOS DE AGUIAR SOARES', 'nasoares', 'nasoares@gruporoveri.com'),
  ('ALEXANDRE MARQUES DA SILVA GUERRA', 'alguerra', 'alguerra@gruporoveri.com'),
  ('MARIA STEFANE MENDS FEITOSA', 'mafeitosa', 'mafeitosa@gruporoveri.com'),
  ('LUCAS VELOSO SILVA', 'lucveloso', 'lucveloso@gruporoveri.com'),
  ('MILLENA DOS SANTOS SILVA', 'missilva', 'missilva@gruporoveri.com'),
  ('ANNA CLARA STORTI CAMILO', 'ancamilo', 'ancamilo@gruporoveri.com'),
  ('EMILLY KAMILLY SIQUEIRA DA SILVA', 'emsiqueira', 'emsiqueira@gruporoveri.com'),
  ('JENIFER MAIRA LIMA DA SILVA', 'jemsilva', 'jemsilva@gruporoveri.com'),
  ('YARA RIBEIRO SOUZA', 'yasouza', 'yasouza@gruporoveri.com'),
  ('FERNANDA DE OLIVEIRA VIANA', 'feviana', 'feviana@gruporoveri.com'),
  ('STELLA SOUZA FREITAS', 'stfreitas', 'stfreitas@gruporoveri.com'),
  ('LARICE BENTO GARCIA', 'lagarcia', 'lagarcia@gruporoveri.com'),
  ('ANA JULIA SOARES DE MELO', 'anjmelo', 'anjmelo@gruporoveri.com'),
  ('NICOLE PIONA COSTA RODRIGUES', 'nicpiona', 'nicpiona@gruporoveri.com'),
  ('JULYA DA SILVA PEREIRA', 'julpereira', 'julpereira@gruporoveri.com'),
  ('JENNIFER LIZ DE ALMEIDA VIEIRA', 'jenvieira', 'jenvieira@gruporoveri.com'),
  ('KETHLEEN NATHALIA DOS SANTOS MORINI', 'kemorini', 'kemorini@gruporoveri.com'),
  ('RAYANE SOUSA DA SILVA', 'rayasilva', 'rayasilva@gruporoveri.com'),
  ('ROSANE CORREA SANTOS ALVES', 'rosalves', 'rosalves@gruporoveri.com'),
  ('GABRIELLA DO NASCIMENTO SILVA', 'gabnascimento', 'gabnascimento@gruporoveri.com'),
  ('ANA SARA RODRIGUES SILVA', 'annsilva', 'annsilva@gruporoveri.com'),
  ('MARLEIZE ERDEI PARRINI', 'maparrini', 'maparrini@gruporoveri.com'),
  ('BRUNO RAFAEL DOS SANTOS ABRAO', 'brabrao', 'brabrao@gruporoveri.com'),
  ('SILVANA COSTA BERTOLUCCI', 'sibertolucci', 'sibertolucci@gruporoveri.com'),
  ('DEBORA MACHADO', 'demachado', 'demachado@gruporoveri.com'),
  ('LENILZA ANSELMO REIS SANTOS', 'leanselmo', 'leanselmo@gruporoveri.com'),
  ('YURI CRISPIM DE LIMA', 'yulima', 'yulima@gruporoveri.com'),
  ('LUAN SANTOS MOTA', 'lumota', 'lumota@gruporoveri.com'),
  ('MATEUS BARREIROS MARQUES DE SOUZA', 'mabasouza', 'mabasouza@gruporoveri.com'),
  ('KALIL DE ALMEIDA VIEIRA', 'kaalvieira', 'kaalvieira@gruporoveri.com'),
  ('MARIA EDUARDA LIMA SILVA', 'malisilva', 'malisilva@gruporoveri.com'),
  ('KAUAI RODRIGUES BARBOSA', 'kabarbosa', 'kabarbosa@gruporoveri.com'),
  ('BEATRIZ SOUZA SILVA', 'besosilva', 'besosilva@gruporoveri.com'),
  ('JOVANA ESTEFANE NOGUEIRA DA SILVA', 'joessilva', 'joessilva@gruporoveri.com'),
  ('JENIFFER LOUREANO BOSSI DE BARROS', 'jebarros', 'jebarros@gruporoveri.com'),
  ('EMILI DOS SANTOS SILVA', 'emsimoura', 'emsimoura@gruporoveri.com'),
  ('VANESSA GOMES DE FREITAS', 'vafreitas', 'vafreitas@gruporoveri.com'),
  ('DEBORA PEREIRA SANTOS', 'depesantos', 'depesantos@gruporoveri.com'),
  ('RAUL SABINO SOLERA', 'rasolera', 'rasolera@gruporoveri.com'),
  ('GYOVANNA PASCHOAL FULINI RIBEIRO', 'gyribeiro', 'gyribeiro@gruporoveri.com'),
  ('GERUSIA MARTA FERNADES LINHARES', 'gelinhares', 'gelinhares@gruporoveri.com'),
  ('KELLY CRISTINA PINTO SILVEIRA', 'kesilveira', 'kesilveira@gruporoveri.com'),
  ('LEANY MARIA CAETANO OLIVEIRA', 'leaoliveira', 'leaoliveira@gruporoveri.com'),
  ('RAPHAEL CORREIA NEVES', 'racneves', 'racneves@gruporoveri.com'),
  ('LUCAS FERREIRA DA SILVA', 'lucferreira', 'lucferreira@gruporoveri.com'),
  ('LUCAS TAMASHIRO UJLAKI', 'luujlaki', 'luujlaki@gruporoveri.com'),
  ('RYAN CAVINATO BAZAN', 'rybazan', 'rybazan@gruporoveri.com'),
  ('MURILO ESTEVAM DE SOUZA', 'mursouza', 'mursouza@gruporoveri.com'),
  ('LUCAS FERNANDES BARROS', 'lubarros', 'lubarros@gruporoveri.com'),
  ('GIOVANNA GONCALVES CABRAL', 'gigcabral', 'gigcabral@gruporoveri.com'),
  ('VICTOR HUGO GONCALVES SANTOS', 'vihsantos', 'vihsantos@gruporoveri.com'),
  ('KEZIA LEAL', 'keleal', 'keleal@gruporoveri.com'),
  ('MARIA EDUARDA GUIMARAES LOPES', 'marlopes', 'marlopes@gruporoveri.com'),
  ('VITORIA CAMPOS AGUIAR', 'viaguiar', 'viaguiar@gruporoveri.com'),
  ('BENTO DE LIMA ALVES', 'betalves', 'betalves@gruporoveri.com'),
  ('YASMIN LIMA BARBOSA', 'yalbarbosa', 'yalbarbosa@gruporoveri.com'),
  ('YASMIM GUIMARAES CORDEIRO DOS SANTOS', 'yascordeiro', 'yascordeiro@gruporoveri.com'),
  ('SARA SILVA SANTOS', 'ssasantos', 'ssasantos@gruporoveri.com'),
  ('ANDREIA ALBERTO FURTADO FERREIRA', 'andrferreira', 'andrferreira@gruporoveri.com'),
  ('MANOELLA SENA BARBOSA', 'masbarbosa', 'masbarbosa@gruporoveri.com'),
  ('ESTHER SILVA', 'esthsilva', 'esthsilva@gruporoveri.com'),
  ('NIVEA KATIA DA SILVA BOAVENTURA', 'niboaventura', 'niboaventura@gruporoveri.com'),
  ('MARIA EDUARDA SOUZA DE LIMA', 'madulima', 'madulima@gruporoveri.com'),
  ('TATIANA SIQUEIRA DE MOURA', 'tatimoura', 'tatimoura@gruporoveri.com'),
  ('VITOR FERREIRA MORAIS', 'vimorais', 'vimorais@gruporoveri.com'),
  ('GIOVANA FERREIRA DA SILVA', 'gifsilva', 'gifsilva@gruporoveri.com'),
  ('FABIANA ABDALLA', 'faabdalla', 'faabdalla@gruporoveri.com'),
  ('THAIS REZENDE SILVA', 'threzende', 'threzende@gruporoveri.com'),
  ('LUCAS DA SILVA PEDROSA', 'ludpedrosa', 'ludpedrosa@gruporoveri.com'),
  ('FELIPE AGUIAR MENDES DO NASCIMENTO', 'feaguiar', 'feaguiar@gruporoveri.com'),
  ('ANA KATIA DA SILVA', 'ankatia', 'ankatia@gruporoveri.com'),
  ('CATARINA ALVES SILVA', 'catsilva', 'catsilva@gruporoveri.com'),
  ('PEDRO HENRIQUE LAVORATO', 'pelavorato', 'pelavorato@gruporoveri.com'),
  ('EDER NASCIMENTO ALVES', 'edalves', 'edalves@gruporoveri.com'),
  ('MELISSA BALBINO DA SILVA GOMES', 'megomes', 'megomes@gruporoveri.com'),
  ('LARISSA NASARIO PEREIRA', 'lapereira', 'lapereira@gruporoveri.com'),
  ('RENAN DA SILVA BULGARELLI', 'rebulgarelli', 'rebulgarelli@gruporoveri.com'),
  ('ANA CAROLINE SOUZA OLIVIA', 'anolivia', 'anolivia@gruporoveri.com'),
  ('PEDRO HENRIQUE NASCIMENTO DA SILVA', 'phenrique', 'phenrique@gruporoveri.com'),
  ('LIVIA NOBREGA PIGHIN', 'lipighin', 'lipighin@gruporoveri.com'),
  ('KARINA MUNIZ VIEIRA', 'kamuniz', 'kamuniz@gruporoveri.com'),
  ('VITOR HUGO ALVARENGA FACCIOLO', 'vifacciolo', 'vifacciolo@gruporoveri.com'),
  ('BRENDA MORGAN ESTRELA DA SILVA', 'brestrela', 'brestrela@gruporoveri.com'),
  ('GABRIELLY SANTOS OLIVEIRA', 'gbsoliveira', 'gbsoliveira@gruporoveri.com'),
  ('JADE ALVES DE ARAUJO', 'jaaraujo', 'jaaraujo@gruporoveri.com'),
  ('ISABELA CRISTINA DE SOUZA', 'iscsouza', 'iscsouza@gruporoveri.com'),
  ('AMANDA CUER FERREIRA', 'amferreira', 'amferreira@gruporoveri.com'),
  ('ANA KAROLINA PEREIRA CRUZ', 'ankcruz', 'ankcruz@gruporoveri.com'),
  ('LETICIA SIQUEIRA BISPO', 'lebispo', 'lebispo@gruporoveri.com'),
  ('KAUE RAMOS PEREIRA', 'kapereira', 'kapereira@gruporoveri.com'),
  ('DANIELLE LIMA DA COSTA', 'dacosta', 'dacosta@gruporoveri.com'),
  ('NADJA GAMA DOS SANTOS', 'ngama', 'ngama@gruporoveri.com'),
  ('MAYSA DOS SANTOS NERES', 'maneres', 'maneres@gruporoveri.com'),
  ('TAMIRES NEVES DOS SANTOS', 'tansantos', 'tansantos@gruporoveri.com'),
  ('MAXINE LUARA RODRIGUES BATISTA DA SILVA', 'maluara', 'maluara@gruporoveri.com'),
  ('FABIANA APARECIDA BASILIO', 'fabasilio', 'fabasilio@gruporoveri.com'),
  ('STEFANIE PAMPOLINI DE ASSIS', 'stassis', 'stassis@gruporoveri.com'),
  ('LUANA DIAS BRAZ', 'lubraz', 'lubraz@gruporoveri.com'),
  ('FRANCIELE QUERCIA DE OLIVEIRA DOS REIS', 'frreis', 'frreis@gruporoveri.com'),
  ('YASMIN MACHADO DA SILVA', 'yasmachado', 'yasmachado@gruporoveri.com'),
  ('DAVI JOSE NIETTO DE SOUZA', 'danietto', 'danietto@gruporoveri.com'),
  ('VITOR MENDONCA LOPES', 'vilopes', 'vilopes@gruporoveri.com'),
  ('CAROLINA NUNES DA SILVA', 'carsnunes', 'carsnunes@gruporoveri.com'),
  ('PRISCILA FONTES DE AZEVEDO', 'prazevedo', 'prazevedo@gruporoveri.com'),
  ('ERIKA MACIEL PEREIRA', 'ermpereira', 'ermpereira@gruporoveri.com'),
  ('MARCOS VINICIUS DE LIMA COSTA', 'mavcosta', 'mavcosta@gruporoveri.com'),
  ('THAIS SANTOS LOURENCO', 'thlourenco', 'thlourenco@gruporoveri.com'),
  ('DEISY KIMBERLLY SATILITE ARAUJO', 'dearaujo', 'dearaujo@gruporoveri.com'),
  ('BRENO ALVES NOGUEIRA', 'brenogueira', 'brenogueira@gruporoveri.com'),
  ('DANIELLE DA SILVA WENCESLAU', 'dawenceslau', 'dawenceslau@gruporoveri.com'),
  ('FABIO EISHIMA DE CASTRO GUIRRA', 'faguirra', 'faguirra@gruporoveri.com'),
  ('GEOVANA SILVA MATARUCO DE GODOY', 'gegodoy', 'gegodoy@gruporoveri.com'),
  ('HAYANE DE MOURA GOMES', 'hagomes', 'hagomes@gruporoveri.com'),
  ('DANIELA MOURA ANDRADE', 'daneto', 'daneto@gruporoveri.com'),
  ('CARLOS VINICIUS DIAS DA SILVA', 'cavinicius', 'cavinicius@gruporoveri.com'),
  ('GEOVANA DE JESUS SANTOS', 'geovjesus', 'geovjesus@gruporoveri.com')
ON CONFLICT (email) DO NOTHING;

-- Índices para melhor performance
CREATE INDEX IF NOT EXISTS idx_operators_username ON operators(username);
CREATE INDEX IF NOT EXISTS idx_operators_email ON operators(email);
