-- ==============================================
-- INSERIR OPERADORES (Grupo Roveri)
-- Execute no SQL Editor do Supabase
-- Atualizado em: 21/04/2026
-- ==============================================
-- Este script insere operadores na tabela users
-- Usa ON CONFLICT para ignorar duplicatas
-- ==============================================

INSERT INTO users (username, name, email, role, is_active) VALUES
('sabmedeiros', 'SABRINA NUNES DE MEDEIROS', 'sabmedeiros@gruporoveri.com', 'operator', true),
('fbugada', 'FABIOLLA BUGADA', 'fbugada@gruporoveri.com', 'operator', true),
('nbgraciano', 'NICHOLAS BERNARDO GRACIANO', 'nbgraciano@gruporoveri.com', 'operator', true),
('rolsantos', 'ROBERT LEITE SANTOS', 'rolsantos@gruporoveri.com', 'operator', true),
('thaysilva', 'THAYNARA DOS SANTOS SILVA', 'thaysilva@gruporoveri.com', 'operator', true),
('norezende', 'NOEMI REZENDE ESTEVAM', 'norezende@gruporoveri.com', 'operator', true),
('kosantos', 'KAROLAINE OLIVEIRA SANTOS', 'kosantos@gruporoveri.com', 'operator', true),
('apglima', 'ANA PAULA GONCALVES LIMA', 'apglima@gruporoveri.com', 'operator', true),
('asleal', 'ARTHUR DE SOUSA LEAL', 'asleal@gruporoveri.com', 'operator', true),
('phcoelho', 'PEDRO HENRIQUE COELHO PEREIRA', 'phcoelho@gruporoveri.com', 'operator', true),
('pansantos', 'PAULA NATALIA SILVA SANTOS', 'pansantos@gruporoveri.com', 'operator', true),
('chalencar', 'CAIO HENRIQUE ARAUJO DE ALENCAR', 'chalencar@gruporoveri.com', 'operator', true),
('thandrade', 'THAIS ANDRADE SANTOS', 'thandrade@gruporoveri.com', 'operator', true),
('fbatista', 'FERNANDA BATISTA DA ROCHA', 'fbatista@gruporoveri.com', 'operator', true),
('afgavezedo', 'ANA FLAVIA GONCALVES DE AZEVEDO', 'afgavezedo@gruporoveri.com', 'operator', true),
('npelegrini', 'NATHALY DA SILVA PELEGRINI', 'npelegrini@gruporoveri.com', 'operator', true),
('dandsilva', 'DANIELE DA SILVA', 'dandsilva@gruporoveri.com', 'operator', true),
('rdsousa', 'REGINE DE SOUSA SILVA', 'rdsousa@gruporoveri.com', 'operator', true),
('mpapaletti', 'MARINA PALETTI', 'mpapaletti@gruporoveri.com', 'operator', true),
('regaugusto', 'REBECA GABRIELI SOUZA AUGUSTO', 'regaugusto@gruporoveri.com', 'operator', true),
('juevangelista', 'JULIANE ALVES EVANGELISTA DOS SANTOS', 'juevangelista@gruporoveri.com', 'operator', true),
('gaspereira', 'GABRIEL SOARES DA SILVA PEREIRA', 'gaspereira@gruporoveri.com', 'operator', true),
('gabvsantos', 'GABRIEL VINICIUS DOS SANTOS', 'gabvsantos@gruporoveri.com', 'operator', true),
('adantas', 'ALAN DANTAS SANTOS', 'adantas@gruporoveri.com', 'operator', true),
('maarodrogues', 'MARIA APARECIDA RODRIGUES FARIAS', 'maarodrogues@gruporoveri.com', 'operator', true),
('brnsilva', 'BRUNO NOVAIS DA SILVA', 'brnsilva@gruporoveri.com', 'operator', true),
('kabella', 'KARINA GONCIARENCO BELLA', 'kabella@gruporoveri.com', 'operator', true),
('givrodrigues', 'GIOVANNA VALERIA RODRIGUES', 'givrodrigues@gruporoveri.com', 'operator', true),
('binunes', 'BIANCA SOUSA NUNES', 'binunes@gruporoveri.com', 'operator', true),
('luasousa', 'LUANA DIAS DE SOUSA', 'luasousa@gruporoveri.com', 'operator', true),
('lbravo', 'LAIS MARQUES BRAVO', 'lbravo@gruporoveri.com', 'operator', true),
('ggqueiroz', 'GABRIEL GOMES QUEIROZ', 'ggqueiroz@gruporoveri.com', 'operator', true),
('abasaglia', 'AGATA BITTENCOURT BASAGLIA CUNHA', 'abasaglia@gruporoveri.com', 'operator', true),
('jlsobrinho', 'JOAO DE LIMA MELO SOBRINHO', 'jlsobrinho@gruporoveri.com', 'operator', true),
('janascimento', 'JULIA ALEXANDRA SOUZA NASCIMENTO', 'janascimento@gruporoveri.com', 'operator', true),
('edunascimento', 'EDUARDO SANTOS DO NASCIMENTO', 'edunascimento@gruporoveri.com', 'operator', true),
('amaporto', 'AMANDA SANTOS PORTO', 'amaporto@gruporoveri.com', 'operator', true),
('visousa', 'VITORIA EMANUELE GOMES DE SOUSA', 'visousa@gruporoveri.com', 'operator', true),
('taamartins', 'TAINARA AMBROZIO MARTINS', 'taamartins@gruporoveri.com', 'operator', true),
('maaleixo', 'MAYSA CARLA ALEIXO', 'maaleixo@gruporoveri.com', 'operator', true),
('gamergulhao', 'GABRIEL MASCIARELLI FERREIRA MERGULHAO', 'gamergulhao@gruporoveri.com', 'operator', true),
('elvieira', 'ELDA REGIANE BALERO VIEIRA', 'elvieira@gruporoveri.com', 'operator', true),
('recordeiro', 'RENATA CORDEIRO', 'recordeiro@gruporoveri.com', 'operator', true),
('namiranda', 'NATALIA SILVA MIRANDA', 'namiranda@gruporoveri.com', 'operator', true),
('aucarvalho', 'AUGUSTO FELIPE TAVARES DE CARVALHO', 'aucarvalho@gruporoveri.com', 'operator', true),
('gahidalgo', 'GABRIEL MOTTA HIDALGO', 'gahidalgo@gruporoveri.com', 'operator', true),
('mcferreirta', 'MARIA CLAUDIA FERREIRA DO NASCIMENTO', 'mcferreirta@gruporoveri.com', 'operator', true),
('vsouza', 'VERONICA APARECIDA DE SOUZA', 'vsouza@gruporoveri.com', 'operator', true),
('frsousa', 'FRANCILENE MACIEL SOUSA', 'frsousa@gruporoveri.com', 'operator', true),
('idaniela', 'INGRID DANIELA BENTO DA SILVA', 'idaniela@gruporoveri.com', 'operator', true),
('ragoncalves', 'RAFAELA PEREIRA GONCALVES', 'ragoncalves@gruporoveri.com', 'operator', true),
('samagalhaes', 'SARA DE BARROS MAGALHAES', 'samagalhaes@gruporoveri.com', 'operator', true),
('igpereira', 'IGOR CHINELATO PEREIRA', 'igpereira@gruporoveri.com', 'operator', true),
('juleite', 'JULIA MARINHO LEITE', 'juleite@gruporoveri.com', 'operator', true),
('arrodrigues', 'ARTHUR CONDE RODRIGUES', 'arrodrigues@gruporoveri.com', 'operator', true),
('gafolgosi', 'GABRIELLA TONON FOLGOSI', 'gafolgosi@gruporoveri.com', 'operator', true),
('kalves', 'KATIA SANTOS ALVES', 'kalves@gruporoveri.com', 'operator', true),
('cnunes', 'CRISTIANE NUNES DE OLIVEIRA', 'cnunes@gruporoveri.com', 'operator', true),
('navera', 'NATASHA SILVA VERA', 'navera@gruporoveri.com', 'operator', true),
('jalicosta', 'JAMILLY LIMA DA COSTA', 'jalicosta@gruporoveri.com', 'operator', true),
('thiaraujo', 'THIELLY DE ARAUJO LIMA', 'thiaraujo@gruporoveri.com', 'operator', true),
('befreitas', 'BERNARDO DE PAIVA FREITAS', 'befreitas@gruporoveri.com', 'operator', true),
('thadsilva', 'THALIA APARECIDA DA SILVA', 'thadsilva@gruporoveri.com', 'operator', true),
('jovdias', 'JOAO VICTOR OLIVEIRA DIAS', 'jovdias@gruporoveri.com', 'operator', true),
('garoliveira', 'GABRIELLA RODRIGUES OLIVEIRA', 'garoliveira@gruporoveri.com', 'operator', true),
('miramos', 'MICHELE KAYTHLYN FERREIRA RAMOS', 'miramos@gruporoveri.com', 'operator', true),
('gasoliveira', 'GABRIEL SILVA DE OLIVEIRA', 'gasoliveira@gruporoveri.com', 'operator', true),
('sesantos', 'SEVERINA RIBEIRO DOS SANTOS', 'sesantos@gruporoveri.com', 'operator', true),
('naypereira', 'NAYARA PEREIRA DOS SANTOS', 'naypereira@gruporoveri.com', 'operator', true),
('criferreira', 'CRISLANE FERREIRA SILVA', 'criferreira@gruporoveri.com', 'operator', true),
('gejeronimo', 'GEOVANA JERONIMO DE SOUSA', 'gejeronimo@gruporoveri.com', 'operator', true),
('anluz', 'ANA CAROLINE SILVA LUZ DE OLIVEIRA', 'anluz@gruporoveri.com', 'operator', true),
('otvitor', 'OTAVIO VAILANT VITOR', 'otvitor@gruporoveri.com', 'operator', true),
('nassis', 'NATASHA ASSIS DOS SANTOS', 'nassis@gruporoveri.com', 'operator', true),
('alemelo', 'ALESSANDRA SANTOS DE MELO', 'alemelo@gruporoveri.com', 'operator', true),
('bisantos', 'BIANCA GOMES DOS SANTOS', 'bisantos@gruporoveri.com', 'operator', true),
('nifreitas', 'NICOLY AMARAL DE FREITAS', 'nifreitas@gruporoveri.com', 'operator', true),
('italencar', 'ITALO CARDOSO DA ROCHA ALENCAR', 'italencar@gruporoveri.com', 'operator', true),
('ansbeatriz', 'ANA BEATRIZ DA SILVA', 'ansbeatriz@gruporoveri.com', 'operator', true),
('ancardoso', 'ANE JAMILE CARDOSO PEREIRA', 'ancardoso@gruporoveri.com', 'operator', true),
('frcosta', 'FRANCISCA NAZARIO DA COSTA', 'frcosta@gruporoveri.com', 'operator', true),
('mabusaranho', 'MATHEUS MANDRO BUSARANHO', 'mabusaranho@gruporoveri.com', 'operator', true),
('tiyonemura', 'TIAGO IORI YONEMURA', 'tiyonemura@gruporoveri.com', 'operator', true),
('natsantana', 'NATHYELLE PEREIRA SANTANA', 'natsantana@gruporoveri.com', 'operator', true),
('gianzolin', 'GIOVANNA PAREJA ANZOLIN', 'gianzolin@gruporoveri.com', 'operator', true),
('kepaulino', 'KELLY BARBOSA OLIVEIRA PAULINO', 'kepaulino@gruporoveri.com', 'operator', true),
('brbassi', 'BRUNA BONAVOLHA BASSI', 'brbassi@gruporoveri.com', 'operator', true),
('jodiniz', 'JOYCE DINIZ SOUZA', 'jodiniz@gruporoveri.com', 'operator', true),
('hapereira', 'HAYALA VITORIA SILVA PEREIRA', 'hapereira@gruporoveri.com', 'operator', true),
('nabonfanti', 'NATAN BONFANTI COSTA', 'nabonfanti@gruporoveri.com', 'operator', true),
('erirocha', 'ERICK ROCHA DA SILVA', 'erirocha@gruporoveri.com', 'operator', true),
('lerocha', 'LETICIA VITORIA RODRIGUES BOLLINI ROCHA', 'lerocha@gruporoveri.com', 'operator', true),
('geosouza', 'GEOVANA SOUZA DA SILVA', 'geosouza@gruporoveri.com', 'operator', true),
('macristo', 'MARIA PAMELA SILVA DE CRISTO', 'macristo@gruporoveri.com', 'operator', true),
('romartins', 'ROBERT RODRIGUES MARTINS', 'romartins@gruporoveri.com', 'operator', true),
('prissantos', 'PRISCILA CANDIDA DE OLIVEIRA SANTOS', 'prissantos@gruporoveri.com', 'operator', true),
('gufsilva', 'GUSTAVO FERREIRA SILVA', 'gufsilva@gruporoveri.com', 'operator', true),
('emteixeira', 'EMILLY MUNIZ TEIXEIRA', 'emteixeira@gruporoveri.com', 'operator', true),
('kabressi', 'KAROLAYNE CRISTINA BRESSI DA SILVA', 'kabressi@gruporoveri.com', 'operator', true),
('saleiras', 'SANDRA LEOPOLDINO LEIRAS', 'saleiras@gruporoveri.com', 'operator', true),
('givarjao', 'GIOVANNA DA SILVA VARJAO', 'givarjao@gruporoveri.com', 'operator', true),
('lafaense', 'LAURA FERREIRA FAENSE', 'lafaense@gruporoveri.com', 'operator', true),
('alaquina', 'ALEXANDRINA FIGUEIREDO DE AQUINO', 'alaquina@gruporoveri.com', 'operator', true),
('rogesilva', 'ROGERIO SILVA RODRIGUES', 'rogesilva@gruporoveri.com', 'operator', true),
('mimacena', 'MILENA MACENA OLIVEIRA', 'mimacena@gruporoveri.com', 'operator', true),
('olmeneses', 'OLIVIA ESTEVES MENESES', 'olmeneses@gruporoveri.com', 'operator', true),
('heseverino', 'HENRIQUE SEVERINO DA SILVA', 'heseverino@gruporoveri.com', 'operator', true),
('michessantos', 'MICHELLY DA SILVA SANTOS', 'michessantos@gruporoveri.com', 'operator', true),
('pavaz', 'PALOMA MARQUES APOLIANO VAZ', 'pavaz@gruporoveri.com', 'operator', true),
('anluiza', 'ANA LUIZA DE OLIVEIRA GONCALVES', 'anluiza@gruporoveri.com', 'operator', true),
('samuamaral', 'SAMUEL RODRIGUES DO AMARAL', 'samuamaral@gruporoveri.com', 'operator', true),
('yaribeiro', 'YARA RIBEIRO DE OLIVEIRA', 'yaribeiro@gruporoveri.com', 'operator', true),
('geferreira', 'GEOVANNA LEANDRO FERREIRA', 'geferreira@gruporoveri.com', 'operator', true),
('mucampoli', 'MURILO CAMPOLI DA SILVA', 'mucampoli@gruporoveri.com', 'operator', true),
('pcbezerra', 'PAOLA CANDIDA BEZERRA', 'pcbezerra@gruporoveri.com', 'operator', true),
('lulelis', 'LUANA SILVA LELIS', 'lulelis@gruporoveri.com', 'operator', true),
('clesantos', 'CLEIDE ROSA DOS SANTOS', 'clesantos@gruporoveri.com', 'operator', true),
('elflima', 'ELIANA FERNANDES DE LIMA', 'elflima@gruporoveri.com', 'operator', true),
('lubernardes', 'LUIZ HENRIQUE DIAS BERNARDES', 'lubernardes@gruporoveri.com', 'operator', true),
('bruborges', 'BRUNO DOS SANTOS RIBEIRO BORGES', 'bruborges@gruporoveri.com', 'operator', true),
('fabigoncalves', 'FABIANA MURARI GONCALVES', 'fabigoncalves@gruporoveri.com', 'operator', true),
('josysousa', 'JOSY TALITA GONCALVES DE SOUSA', 'josysousa@gruporoveri.com', 'operator', true),
('angvieira', 'ANGELO MAXIMO SILVA VIEIRA', 'angvieira@gruporoveri.com', 'operator', true),
('magelima', 'MARIA GENILDA DE ARAUJO LIMA', 'magelima@gruporoveri.com', 'operator', true),
('adlopes', 'ADRIANO PALMEIRA LOPES', 'adlopes@gruporoveri.com', 'operator', true),
('larialves', 'LARISSA ARIADNE COUTINHO CARVALHO ALVES', 'larialves@gruporoveri.com', 'operator', true),
('jeleite', 'JEFFERSON DE SOUSA LEITE', 'jeleite@gruporoveri.com', 'operator', true),
('reanjos', 'RENATA GOMES DOS ANJOS', 'reanjos@gruporoveri.com', 'operator', true),
('nateoliveira', 'NATELLY SALGADO DE OLIVEIRA', 'nateoliveira@gruporoveri.com', 'operator', true),
('yamarques', 'YASMIM LAIS SANTOS REIS MARQUES', 'yamarques@gruporoveri.com', 'operator', true),
('jhonsilva', 'JHONATAN MONTEIRO DA SILVA', 'jhonsilva@gruporoveri.com', 'operator', true),
('jucerqueira', 'JULIANA CERQUEIRA', 'jucerqueira@gruporoveri.com', 'operator', true),
('yamelo', 'YASMIM DA SILVA MELO', 'yamelo@gruporoveri.com', 'operator', true),
('magaldino', 'MARIANE VITORIA GALDINO', 'magaldino@gruporoveri.com', 'operator', true),
('vemoura', 'VERA MOURA DA SILVA', 'vemoura@gruporoveri.com', 'operator', true),
('karosantos', 'KAROLINA DE OLIVEIRA SANTOS', 'karosantos@gruporoveri.com', 'operator', true),
('isbarreto', 'ISABELLY LIMA BARRETO', 'isbarreto@gruporoveri.com', 'operator', true),
('taasilva', 'TAINA APARECIDA SALES DA SILVA', 'taasilva@gruporoveri.com', 'operator', true),
('raycarvalho', 'RAISLENY DE CARVALHO', 'raycarvalho@gruporoveri.com', 'operator', true),
('nirabisquim', 'NILVA MARIA RABISQUIM', 'nirabisquim@gruporoveri.com', 'operator', true),
('mascucuglia', 'MATHEUS ALVES ELLERN SCUCUGLIA', 'mascucuglia@gruporoveri.com', 'operator', true),
('mafretegotto', 'MARIA TEREZA FRETEGOTTO', 'mafretegotto@gruporoveri.com', 'operator', true),
('stgaloro', 'STHEU SCANCANI GALORO', 'stgaloro@gruporoveri.com', 'operator', true),
('elblima', 'ELAINE BISPO SOARES LIMA', 'elblima@gruporoveri.com', 'operator', true),
('joccosta', 'JOSE CARLOS COSTA', 'joccosta@gruporoveri.com', 'operator', true),
('ganegri', 'GABRIELLA NASCIMENTO NEGRI', 'ganegri@gruporoveri.com', 'operator', true),
('viromagnolo', 'VINICIUS DE ALMEIDA ROMAGNOLO', 'viromagnolo@gruporoveri.com', 'operator', true),
('gumagno', 'GIULIA RIBEIRO TAVARES FARIAS MAGNO', 'gumagno@gruporoveri.com', 'operator', true),
('kasa', 'KAREN CARVALHO DE SA', 'kasa@gruporoveri.com', 'operator', true),
('rinfrancisco', 'RANIELLY SILVA LEITE FRANCISCO', 'rinfrancisco@gruporoveri.com', 'operator', true),
('arcamargo', 'ARTHUR AVELINO CAMARGO', 'arcamargo@gruporoveri.com', 'operator', true),
('majustino', 'MAYARA THAYNA DE JESUS ALVES DA SILVA', 'majustino@gruporoveri.com', 'operator', true),
('vrpassos', 'VINICIUS DOS REIS PASSOS', 'vrpassos@gruporoveri.com', 'operator', true),
('marnogueira', 'MARISA DEMARCHI NOGUEIRA', 'marnogueira@gruporoveri.com', 'operator', true),
('emlima', 'EMILLY GONCALVES DE LIMA', 'emlima@gruporoveri.com', 'operator', true),
('jencsantos', 'JENNIFER CAMILA DOS SANTOS', 'jencsantos@gruporoveri.com', 'operator', true),
('jocruz', 'JOYCE CRUZ DOS SANTOS', 'jocruz@gruporoveri.com', 'operator', true),
('leaferreira', 'LEANNE SLENY FERREIRA FREITAS', 'leaferreira@gruporoveri.com', 'operator', true),
('lubispo', 'LUIZA ROSA BISPO SOUSA', 'lubispo@gruporoveri.com', 'operator', true),
('gaannunciato', 'GABRIELLA SILVESTRE ANNUNCIATO', 'gaannunciato@gruporoveri.com', 'operator', true),
('giannunciato', 'GIOVANNA SILVESTRE ANNUNCIATO', 'giannunciato@gruporoveri.com', 'operator', true),
('edmartins', 'EDUARDA DE OLIVEIRA MARTINS', 'edmartins@gruporoveri.com', 'operator', true),
('gidabsilva', 'GIOVANNA BRITO DA SILVA', 'gidabsilva@gruporoveri.com', 'operator', true),
('hebdlima', 'HELOISA BORGES DE LIMA', 'hebdlima@gruporoveri.com', 'operator', true),
('luclsantos', 'LUCAS PEREIRA CLAUDINO DOS SANTOS', 'luclsantos@gruporoveri.com', 'operator', true),
('inpsantos', 'INES PEREIRA DOS SANTOS', 'inpsantos@gruporoveri.com', 'operator', true),
('cisotocorno', 'CINTHIA DE OLIVEIRA SOTOCORNO', 'cisotocorno@gruporoveri.com', 'operator', true),
('thxalmeida', 'THALIA XAVIER DE ALMEIDA', 'thxalmeida@gruporoveri.com', 'operator', true),
('majmelo', 'MARIA JOSE SILVA DE MELO', 'majmelo@gruporoveri.com', 'operator', true),
('laynsilva', 'LAYANE SANTOS VITOR SILVA', 'laynsilva@gruporoveri.com', 'operator', true),
('rulopes', 'RUI SOBREIRA LOPES', 'rulopes@gruporoveri.com', 'operator', true),
('cilima', 'CINTIA DANIEL LIMA', 'cilima@gruporoveri.com', 'operator', true),
('gysales', 'GYOVANNA DOS SANTOS SALES', 'gysales@gruporoveri.com', 'operator', true),
('lelincevicius', 'LEONARDO GUSTAVO GOMES LINCEVICIUS', 'lelincevicius@gruporoveri.com', 'operator', true),
('stcisterna', 'STEFANIE CAROLINE OLIVEIRA CISTERNAS', 'stcisterna@gruporoveri.com', 'operator', true),
('dadcosta', 'DAVI MEDEIROS DA COSTA', 'dadcosta@gruporoveri.com', 'operator', true),
('alvieira', 'ALICE SANTOS DE ALMEIDA VIEIRA', 'alvieira@gruporoveri.com', 'operator', true),
('vatossato', 'VANESSA TOSSATO', 'vatossato@gruporoveri.com', 'operator', true),
('mopaixao', 'MONIQUE MESQUITA DA SILVA PAIXAO', 'mopaixao@gruporoveri.com', 'operator', true),
('veleite', 'VERONICA GONZAGA LEITE', 'veleite@gruporoveri.com', 'operator', true),
('gefcruz', 'GESSICA FERNANDES DA CRUZ', 'gefcruz@gruporoveri.com', 'operator', true),
('lusfreitas', 'LUANY SALES DE FREITAS', 'lusfreitas@gruporoveri.com', 'operator', true),
('malgomes', 'MARIA EDUARDA LIMA GOMES', 'malgomes@gruporoveri.com', 'operator', true),
('yanascimento', 'YANNE KARYNE FREITAS DO NASCIMENTO', 'yanascimento@gruporoveri.com', 'operator', true),
('saleao', 'SABRINA BARBOSA LEAO', 'saleao@gruporoveri.com', 'operator', true),
('alraimundo', 'ALINE CAMPOS RAIMUNDO', 'alraimundo@gruporoveri.com', 'operator', true),
('gapcarvalho', 'GABRIELA PAOLA DE CARVALHO', 'gapcarvalho@gruporoveri.com', 'operator', true),
('guclima', 'GUILHERME CAETANO BARBOZA DE LIMA', 'guclima@gruporoveri.com', 'operator', true),
('eldias', 'ELIANE JOSEFA DIAS', 'eldias@gruporoveri.com', 'operator', true),
('vixalega', 'VICTOR FREITAS XALEGA', 'vixalega@gruporoveri.com', 'operator', true),
('cabfreitas', 'CAUAN BOAVISTA DE FREITAS', 'cabfreitas@gruporoveri.com', 'operator', true),
('anfonseca', 'ANA MARIA DE OLIVEIRA FONSECA', 'anfonseca@gruporoveri.com', 'operator', true),
('nasoares', 'NAIOBI SAPONHOS DE AGUIAR SOARES', 'nasoares@gruporoveri.com', 'operator', true),
('alguerra', 'ALEXANDRE MARQUES DA SILVA GUERRA', 'alguerra@gruporoveri.com', 'operator', true),
('mafeitosa', 'MARIA STEFANE MENDS FEITOSA', 'mafeitosa@gruporoveri.com', 'operator', true),
('lucveloso', 'LUCAS VELOSO SILVA', 'lucveloso@gruporoveri.com', 'operator', true),
('missilva', 'MILLENA DOS SANTOS SILVA', 'missilva@gruporoveri.com', 'operator', true),
('ancamilo', 'ANNA CLARA STORTI CAMILO', 'ancamilo@gruporoveri.com', 'operator', true),
('emsiqueira', 'EMILLY KAMILLY SIQUEIRA DA SILVA', 'emsiqueira@gruporoveri.com', 'operator', true),
('jemsilva', 'JENIFER MAIRA LIMA DA SILVA', 'jemsilva@gruporoveri.com', 'operator', true),
('yasouza', 'YARA RIBEIRO SOUZA', 'yasouza@gruporoveri.com', 'operator', true),
('feviana', 'FERNANDA DE OLIVEIRA VIANA', 'feviana@gruporoveri.com', 'operator', true),
('stfreitas', 'STELLA SOUZA FREITAS', 'stfreitas@gruporoveri.com', 'operator', true),
('lagarcia', 'LARICE BENTO GARCIA', 'lagarcia@gruporoveri.com', 'operator', true),
('anjmelo', 'ANA JULIA SOARES DE MELO', 'anjmelo@gruporoveri.com', 'operator', true),
('nicpiona', 'NICOLE PIONA COSTA RODRIGUES', 'nicpiona@gruporoveri.com', 'operator', true),
('julpereira', 'JULYA DA SILVA PEREIRA', 'julpereira@gruporoveri.com', 'operator', true),
('jenvieira', 'JENNIFER LIZ DE ALMEIDA VIEIRA', 'jenvieira@gruporoveri.com', 'operator', true),
('kemorini', 'KETHLEEN NATHALIA DOS SANTOS MORINI', 'kemorini@gruporoveri.com', 'operator', true),
('rayasilva', 'RAYANE SOUSA DA SILVA', 'rayasilva@gruporoveri.com', 'operator', true),
('rosalves', 'ROSANE CORREA SANTOS ALVES', 'rosalves@gruporoveri.com', 'operator', true),
('gabnascimento', 'GABRIELLA DO NASCIMENTO SILVA', 'gabnascimento@gruporoveri.com', 'operator', true),
('annsilva', 'ANA SARA RODRIGUES SILVA', 'annsilva@gruporoveri.com', 'operator', true),
('maparrini', 'MARLEIZE ERDEI PARRINI', 'maparrini@gruporoveri.com', 'operator', true),
('brabrao', 'BRUNO RAFAEL DOS SANTOS ABRAO', 'brabrao@gruporoveri.com', 'operator', true),
('sibertolucci', 'SILVANA COSTA BERTOLUCCI', 'sibertolucci@gruporoveri.com', 'operator', true),
('demachado', 'DEBORA MACHADO', 'demachado@gruporoveri.com', 'operator', true),
('leanselmo', 'LENILZA ANSELMO REIS SANTOS', 'leanselmo@gruporoveri.com', 'operator', true),
('yulima', 'YURI CRISPIM DE LIMA', 'yulima@gruporoveri.com', 'operator', true),
('lumota', 'LUAN SANTOS MOTA', 'lumota@gruporoveri.com', 'operator', true),
('mabasouza', 'MATEUS BARREIROS MARQUES DE SOUZA', 'mabasouza@gruporoveri.com', 'operator', true),
('kaalvieira', 'KALIL DE ALMEIDA VIEIRA', 'kaalvieira@gruporoveri.com', 'operator', true),
('malisilva', 'MARIA EDUARDA LIMA SILVA', 'malisilva@gruporoveri.com', 'operator', true),
('kabarbosa', 'KAUAI RODRIGUES BARBOSA', 'kabarbosa@gruporoveri.com', 'operator', true),
('besosilva', 'BEATRIZ SOUZA SILVA', 'besosilva@gruporoveri.com', 'operator', true),
('joessilva', 'JOVANA ESTEFANE NOGUEIRA DA SILVA', 'joessilva@gruporoveri.com', 'operator', true),
('jebarros', 'JENIFFER LOUREANO BOSSI DE BARROS', 'jebarros@gruporoveri.com', 'operator', true),
('emsimoura', 'EMILI DOS SANTOS SILVA', 'emsimoura@gruporoveri.com', 'operator', true),
('vafreitas', 'VANESSA GOMES DE FREITAS', 'vafreitas@gruporoveri.com', 'operator', true),
('depesantos', 'DEBORA PEREIRA SANTOS', 'depesantos@gruporoveri.com', 'operator', true),
('rasolera', 'RAUL SABINO SOLERA', 'rasolera@gruporoveri.com', 'operator', true),
('gyribeiro', 'GYOVANNA PASCHOAL FULINI RIBEIRO', 'gyribeiro@gruporoveri.com', 'operator', true),
('gelinhares', 'GERUSIA MARTA FERNADES LINHARES', 'gelinhares@gruporoveri.com', 'operator', true),
('kesilveira', 'KELLY CRISTINA PINTO SILVEIRA', 'kesilveira@gruporoveri.com', 'operator', true),
('leaoliveira', 'LEANY MARIA CAETANO OLIVEIRA', 'leaoliveira@gruporoveri.com', 'operator', true),
('racneves', 'RAPHAEL CORREIA NEVES', 'racneves@gruporoveri.com', 'operator', true),
('lucferreira', 'LUCAS FERREIRA DA SILVA', 'lucferreira@gruporoveri.com', 'operator', true),
('luujlaki', 'LUCAS TAMASHIRO UJLAKI', 'luujlaki@gruporoveri.com', 'operator', true),
('rybazan', 'RYAN CAVINATO BAZAN', 'rybazan@gruporoveri.com', 'operator', true),
('mursouza', 'MURILO ESTEVAM DE SOUZA', 'mursouza@gruporoveri.com', 'operator', true),
('lubarros', 'LUCAS FERNANDES BARROS', 'lubarros@gruporoveri.com', 'operator', true),
('gigcabral', 'GIOVANNA GONCALVES CABRAL', 'gigcabral@gruporoveri.com', 'operator', true),
('vihsantos', 'VICTOR HUGO GONCALVES SANTOS', 'vihsantos@gruporoveri.com', 'operator', true),
('keleal', 'KEZIA LEAL', 'keleal@gruporoveri.com', 'operator', true),
('marlopes', 'MARIA EDUARDA GUIMARAES LOPES', 'marlopes@gruporoveri.com', 'operator', true),
('viaguiar', 'VITORIA CAMPOS AGUIAR', 'viaguiar@gruporoveri.com', 'operator', true),
('betalves', 'BENTO DE LIMA ALVES', 'betalves@gruporoveri.com', 'operator', true),
('yalbarbosa', 'YASMIN LIMA BARBOSA', 'yalbarbosa@gruporoveri.com', 'operator', true),
('yascordeiro', 'YASMIM GUIMARAES CORDEIRO DOS SANTOS', 'yascordeiro@gruporoveri.com', 'operator', true),
('ssasantos', 'SARA SILVA SANTOS', 'ssasantos@gruporoveri.com', 'operator', true),
('andrferreira', 'ANDREIA ALBERTO FURTADO FERREIRA', 'andrferreira@gruporoveri.com', 'operator', true),
('masbarbosa', 'MANOELLA SENA BARBOSA', 'masbarbosa@gruporoveri.com', 'operator', true),
('esthsilva', 'ESTHER SILVA', 'esthsilva@gruporoveri.com', 'operator', true),
('niboaventura', 'NIVEA KATIA DA SILVA BOAVENTURA', 'niboaventura@gruporoveri.com', 'operator', true),
('madulima', 'MARIA EDUARDA SOUZA DE LIMA', 'madulima@gruporoveri.com', 'operator', true),
('tatimoura', 'TATIANA SIQUEIRA DE MOURA', 'tatimoura@gruporoveri.com', 'operator', true),
('vimorais', 'VITOR FERREIRA MORAIS', 'vimorais@gruporoveri.com', 'operator', true),
('gifsilva', 'GIOVANA FERREIRA DA SILVA', 'gifsilva@gruporoveri.com', 'operator', true),
('faabdalla', 'FABIANA ABDALLA', 'faabdalla@gruporoveri.com', 'operator', true),
('threzende', 'THAIS REZENDE SILVA', 'threzende@gruporoveri.com', 'operator', true),
('ludpedrosa', 'LUCAS DA SILVA PEDROSA', 'ludpedrosa@gruporoveri.com', 'operator', true),
('feaguiar', 'FELIPE AGUIAR MENDES DO NASCIMENTO', 'feaguiar@gruporoveri.com', 'operator', true),
('ankatia', 'ANA KATIA DA SILVA', 'ankatia@gruporoveri.com', 'operator', true),
('catsilva', 'CATARINA ALVES SILVA', 'catsilva@gruporoveri.com', 'operator', true),
('pelavorato', 'PEDRO HENRIQUE LAVORATO', 'pelavorato@gruporoveri.com', 'operator', true),
('edalves', 'EDER NASCIMENTO ALVES', 'edalves@gruporoveri.com', 'operator', true),
('megomes', 'MELISSA BALBINO DA SILVA GOMES', 'megomes@gruporoveri.com', 'operator', true),
('lapereira', 'LARISSA NASARIO PEREIRA', 'lapereira@gruporoveri.com', 'operator', true),
('rebulgarelli', 'RENAN DA SILVA BULGARELLI', 'rebulgarelli@gruporoveri.com', 'operator', true),
('anolivia', 'ANA CAROLINE SOUZA OLIVIA', 'anolivia@gruporoveri.com', 'operator', true),
('phenrique', 'PEDRO HENRIQUE NASCIMENTO DA SILVA', 'phenrique@gruporoveri.com', 'operator', true),
('lipighin', 'LIVIA NOBREGA PIGHIN', 'lipighin@gruporoveri.com', 'operator', true),
('kamuniz', 'KARINA MUNIZ VIEIRA', 'kamuniz@gruporoveri.com', 'operator', true),
('vifacciolo', 'VITOR HUGO ALVARENGA FACCIOLO', 'vifacciolo@gruporoveri.com', 'operator', true),
('brestrela', 'BRENDA MORGAN ESTRELA DA SILVA', 'brestrela@gruporoveri.com', 'operator', true),
('gbsoliveira', 'GABRIELLY SANTOS OLIVEIRA', 'gbsoliveira@gruporoveri.com', 'operator', true),
('jaaraujo', 'JADE ALVES DE ARAUJO', 'jaaraujo@gruporoveri.com', 'operator', true),
('iscsouza', 'ISABELA CRISTINA DE SOUZA', 'iscsouza@gruporoveri.com', 'operator', true),
('amferreira', 'AMANDA CUER FERREIRA', 'amferreira@gruporoveri.com', 'operator', true),
('ankcruz', 'ANA KAROLINA PEREIRA CRUZ', 'ankcruz@gruporoveri.com', 'operator', true),
('lebispo', 'LETICIA SIQUEIRA BISPO', 'lebispo@gruporoveri.com', 'operator', true),
('kapereira', 'KAUE RAMOS PEREIRA', 'kapereira@gruporoveri.com', 'operator', true),
('dacosta', 'DANIELLE LIMA DA COSTA', 'dacosta@gruporoveri.com', 'operator', true),
('ngama', 'NADJA GAMA DOS SANTOS', 'ngama@gruporoveri.com', 'operator', true),
('maneres', 'MAYSA DOS SANTOS NERES', 'maneres@gruporoveri.com', 'operator', true),
('tansantos', 'TAMIRES NEVES DOS SANTOS', 'tansantos@gruporoveri.com', 'operator', true),
('maluara', 'MAXINE LUARA RODRIGUES BATISTA DA SILVA', 'maluara@gruporoveri.com', 'operator', true),
('fabasilio', 'FABIANA APARECIDA BASILIO', 'fabasilio@gruporoveri.com', 'operator', true),
('stassis', 'STEFANIE PAMPOLINI DE ASSIS', 'stassis@gruporoveri.com', 'operator', true),
('lubraz', 'LUANA DIAS BRAZ', 'lubraz@gruporoveri.com', 'operator', true),
('frreis', 'FRANCIELE QUERCIA DE OLIVEIRA DOS REIS', 'frreis@gruporoveri.com', 'operator', true),
('yasmachado', 'YASMIN MACHADO DA SILVA', 'yasmachado@gruporoveri.com', 'operator', true),
('danietto', 'DAVI JOSE NIETTO DE SOUZA', 'danietto@gruporoveri.com', 'operator', true),
('vilopes', 'VITOR MENDONCA LOPES', 'vilopes@gruporoveri.com', 'operator', true),
('carsnunes', 'CAROLINA NUNES DA SILVA', 'carsnunes@gruporoveri.com', 'operator', true),
('prazevedo', 'PRISCILA FONTES DE AZEVEDO', 'prazevedo@gruporoveri.com', 'operator', true),
('ermpereira', 'ERIKA MACIEL PEREIRA', 'ermpereira@gruporoveri.com', 'operator', true),
('mavcosta', 'MARCOS VINICIUS DE LIMA COSTA', 'mavcosta@gruporoveri.com', 'operator', true),
('thlourenco', 'THAIS SANTOS LOURENCO', 'thlourenco@gruporoveri.com', 'operator', true),
('dearaujo', 'DEISY KIMBERLLY SATILITE ARAUJO', 'dearaujo@gruporoveri.com', 'operator', true),
('brenogueira', 'BRENO ALVES NOGUEIRA', 'brenogueira@gruporoveri.com', 'operator', true),
('dawenceslau', 'DANIELLE DA SILVA WENCESLAU', 'dawenceslau@gruporoveri.com', 'operator', true),
('faguirra', 'FABIO EISHIMA DE CASTRO GUIRRA', 'faguirra@gruporoveri.com', 'operator', true),
('gegodoy', 'GEOVANA SILVA MATARUCO DE GODOY', 'gegodoy@gruporoveri.com', 'operator', true),
('hagomes', 'HAYANE DE MOURA GOMES', 'hagomes@gruporoveri.com', 'operator', true),
('daneto', 'DANIELA MOURA ANDRADE', 'daneto@gruporoveri.com', 'operator', true),
('cavinicius', 'CARLOS VINICIUS DIAS DA SILVA', 'cavinicius@gruporoveri.com', 'operator', true),
('geovjesus', 'GEOVANA DE JESUS SANTOS', 'geovjesus@gruporoveri.com', 'operator', true),
('giferraiuli', 'GIOVANNA FERRAIULI', 'giferraiuli@gruporoveri.com', 'operator', true),
('marsaraiva', 'MARIA EDUARDA SARAIVA BARBOSA', 'marsaraiva@gruporoveri.com', 'operator', true),
('marisoares', 'MARINA SOARES DA SILVA', 'marisoares@gruporoveri.com', 'operator', true),
('reterto', 'REBECA CIARELLI GUERRA TERTO', 'reterto@gruporoveri.com', 'operator', true),
('casvitoria', 'CAMILLY VITORIA SILVA', 'casvitoria@gruporoveri.com', 'operator', true),
('amsantos', 'AMANDA LUIZA DIAS SANTOS', 'amsantos@gruporoveri.com', 'operator', true),
('kaylsilva', 'KAYLLANE MYRELLE MOTA SILVA', 'kaylsilva@gruporoveri.com', 'operator', true),
('crpaiz', 'CRISTIANE PAIZ LYRA', 'crpaiz@gruporoveri.com', 'operator', true),
('gutsouza', 'GUSTAVO HENRIQUE NASCIMENTO DE SOUZA', 'gutsouza@gruporoveri.com', 'operator', true),
('gasandran', 'GABRIEL DA SILVA SANDRAN', 'gasandran@gruporoveri.com', 'operator', true),
('jucavalcante', 'JULIA CAVALCANTI DA COSTA', 'jucavalcante@gruporoveri.com', 'operator', true),
('velage', 'VERONICA CAVALCANTE LAGE', 'velage@gruporoveri.com', 'operator', true),
('pefreitas', 'PEDRO FERREIRA DE FREITAS', 'pefreitas@gruporoveri.com', 'operator', true),
('marilima', 'MARIANI SILVA DE LIMA', 'marilima@gruporoveri.com', 'operator', true),
('elesilva', 'ELETICIA SOUZA DA SILVA', 'elesilva@gruporoveri.com', 'operator', true),
('bifoliveira', 'BIANCA FARIAS DE OLIVEIRA', 'bifoliveira@gruporoveri.com', 'operator', true),
('niwitkowaki', 'NICOLAS WITKOWSKI', 'niwitkowaki@gruporoveri.com', 'operator', true),
('miamaral', 'MIRELLA DE ARAUJO AMARAL', 'miamaral@gruporoveri.com', 'operator', true),
('kanslima', 'KAUANY SILVA LIMA', 'kanslima@gruporoveri.com', 'operator', true),
('quezsantos', 'QUEZIA SILVA DOS SANTOS', 'quezsantos@gruporoveri.com', 'operator', true),
('jenisilva', 'JENIFER MARTINS DA SILVA', 'jenisilva@gruporoveri.com', 'operator', true),
('sicarvalho', 'SIMONE DE CARVALHO SILVA', 'sicarvalho@gruporoveri.com', 'operator', true),
('gineribeiro', 'GISELE NERI RIBEIRO', 'gineribeiro@gruporoveri.com', 'operator', true),
('thbezerra', 'THAINA LORRANNE NICOLAU BEZERRA', 'thbezerra@gruporoveri.com', 'operator', true),
('tapsantos', 'TAMARA PEREIRA SANTOS', 'tapsantos@gruporoveri.com', 'operator', true),
('anmasilva', 'ANDREY MATOS FERREIRA DA SILVA', 'anmasilva@gruporoveri.com', 'operator', true),
('cavisantos', 'CAROLINA VITORIA DE ARAUJO SANTOS', 'cavisantos@gruporoveri.com', 'operator', true),
('kaflima', 'KARIN FIRMO DE LIMA', 'kaflima@gruporoveri.com', 'operator', true),
('calima', 'CAMILA FIRMO DE LIMA', 'calima@gruporoveri.com', 'operator', true),
('helisilva', 'HENRIQUE LINO DA SILVA', 'helisilva@gruporoveri.com', 'operator', true),
('inanisilva', 'INGRID ANISIO DA SILVA', 'inanisilva@gruporoveri.com', 'operator', true),
('anparodrigues', 'ANA PAULA RODRIGUES', 'anparodrigues@gruporoveri.com', 'operator', true),
('desales', 'DERICK RIBEIRO DE SALES', 'desales@gruporoveri.com', 'operator', true),
('kasantana', 'KATHELLYN IASMIM ROSA SANTANA', 'kasantana@gruporoveri.com', 'operator', true),
('lamoller', 'LAURA AMURIM ESTAPINA MOLLER', 'lamoller@gruporoveri.com', 'operator', true),
('flsantos', 'FLAVIA BERNARDES STOLFO DOS SANTOS', 'flsantos@gruporoveri.com', 'operator', true),
('vapereira', 'VANESSA PINTO', 'vapereira@gruporoveri.com', 'operator', true),
('stgsoares', 'STEPHANIE GOMES SOARES', 'stgsoares@gruporoveri.com', 'operator', true),
('groliveira', 'GRAZIELLI CRISTINA PEREIRA DE OLIVEIRA', 'groliveira@gruporoveri.com', 'operator', true),
('jaraimundo', 'JACKSON CINTRA RAIMUNDO', 'jaraimundo@gruporoveri.com', 'operator', true),
('lubarsantos', 'LUCIANA BARBOSA DA SILVA SANTOS', 'lubarsantos@gruporoveri.com', 'operator', true),
('fajesus', 'FATIMA CRISTINA SILVA DE JESUS', 'fajesus@gruporoveri.com', 'operator', true),
('nosousa', 'NOEMY BESERRA DA SILVA DE SOUSA', 'nosousa@gruporoveri.com', 'operator', true),
('edtoledo', 'EDUARDA SILVA DE TOLEDO PINTO', 'edtoledo@gruporoveri.com', 'operator', true),
('jclsilva', 'JOSE CARLOS DA SILVA', 'jclsilva@gruporoveri.com', 'operator', true),
('mrlfreitas', 'MARIA LUIZA FREITAS DOS SANTOS', 'mrlfreitas@gruporoveri.com', 'operator', true),
('detelles', 'DEBORA DA SILVA TELLES', 'detelles@gruporoveri.com', 'operator', true),
('vipompeu', 'VINICIUS DOS SANTOS PEREIRA POMPEU', 'vipompeu@gruporoveri.com', 'operator', true),
('jozarbinati', 'JOAQUIM RODRIGUES ZARBINATI', 'jozarbinati@gruporoveri.com', 'operator', true),
('vgrodrigues', 'VITOR GABRIEL BRANDAO RODRIGUES', 'vgrodrigues@gruporoveri.com', 'operator', true),
('jocaetano', 'JOICE VITAL CAETANO', 'jocaetano@gruporoveri.com', 'operator', true),
('evspereira', 'EVELLYN SILVA PEREIRA', 'evspereira@gruporoveri.com', 'operator', true),
('glaraujo', 'GIOVANNA LAMBIASI DE ARAUJO', 'glaraujo@gruporoveri.com', 'operator', true),
('levieira', 'LETICIA ANTUNES VIEIRA', 'levieira@gruporoveri.com', 'operator', true),
('sineves', 'SILMEIA SANTANA NEVES', 'sineves@gruporoveri.com', 'operator', true),
('simota', 'SIRLEI APARECIDA MOTA', 'simota@gruporoveri.com', 'operator', true),
('amsouza', 'AMANDA FERNANDES DA SILVA SOUZA', 'amsouza@gruporoveri.com', 'operator', true),
('maathayde', 'MARIA DE FATIMA FLORENCIO DE ATHAYDE', 'maathayde@gruporoveri.com', 'operator', true),
('stexavier', 'STEPHANIE XAVIER DE OLIVEIRA', 'stexavier@gruporoveri.com', 'operator', true),
('tabustos', 'TABATA SAMANTHA AGUIAR BUSTOS', 'tabustos@gruporoveri.com', 'operator', true),
('trebeca', 'TALITA REBECA ALBUQUERQUE DE LIMA', 'trebeca@gruporoveri.com', 'operator', true),
('vitsilva', 'VITOR DA SILVA OLIVEIRA', 'vitsilva@gruporoveri.com', 'operator', true),
('rehorvath', 'RENATA HORVATH', 'rehorvath@gruporoveri.com', 'operator', true),
('rilucindo', 'RICHARD MENDES LUCINDO', 'rilucindo@gruporoveri.com', 'operator', true),
('larcsilva', 'LARISSA OLIVEIRA CARVALHO', 'larcsilva@gruporoveri.com', 'operator', true),
('lelucindo', 'LETICIA RANY MENDES LUCINDO', 'lelucindo@gruporoveri.com', 'operator', true),
('luabreu', 'LUCAS DELLA BIANCA ABREU', 'luabreu@gruporoveri.com', 'operator', true),
('msusyane', 'MARIA SUSYANE DO NASCIMENTO', 'msusyane@gruporoveri.com', 'operator', true),
('gmodesto', 'GUILHERME MODESTO LOPES DA SILVA', 'gmodesto@gruporoveri.com', 'operator', true),
('mbrito', 'MARIA EDUARDA DE BRITO SILVA', 'mbrito@gruporoveri.com', 'operator', true),
('bontiveros', 'BRUNA ONTIVEROS JESUS', 'bontiveros@gruporoveri.com', 'operator', true),
('clunguinho', 'CARLOS EDUARDO LUNGUINHO DE OLIVEIRA', 'clunguinho@gruporoveri.com', 'operator', true),
('errfato', 'ERIC CATINO RFATO', 'errfato@gruporoveri.com', 'operator', true),
('aradeo', 'ARTUR ALVES ADEO', 'aradeo@gruporoveri.com', 'operator', true),
('besanciulis', 'BEATRIZ CAMILLO SANCIULIS', 'besanciulis@gruporoveri.com', 'operator', true),
('bpenacchio', 'BEATTRIZ PENACCHIO RIBEIRO SILVA', 'bpenacchio@gruporoveri.com', 'operator', true),
('gapossebom', 'GABRIELLA POSSEBOM LOPES', 'gapossebom@gruporoveri.com', 'operator', true),
('lusolda', 'LUIS FERNANDO OSUNA SOLDA', 'lusolda@gruporoveri.com', 'operator', true),
('gabrteixeira', 'GABRIELA TEIXEIRA DO NASCIMENTO', 'gabrteixeira@gruporoveri.com', 'operator', true),
('anevangelista', 'ANA LARISSA EVANGELISTA DA SILVA', 'anevangelista@gruporoveri.com', 'operator', true),
('denisilva', 'DENISE DA SILVA', 'denisilva@gruporoveri.com', 'operator', true),
('majovino', 'MARCOS VINICIUS JOVINO DOS SANTOS', 'majovino@gruporoveri.com', 'operator', true),
('rupablo', 'RUAN PABLO DA SILVA', 'rupablo@gruporoveri.com', 'operator', true),
('sopereira', 'SOPHIA ANDRADE PEREIRA', 'sopereira@gruporoveri.com', 'operator', true),
('anbarreto', 'ANDRE DA ROCHA BARRETO', 'anbarreto@gruporoveri.com', 'operator', true),
('beyusmy', 'BEATRIZ DORINE YUSMY DA SILVA', 'beyusmy@gruporoveri.com', 'operator', true),
('casimoes', 'CARINA SIMOES', 'casimoes@gruporoveri.com', 'operator', true),
('isaferreira', 'ISADORA DE OLIVEIRA FERREIRA', 'isaferreira@gruporoveri.com', 'operator', true),
('thferreira', 'THAINA GUIMARAES FERREIRA', 'thferreira@gruporoveri.com', 'operator', true),
('kaabreu', 'KAUAN DURAES DE ABREU', 'kaabreu@gruporoveri.com', 'operator', true),
('gealmeida', 'GEOVANNA APARECIDA ALMEIDA DA SILVA', 'gealmeida@gruporoveri.com', 'operator', true),
('alamorim', 'ALINE TEIXEIRA DE AMORIM', 'alamorim@gruporoveri.com', 'operator', true),
('inlima', 'INGRID LARA CESAR LIMA', 'inlima@gruporoveri.com', 'operator', true),
('risantos', 'RITA DE CASSIA DOS SANTOS', 'risantos@gruporoveri.com', 'operator', true),
('sagarcia', 'SARA SARTORIO ALVES GARCIA', 'sagarcia@gruporoveri.com', 'operator', true),
('lojuvino', 'LOHANY DO NASCIMENTO LEOCADIO JUVINO', 'lojuvino@gruporoveri.com', 'operator', true),
('lachinconi', 'LORENA FACHINCONI DA SILVA', 'lachinconi@gruporoveri.com', 'operator', true),
('ginavaro', 'GIULIANA CAVLAK NAVARRO', 'ginavaro@gruporoveri.com', 'operator', true),
('kamelo', 'KATHLLEN LIMA DE MELO', 'kamelo@gruporoveri.com', 'operator', true),
('biflaminio', 'BIANCA ARRIATE DA SILA FLAMINIO', 'biflaminio@gruporoveri.com', 'operator', true),
('jhfernandes', 'JHENNYFER PEGO FERNANDES', 'jhfernandes@gruporoveri.com', 'operator', true),
('luneves', 'LUCIANA RAPOZO NEVES', 'luneves@gruporoveri.com', 'operator', true),
('mocorreia', 'MONIQUE CORREIA', 'mocorreia@gruporoveri.com', 'operator', true),
('pesanches', 'PEDRO LUIGI PALMA SANCHES', 'pesanches@gruporoveri.com', 'operator', true),
('rireis', 'RICHARD VITOR SILVA DOS REIS', 'rireis@gruporoveri.com', 'operator', true),
('kepaiva', 'KEYANE VELOSO PAIVA', 'kepaiva@gruporoveri.com', 'operator', true),
('sioliveira', 'SILVIA REGINA DE OLIVEIRA', 'sioliveira@gruporoveri.com', 'operator', true),
('yaosman', 'YASMIN YOUSSEF ABOU OSMAN', 'yaosman@gruporoveri.com', 'operator', true),
('matartari', 'MARISA FRANCIS GUILHERME TARTARI', 'matartari@gruporoveri.com', 'operator', true),
('maximenes', 'MATHEUS DE MARTIN XIMENES', 'maximenes@gruporoveri.com', 'operator', true),
('pehesilva', 'PEDRO HENRYQUE SILVA', 'pehesilva@gruporoveri.com', 'operator', true),
('prleite', 'PRISCILA NUNES LEITE', 'prleite@gruporoveri.com', 'operator', true),
('prprates', 'PRISCILA PRATES', 'prprates@gruporoveri.com', 'operator', true),
('ketlima', 'KETILY CRISTINI DA SILVA LIMA', 'ketlima@gruporoveri.com', 'operator', true),
('laorlando', 'LARISSA GONCALVES ORLANDO', 'laorlando@gruporoveri.com', 'operator', true),
('lumelo', 'LUCAS DE SOUSA MELO', 'lumelo@gruporoveri.com', 'operator', true),
('lueilima', 'LUCAS EIRISDAN OLIVEIRA LIMA', 'lueilima@gruporoveri.com', 'operator', true),
('jogalindo', 'JOAO PEDRO MARVALHO GALINDO', 'jogalindo@gruporoveri.com', 'operator', true),
('androcha', 'ANDRESSA ROCHA ARAUJO', 'androcha@gruporoveri.com', 'operator', true),
('arcasal', 'ARTUR LUCIANO CASAL', 'arcasal@gruporoveri.com', 'operator', true),
('vimatano', 'VITOR FRANCIA MATANO', 'vimatano@gruporoveri.com', 'operator', true),
('anoliveir', 'ANA VITORIA DOS SANTOS OLIVEIR', 'anoliveir@gruporoveri.com', 'operator', true),
('evmartinez', 'EVELLYN SOARES MARTINEZ', 'evmartinez@gruporoveri.com', 'operator', true),
('prpereira', 'PRISCILA PEREIRA', 'prpereira@gruporoveri.com', 'operator', true),
('anpawluk', 'ANNA CLARA PAWLUK', 'anpawluk@gruporoveri.com', 'operator', true),
('gapostigo', 'GABRIEL POSTIGO', 'gapostigo@gruporoveri.com', 'operator', true),
('glsa', 'GLEICE QUELLI CONCEICAO DOS SA', 'glsa@gruporoveri.com', 'operator', true),
('embrito', 'EMMANUELLE ALEIXO BRITO', 'embrito@gruporoveri.com', 'operator', true),
('ferabetti', 'FELIPE ZULEGER RABETTI', 'ferabetti@gruporoveri.com', 'operator', true),
('hefrsantos', 'HELOISA FREITAS DOS SANTOS', 'hefrsantos@gruporoveri.com', 'operator', true),
('lirezende', 'LILIAN CRISTINA REZENDE', 'lirezende@gruporoveri.com', 'operator', true),
('rarosilva', 'RAUL ANTONIO ROQUE E SILVA', 'rarosilva@gruporoveri.com', 'operator', true),
('rymsilva', 'RYAN MATA DA SILVA', 'rymsilva@gruporoveri.com', 'operator', true),
('suaraujo', 'SUZANA SANTOS ARAUJO', 'suaraujo@gruporoveri.com', 'operator', true),
('tasoliveira', 'TAINA SANTOS DE OLIVEIRA', 'tasoliveira@gruporoveri.com', 'operator', true),
('taje', 'TALITA FERNANDA DA SILVA DE JE', 'taje@gruporoveri.com', 'operator', true),
('thpecosta', 'THAYNA PEREIRA COSTA', 'thpecosta@gruporoveri.com', 'operator', true),
('valicosta', 'VANESSA LIMA DA COSTA', 'valicosta@gruporoveri.com', 'operator', true),
('jovarjao', 'JOSE EMERSON VARJAO', 'jovarjao@gruporoveri.com', 'operator', true),
('brlorodrigues', 'BRUNO LORENZO RODRIGUES', 'brlorodrigues@gruporoveri.com', 'operator', true),
('dasous', 'DAVID RANGEL GONCALVES DE SOUS', 'dasous@gruporoveri.com', 'operator', true),
('camigoncalves', 'CAMILA MICAELE GONCALVES', 'camigoncalves@gruporoveri.com', 'operator', true),
('adroliveira', 'ADRISIA SANTOS DE OLIVEIRA', 'adroliveira@gruporoveri.com', 'operator', true),
('jemartins', 'JESSICA DA CONCEICAO MARTINS', 'jemartins@gruporoveri.com', 'operator', true),
('lamysouza', 'LARISSA MYUKI OLIVEIRA SOUZA', 'lamysouza@gruporoveri.com', 'operator', true),
('luhofer', 'LUCAS ARAUJO HOFER', 'luhofer@gruporoveri.com', 'operator', true),
('mapi', 'MARIA CRISTINA GRECCO MOURA PI', 'mapi@gruporoveri.com', 'operator', true),
('maandreotti', 'MATHEUS APARECIDO ANDREOTTI', 'maandreotti@gruporoveri.com', 'operator', true),
('rbnogueira', 'REBECA NOGUEIRA DA SILVA', 'rbnogueira@gruporoveri.com', 'operator', true),
('rerocha', 'RENATA SILVA ROCHA', 'rerocha@gruporoveri.com', 'operator', true),
('rybernardino', 'RYAN DE SOUSA BERNARDINO', 'rybernardino@gruporoveri.com', 'operator', true),
('vivcosta', 'VIVIANE SILVA COSTA', 'vivcosta@gruporoveri.com', 'operator', true),
('yalopes', 'YASMIN MATTAR DOS SANTOS LOPES', 'yalopes@gruporoveri.com', 'operator', true),
('ispsilva', 'ISABELA PEREIRA DA SILVA', 'ispsilva@gruporoveri.com', 'operator', true),
('jadsantos', 'JADSON CONCEICAO SANTOS', 'jadsantos@gruporoveri.com', 'operator', true),
('jovoliveira', 'JOAO VICTOR FONOLOSA DE OLIVEIRA', 'jovoliveira@gruporoveri.com', 'operator', true),
('juyetika', 'JULIA SILVESTRE YETIKA', 'juyetika@gruporoveri.com', 'operator', true),
('kcrsoares', 'KAREN CRISTINA SOARES', 'kcrsoares@gruporoveri.com', 'operator', true),
('kmgoncalves', 'KEMELLY GONCALVES DA SILVA', 'kmgoncalves@gruporoveri.com', 'operator', true),
('lualmeida', 'LUANA JANUARIO SANTOS DE ALMEIDA', 'lualmeida@gruporoveri.com', 'operator', true),
('dahidalgo', 'DAVI HIDALGO DA SILVA', 'dahidalgo@gruporoveri.com', 'operator', true),
('gsbrito', 'GABRIELLA SCAVONE BRITO', 'gsbrito@gruporoveri.com', 'operator', true),
('bnsantos', 'BRUNA APARECIDA SILVA SANTOS', 'bnsantos@gruporoveri.com', 'operator', true),
('bmsouza', 'BRUNA MOURA PINTO DE SOUZA', 'bmsouza@gruporoveri.com', 'operator', true),
('grpereira', 'GIOVANNA RIBEIRO FOGATO PEREIRA', 'grpereira@gruporoveri.com', 'operator', true),
('jafarias', 'JAQUELINE DELLVALD FARIAS', 'jafarias@gruporoveri.com', 'operator', true),
('arcaires', 'ARTHUR LISBOA CAIRES', 'arcaires@gruporoveri.com', 'operator', true),
('dajunior', 'DANIEL TELES JUNIOR', 'dajunior@gruporoveri.com', 'operator', true),
('lafraga', 'LARISSA DA SILVA FRAGA', 'lafraga@gruporoveri.com', 'operator', true),
('nanovaes', 'NATHALIA REGINA SILVA NOVAES', 'nanovaes@gruporoveri.com', 'operator', true),
('nialbuquerque', 'NICOLE CAVALCANTE DE ALBUQUERQUE', 'nialbuquerque@gruporoveri.com', 'operator', true),
('vtrbatista', 'VITORIA SILVA BATISTA', 'vtrbatista@gruporoveri.com', 'operator', true)
ON CONFLICT (username) DO NOTHING;

-- ==============================================
-- FIM DO SCRIPT
-- Total de operadores: 420
-- ==============================================
