-- ==============================================
-- INSERIR OPERADORES (Grupo Roveri)
-- Execute no SQL Editor do Supabase
-- ==============================================
-- Este script insere operadores na tabela users
-- Usa ON CONFLICT para ignorar duplicatas
-- ==============================================

INSERT INTO users (name, email, role, is_active) VALUES
('SABRINA NUNES DE MEDEIROS', 'sabmedeiros@gruporoveri.com', 'operator', true),
('FABIOLLA BUGADA', 'fbugada@gruporoveri.com', 'operator', true),
('NICHOLAS BERNARDO GRACIANO', 'nbgraciano@gruporoveri.com', 'operator', true),
('ROBERT LEITE SANTOS', 'rolsantos@gruporoveri.com', 'operator', true),
('THAYNARA DOS SANTOS SILVA', 'thaysilva@gruporoveri.com', 'operator', true),
('NOEMI REZENDE ESTEVAM', 'norezende@gruporoveri.com', 'operator', true),
('KAROLAINE OLIVEIRA SANTOS', 'kosantos@gruporoveri.com', 'operator', true),
('ANA PAULA GONCALVES LIMA', 'apglima@gruporoveri.com', 'operator', true),
('ARTHUR DE SOUSA LEAL', 'asleal@gruporoveri.com', 'operator', true),
('PEDRO HENRIQUE COELHO PEREIRA', 'phcoelho@gruporoveri.com', 'operator', true),
('PAULA NATALIA SILVA SANTOS', 'pansantos@gruporoveri.com', 'operator', true),
('CAIO HENRIQUE ARAUJO DE ALENCAR', 'chalencar@gruporoveri.com', 'operator', true),
('THAIS ANDRADE SANTOS', 'thandrade@gruporoveri.com', 'operator', true),
('FERNANDA BATISTA DA ROCHA', 'fbatista@gruporoveri.com', 'operator', true),
('ANA FLAVIA GONCALVES DE AZEVEDO', 'afgavezedo@gruporoveri.com', 'operator', true),
('NATHALY DA SILVA PELEGRINI', 'npelegrini@gruporoveri.com', 'operator', true),
('DANIELE DA SILVA', 'dandsilva@gruporoveri.com', 'operator', true),
('REGINE DE SOUSA SILVA', 'rdsousa@gruporoveri.com', 'operator', true),
('MARINA PALETTI', 'mpapaletti@gruporoveri.com', 'operator', true),
('REBECA GABRIELI SOUZA AUGUSTO', 'regaugusto@gruporoveri.com', 'operator', true),
('JULIANE ALVES EVANGELISTA DOS SANTOS', 'juevangelista@gruporoveri.com', 'operator', true),
('GABRIEL SOARES DA SILVA PEREIRA', 'gaspereira@gruporoveri.com', 'operator', true),
('GABRIEL VINICIUS DOS SANTOS', 'gabvsantos@gruporoveri.com', 'operator', true),
('ALAN DANTAS SANTOS', 'adantas@gruporoveri.com', 'operator', true),
('MARIA APARECIDA RODRIGUES FARIAS', 'maarodrogues@gruporoveri.com', 'operator', true),
('BRUNO NOVAIS DA SILVA', 'brnsilva@gruporoveri.com', 'operator', true),
('KARINA GONCIARENCO BELLA', 'kabella@gruporoveri.com', 'operator', true),
('GIOVANNA VALERIA RODRIGUES', 'givrodrigues@gruporoveri.com', 'operator', true),
('BIANCA SOUSA NUNES', 'binunes@gruporoveri.com', 'operator', true),
('LUANA DIAS DE SOUSA', 'luasousa@gruporoveri.com', 'operator', true),
('LAIS MARQUES BRAVO', 'lbravo@gruporoveri.com', 'operator', true),
('GABRIEL GOMES QUEIROZ', 'ggqueiroz@gruporoveri.com', 'operator', true),
('AGATA BITTENCOURT BASAGLIA CUNHA', 'abasaglia@gruporoveri.com', 'operator', true),
('JOAO DE LIMA MELO SOBRINHO', 'jlsobrinho@gruporoveri.com', 'operator', true),
('JULIA ALEXANDRA SOUZA NASCIMENTO', 'janascimento@gruporoveri.com', 'operator', true),
('EDUARDO SANTOS DO NASCIMENTO', 'edunascimento@gruporoveri.com', 'operator', true),
('AMANDA SANTOS PORTO', 'amaporto@gruporoveri.com', 'operator', true),
('VITORIA EMANUELE GOMES DE SOUSA', 'visousa@gruporoveri.com', 'operator', true),
('TAINARA AMBROZIO MARTINS', 'taamartins@gruporoveri.com', 'operator', true),
('MAYSA CARLA ALEIXO', 'maaleixo@gruporoveri.com', 'operator', true),
('GABRIEL MASCIARELLI FERREIRA MERGULHAO', 'gamergulhao@gruporoveri.com', 'operator', true),
('ELDA REGIANE BALERO VIEIRA', 'elvieira@gruporoveri.com', 'operator', true),
('RENATA CORDEIRO', 'recordeiro@gruporoveri.com', 'operator', true),
('NATALIA SILVA MIRANDA', 'namiranda@gruporoveri.com', 'operator', true),
('AUGUSTO FELIPE TAVARES DE CARVALHO', 'aucarvalho@gruporoveri.com', 'operator', true),
('GABRIEL MOTTA HIDALGO', 'gahidalgo@gruporoveri.com', 'operator', true),
('MARIA CLAUDIA FERREIRA DO NASCIMENTO', 'mcferreirta@gruporoveri.com', 'operator', true),
('VERONICA APARECIDA DE SOUZA', 'vsouza@gruporoveri.com', 'operator', true),
('FRANCILENE MACIEL SOUSA', 'frsousa@gruporoveri.com', 'operator', true),
('INGRID DANIELA BENTO DA SILVA', 'idaniela@gruporoveri.com', 'operator', true),
('RAFAELA PEREIRA GONCALVES', 'ragoncalves@gruporoveri.com', 'operator', true),
('SARA DE BARROS MAGALHAES', 'samagalhaes@gruporoveri.com', 'operator', true),
('IGOR CHINELATO PEREIRA', 'igpereira@gruporoveri.com', 'operator', true),
('JULIA MARINHO LEITE', 'juleite@gruporoveri.com', 'operator', true),
('ARTHUR CONDE RODRIGUES', 'arrodrigues@gruporoveri.com', 'operator', true),
('GABRIELLA TONON FOLGOSI', 'gafolgosi@gruporoveri.com', 'operator', true),
('KATIA SANTOS ALVES', 'kalves@gruporoveri.com', 'operator', true),
('CRISTIANE NUNES DE OLIVEIRA', 'cnunes@gruporoveri.com', 'operator', true),
('NATASHA SILVA VERA', 'navera@gruporoveri.com', 'operator', true),
('JAMILLY LIMA DA COSTA', 'jalicosta@gruporoveri.com', 'operator', true),
('THIELLY DE ARAUJO LIMA', 'thiaraujo@gruporoveri.com', 'operator', true),
('BERNARDO DE PAIVA FREITAS', 'befreitas@gruporoveri.com', 'operator', true),
('THALIA APARECIDA DA SILVA', 'thadsilva@gruporoveri.com', 'operator', true),
('JOAO VICTOR OLIVEIRA DIAS', 'jovdias@gruporoveri.com', 'operator', true),
('GABRIELLA RODRIGUES OLIVEIRA', 'garoliveira@gruporoveri.com', 'operator', true),
('MICHELE KAYTHLYN FERREIRA RAMOS', 'miramos@gruporoveri.com', 'operator', true),
('GABRIEL SILVA DE OLIVEIRA', 'gasoliveira@gruporoveri.com', 'operator', true),
('SEVERINA RIBEIRO DOS SANTOS', 'sesantos@gruporoveri.com', 'operator', true),
('NAYARA PEREIRA DOS SANTOS', 'naypereira@gruporoveri.com', 'operator', true),
('CRISLANE FERREIRA SILVA', 'criferreira@gruporoveri.com', 'operator', true),
('GEOVANA JERONIMO DE SOUSA', 'gejeronimo@gruporoveri.com', 'operator', true),
('ANA CAROLINE SILVA LUZ DE OLIVEIRA', 'anluz@gruporoveri.com', 'operator', true),
('OTAVIO VAILANT VITOR', 'otvitor@gruporoveri.com', 'operator', true),
('NATASHA ASSIS DOS SANTOS', 'nassis@gruporoveri.com', 'operator', true),
('ALESSANDRA SANTOS DE MELO', 'alemelo@gruporoveri.com', 'operator', true),
('BIANCA GOMES DOS SANTOS', 'bisantos@gruporoveri.com', 'operator', true),
('NICOLY AMARAL DE FREITAS', 'nifreitas@gruporoveri.com', 'operator', true),
('ITALO CARDOSO DA ROCHA ALENCAR', 'italencar@gruporoveri.com', 'operator', true),
('ANA BEATRIZ DA SILVA', 'ansbeatriz@gruporoveri.com', 'operator', true),
('ANE JAMILE CARDOSO PEREIRA', 'ancardoso@gruporoveri.com', 'operator', true),
('FRANCISCA NAZARIO DA COSTA', 'frcosta@gruporoveri.com', 'operator', true),
('MATHEUS MANDRO BUSARANHO', 'mabusaranho@gruporoveri.com', 'operator', true),
('TIAGO IORI YONEMURA', 'tiyonemura@gruporoveri.com', 'operator', true),
('NATHYELLE PEREIRA SANTANA', 'natsantana@gruporoveri.com', 'operator', true),
('GIOVANNA PAREJA ANZOLIN', 'gianzolin@gruporoveri.com', 'operator', true),
('KELLY BARBOSA OLIVEIRA PAULINO', 'kepaulino@gruporoveri.com', 'operator', true),
('BRUNA BONAVOLHA BASSI', 'brbassi@gruporoveri.com', 'operator', true),
('JOYCE DINIZ SOUZA', 'jodiniz@gruporoveri.com', 'operator', true),
('HAYALA VITORIA SILVA PEREIRA', 'hapereira@gruporoveri.com', 'operator', true),
('NATAN BONFANTI COSTA', 'nabonfanti@gruporoveri.com', 'operator', true),
('ERICK ROCHA DA SILVA', 'erirocha@gruporoveri.com', 'operator', true),
('LETICIA VITORIA RODRIGUES BOLLINI ROCHA', 'lerocha@gruporoveri.com', 'operator', true),
('GEOVANA SOUZA DA SILVA', 'geosouza@gruporoveri.com', 'operator', true),
('MARIA PAMELA SILVA DE CRISTO', 'macristo@gruporoveri.com', 'operator', true),
('ROBERT RODRIGUES MARTINS', 'romartins@gruporoveri.com', 'operator', true),
('PRISCILA CANDIDA DE OLIVEIRA SANTOS', 'prissantos@gruporoveri.com', 'operator', true),
('GUSTAVO FERREIRA SILVA', 'gufsilva@gruporoveri.com', 'operator', true),
('EMILLY MUNIZ TEIXEIRA', 'emteixeira@gruporoveri.com', 'operator', true),
('KAROLAYNE CRISTINA BRESSI DA SILVA', 'kabressi@gruporoveri.com', 'operator', true),
('SANDRA LEOPOLDINO LEIRAS', 'saleiras@gruporoveri.com', 'operator', true),
('GIOVANNA DA SILVA VARJAO', 'givarjao@gruporoveri.com', 'operator', true),
('LAURA FERREIRA FAENSE', 'lafaense@gruporoveri.com', 'operator', true),
('ALEXANDRINA FIGUEIREDO DE AQUINO', 'alaquina@gruporoveri.com', 'operator', true),
('ROGERIO SILVA RODRIGUES', 'rogesilva@gruporoveri.com', 'operator', true),
('MILENA MACENA OLIVEIRA', 'mimacena@gruporoveri.com', 'operator', true),
('OLIVIA ESTEVES MENESES', 'olmeneses@gruporoveri.com', 'operator', true),
('HENRIQUE SEVERINO DA SILVA', 'heseverino@gruporoveri.com', 'operator', true),
('MICHELLY DA SILVA SANTOS', 'michessantos@gruporoveri.com', 'operator', true),
('PALOMA MARQUES APOLIANO VAZ', 'pavaz@gruporoveri.com', 'operator', true),
('ANA LUIZA DE OLIVEIRA GONCALVES', 'anluiza@gruporoveri.com', 'operator', true),
('SAMUEL RODRIGUES DO AMARAL', 'samuamaral@gruporoveri.com', 'operator', true),
('YARA RIBEIRO DE OLIVEIRA', 'yaribeiro@gruporoveri.com', 'operator', true),
('GEOVANNA LEANDRO FERREIRA', 'geferreira@gruporoveri.com', 'operator', true),
('MURILO CAMPOLI DA SILVA', 'mucampoli@gruporoveri.com', 'operator', true),
('PAOLA CANDIDA BEZERRA', 'pcbezerra@gruporoveri.com', 'operator', true),
('LUANA SILVA LELIS', 'lulelis@gruporoveri.com', 'operator', true),
('CLEIDE ROSA DOS SANTOS', 'clesantos@gruporoveri.com', 'operator', true),
('ELIANA FERNANDES DE LIMA', 'elflima@gruporoveri.com', 'operator', true),
('LUIZ HENRIQUE DIAS BERNARDES', 'lubernardes@gruporoveri.com', 'operator', true),
('BRUNO DOS SANTOS RIBEIRO BORGES', 'bruborges@gruporoveri.com', 'operator', true),
('FABIANA MURARI GONCALVES', 'fabigoncalves@gruporoveri.com', 'operator', true),
('JOSY TALITA GONCALVES DE SOUSA', 'josysousa@gruporoveri.com', 'operator', true),
('ANGELO MAXIMO SILVA VIEIRA', 'angvieira@gruporoveri.com', 'operator', true),
('MARIA GENILDA DE ARAUJO LIMA', 'magelima@gruporoveri.com', 'operator', true),
('ADRIANO PALMEIRA LOPES', 'adlopes@gruporoveri.com', 'operator', true),
('LARISSA ARIADNE COUTINHO CARVALHO ALVES', 'larialves@gruporoveri.com', 'operator', true),
('JEFFERSON DE SOUSA LEITE', 'jeleite@gruporoveri.com', 'operator', true),
('RENATA GOMES DOS ANJOS', 'reanjos@gruporoveri.com', 'operator', true),
('NATELLY SALGADO DE OLIVEIRA', 'nateoliveira@gruporoveri.com', 'operator', true),
('YASMIM LAIS SANTOS REIS MARQUES', 'yamarques@gruporoveri.com', 'operator', true),
('JHONATAN MONTEIRO DA SILVA', 'jhonsilva@gruporoveri.com', 'operator', true),
('JULIANA CERQUEIRA', 'jucerqueira@gruporoveri.com', 'operator', true),
('YASMIM DA SILVA MELO', 'yamelo@gruporoveri.com', 'operator', true),
('MARIANE VITORIA GALDINO', 'magaldino@gruporoveri.com', 'operator', true),
('VERA MOURA DA SILVA', 'vemoura@gruporoveri.com', 'operator', true),
('KAROLINA DE OLIVEIRA SANTOS', 'karosantos@gruporoveri.com', 'operator', true),
('ISABELLY LIMA BARRETO', 'isbarreto@gruporoveri.com', 'operator', true),
('TAINA APARECIDA SALES DA SILVA', 'taasilva@gruporoveri.com', 'operator', true),
('RAISLENY DE CARVALHO', 'raycarvalho@gruporoveri.com', 'operator', true),
('NILVA MARIA RABISQUIM', 'nirabisquim@gruporoveri.com', 'operator', true),
('MATHEUS ALVES ELLERN SCUCUGLIA', 'mascucuglia@gruporoveri.com', 'operator', true),
('MARIA TEREZA FRETEGOTTO', 'mafretegotto@gruporoveri.com', 'operator', true),
('STHEU SCANCANI GALORO', 'stgaloro@gruporoveri.com', 'operator', true),
('ELAINE BISPO SOARES LIMA', 'elblima@gruporoveri.com', 'operator', true),
('JOSE CARLOS COSTA', 'joccosta@gruporoveri.com', 'operator', true),
('GABRIELLA NASCIMENTO NEGRI', 'ganegri@gruporoveri.com', 'operator', true),
('VINICIUS DE ALMEIDA ROMAGNOLO', 'viromagnolo@gruporoveri.com', 'operator', true),
('GIULIA RIBEIRO TAVARES FARIAS MAGNO', 'gumagno@gruporoveri.com', 'operator', true),
('KAREN CARVALHO DE SA', 'kasa@gruporoveri.com', 'operator', true),
('RANIELLY SILVA LEITE FRANCISCO', 'rinfrancisco@gruporoveri.com', 'operator', true),
('ARTHUR AVELINO CAMARGO', 'arcamargo@gruporoveri.com', 'operator', true),
('MAYARA THAYNA DE JESUS ALVES DA SILVA', 'majustino@gruporoveri.com', 'operator', true),
('VINICIUS DOS REIS PASSOS', 'vrpassos@gruporoveri.com', 'operator', true),
('MARISA DEMARCHI NOGUEIRA', 'marnogueira@gruporoveri.com', 'operator', true),
('EMILLY GONCALVES DE LIMA', 'emlima@gruporoveri.com', 'operator', true),
('JENNIFER CAMILA DOS SANTOS', 'jencsantos@gruporoveri.com', 'operator', true),
('JOYCE CRUZ DOS SANTOS', 'jocruz@gruporoveri.com', 'operator', true),
('LEANNE SLENY FERREIRA FREITAS', 'leaferreira@gruporoveri.com', 'operator', true),
('LUIZA ROSA BISPO SOUSA', 'lubispo@gruporoveri.com', 'operator', true),
('GABRIELLA SILVESTRE ANNUNCIATO', 'gaannunciato@gruporoveri.com', 'operator', true),
('GIOVANNA SILVESTRE ANNUNCIATO', 'giannunciato@gruporoveri.com', 'operator', true),
('EDUARDA DE OLIVEIRA MARTINS', 'edmartins@gruporoveri.com', 'operator', true),
('GIOVANNA BRITO DA SILVA', 'gidabsilva@gruporoveri.com', 'operator', true),
('HELOISA BORGES DE LIMA', 'hebdlima@gruporoveri.com', 'operator', true),
('LUCAS PEREIRA CLAUDINO DOS SANTOS', 'luclsantos@gruporoveri.com', 'operator', true),
('INES PEREIRA DOS SANTOS', 'inpsantos@gruporoveri.com', 'operator', true),
('CINTHIA DE OLIVEIRA SOTOCORNO', 'cisotocorno@gruporoveri.com', 'operator', true),
('THALIA XAVIER DE ALMEIDA', 'thxalmeida@gruporoveri.com', 'operator', true),
('MARIA JOSE SILVA DE MELO', 'majmelo@gruporoveri.com', 'operator', true),
('LAYANE SANTOS VITOR SILVA', 'laynsilva@gruporoveri.com', 'operator', true),
('RUI SOBREIRA LOPES', 'rulopes@gruporoveri.com', 'operator', true),
('CINTIA DANIEL LIMA', 'cilima@gruporoveri.com', 'operator', true),
('GYOVANNA DOS SANTOS SALES', 'gysales@gruporoveri.com', 'operator', true),
('LEONARDO GUSTAVO GOMES LINCEVICIUS', 'lelincevicius@gruporoveri.com', 'operator', true),
('STEFANIE CAROLINE OLIVEIRA CISTERNAS', 'stcisterna@gruporoveri.com', 'operator', true),
('DAVI MEDEIROS DA COSTA', 'dadcosta@gruporoveri.com', 'operator', true),
('ALICE SANTOS DE ALMEIDA VIEIRA', 'alvieira@gruporoveri.com', 'operator', true),
('VANESSA TOSSATO', 'vatossato@gruporoveri.com', 'operator', true),
('MONIQUE MESQUITA DA SILVA PAIXAO', 'mopaixao@gruporoveri.com', 'operator', true),
('VERONICA GONZAGA LEITE', 'veleite@gruporoveri.com', 'operator', true),
('GESSICA FERNANDES DA CRUZ', 'gefcruz@gruporoveri.com', 'operator', true),
('LUANY SALES DE FREITAS', 'lusfreitas@gruporoveri.com', 'operator', true),
('MARIA EDUARDA LIMA GOMES', 'malgomes@gruporoveri.com', 'operator', true),
('YANNE KARYNE FREITAS DO NASCIMENTO', 'yanascimento@gruporoveri.com', 'operator', true),
('SABRINA BARBOSA LEAO', 'saleao@gruporoveri.com', 'operator', true),
('ALINE CAMPOS RAIMUNDO', 'alraimundo@gruporoveri.com', 'operator', true),
('GABRIELA PAOLA DE CARVALHO', 'gapcarvalho@gruporoveri.com', 'operator', true),
('GUILHERME CAETANO BARBOZA DE LIMA', 'guclima@gruporoveri.com', 'operator', true),
('ELIANE JOSEFA DIAS', 'eldias@gruporoveri.com', 'operator', true),
('VICTOR FREITAS XALEGA', 'vixalega@gruporoveri.com', 'operator', true),
('CAUAN BOAVISTA DE FREITAS', 'cabfreitas@gruporoveri.com', 'operator', true),
('ANA MARIA DE OLIVEIRA FONSECA', 'anfonseca@gruporoveri.com', 'operator', true),
('NAIOBI SAPONHOS DE AGUIAR SOARES', 'nasoares@gruporoveri.com', 'operator', true),
('ALEXANDRE MARQUES DA SILVA GUERRA', 'alguerra@gruporoveri.com', 'operator', true),
('MARIA STEFANE MENDS FEITOSA', 'mafeitosa@gruporoveri.com', 'operator', true),
('LUCAS VELOSO SILVA', 'lucveloso@gruporoveri.com', 'operator', true),
('MILLENA DOS SANTOS SILVA', 'missilva@gruporoveri.com', 'operator', true),
('ANNA CLARA STORTI CAMILO', 'ancamilo@gruporoveri.com', 'operator', true),
('EMILLY KAMILLY SIQUEIRA DA SILVA', 'emsiqueira@gruporoveri.com', 'operator', true),
('JENIFER MAIRA LIMA DA SILVA', 'jemsilva@gruporoveri.com', 'operator', true),
('YARA RIBEIRO SOUZA', 'yasouza@gruporoveri.com', 'operator', true),
('FERNANDA DE OLIVEIRA VIANA', 'feviana@gruporoveri.com', 'operator', true),
('STELLA SOUZA FREITAS', 'stfreitas@gruporoveri.com', 'operator', true),
('LARICE BENTO GARCIA', 'lagarcia@gruporoveri.com', 'operator', true),
('ANA JULIA SOARES DE MELO', 'anjmelo@gruporoveri.com', 'operator', true),
('NICOLE PIONA COSTA RODRIGUES', 'nicpiona@gruporoveri.com', 'operator', true),
('JULYA DA SILVA PEREIRA', 'julpereira@gruporoveri.com', 'operator', true),
('JENNIFER LIZ DE ALMEIDA VIEIRA', 'jenvieira@gruporoveri.com', 'operator', true),
('KETHLEEN NATHALIA DOS SANTOS MORINI', 'kemorini@gruporoveri.com', 'operator', true),
('RAYANE SOUSA DA SILVA', 'rayasilva@gruporoveri.com', 'operator', true),
('ROSANE CORREA SANTOS ALVES', 'rosalves@gruporoveri.com', 'operator', true),
('GABRIELLA DO NASCIMENTO SILVA', 'gabnascimento@gruporoveri.com', 'operator', true),
('ANA SARA RODRIGUES SILVA', 'annsilva@gruporoveri.com', 'operator', true),
('MARLEIZE ERDEI PARRINI', 'maparrini@gruporoveri.com', 'operator', true),
('BRUNO RAFAEL DOS SANTOS ABRAO', 'brabrao@gruporoveri.com', 'operator', true),
('SILVANA COSTA BERTOLUCCI', 'sibertolucci@gruporoveri.com', 'operator', true),
('DEBORA MACHADO', 'demachado@gruporoveri.com', 'operator', true),
('LENILZA ANSELMO REIS SANTOS', 'leanselmo@gruporoveri.com', 'operator', true),
('YURI CRISPIM DE LIMA', 'yulima@gruporoveri.com', 'operator', true),
('LUAN SANTOS MOTA', 'lumota@gruporoveri.com', 'operator', true),
('MATEUS BARREIROS MARQUES DE SOUZA', 'mabasouza@gruporoveri.com', 'operator', true),
('KALIL DE ALMEIDA VIEIRA', 'kaalvieira@gruporoveri.com', 'operator', true),
('MARIA EDUARDA LIMA SILVA', 'malisilva@gruporoveri.com', 'operator', true),
('KAUAI RODRIGUES BARBOSA', 'kabarbosa@gruporoveri.com', 'operator', true),
('BEATRIZ SOUZA SILVA', 'besosilva@gruporoveri.com', 'operator', true),
('JOVANA ESTEFANE NOGUEIRA DA SILVA', 'joessilva@gruporoveri.com', 'operator', true),
('JENIFFER LOUREANO BOSSI DE BARROS', 'jebarros@gruporoveri.com', 'operator', true),
('EMILI DOS SANTOS SILVA', 'emsimoura@gruporoveri.com', 'operator', true),
('VANESSA GOMES DE FREITAS', 'vafreitas@gruporoveri.com', 'operator', true),
('DEBORA PEREIRA SANTOS', 'depesantos@gruporoveri.com', 'operator', true),
('RAUL SABINO SOLERA', 'rasolera@gruporoveri.com', 'operator', true),
('GYOVANNA PASCHOAL FULINI RIBEIRO', 'gyribeiro@gruporoveri.com', 'operator', true),
('GERUSIA MARTA FERNADES LINHARES', 'gelinhares@gruporoveri.com', 'operator', true),
('KELLY CRISTINA PINTO SILVEIRA', 'kesilveira@gruporoveri.com', 'operator', true),
('LEANY MARIA CAETANO OLIVEIRA', 'leaoliveira@gruporoveri.com', 'operator', true),
('RAPHAEL CORREIA NEVES', 'racneves@gruporoveri.com', 'operator', true),
('LUCAS FERREIRA DA SILVA', 'lucferreira@gruporoveri.com', 'operator', true),
('LUCAS TAMASHIRO UJLAKI', 'luujlaki@gruporoveri.com', 'operator', true),
('RYAN CAVINATO BAZAN', 'rybazan@gruporoveri.com', 'operator', true),
('MURILO ESTEVAM DE SOUZA', 'mursouza@gruporoveri.com', 'operator', true),
('LUCAS FERNANDES BARROS', 'lubarros@gruporoveri.com', 'operator', true),
('GIOVANNA GONCALVES CABRAL', 'gigcabral@gruporoveri.com', 'operator', true),
('VICTOR HUGO GONCALVES SANTOS', 'vihsantos@gruporoveri.com', 'operator', true),
('KEZIA LEAL', 'keleal@gruporoveri.com', 'operator', true),
('MARIA EDUARDA GUIMARAES LOPES', 'marlopes@gruporoveri.com', 'operator', true),
('VITORIA CAMPOS AGUIAR', 'viaguiar@gruporoveri.com', 'operator', true),
('BENTO DE LIMA ALVES', 'betalves@gruporoveri.com', 'operator', true),
('YASMIN LIMA BARBOSA', 'yalbarbosa@gruporoveri.com', 'operator', true),
('YASMIM GUIMARAES CORDEIRO DOS SANTOS', 'yascordeiro@gruporoveri.com', 'operator', true),
('SARA SILVA SANTOS', 'ssasantos@gruporoveri.com', 'operator', true),
('ANDREIA ALBERTO FURTADO FERREIRA', 'andrferreira@gruporoveri.com', 'operator', true),
('MANOELLA SENA BARBOSA', 'masbarbosa@gruporoveri.com', 'operator', true),
('ESTHER SILVA', 'esthsilva@gruporoveri.com', 'operator', true),
('NIVEA KATIA DA SILVA BOAVENTURA', 'niboaventura@gruporoveri.com', 'operator', true),
('MARIA EDUARDA SOUZA DE LIMA', 'madulima@gruporoveri.com', 'operator', true),
('TATIANA SIQUEIRA DE MOURA', 'tatimoura@gruporoveri.com', 'operator', true),
('VITOR FERREIRA MORAIS', 'vimorais@gruporoveri.com', 'operator', true),
('GIOVANA FERREIRA DA SILVA', 'gifsilva@gruporoveri.com', 'operator', true),
('FABIANA ABDALLA', 'faabdalla@gruporoveri.com', 'operator', true),
('THAIS REZENDE SILVA', 'threzende@gruporoveri.com', 'operator', true),
('LUCAS DA SILVA PEDROSA', 'ludpedrosa@gruporoveri.com', 'operator', true),
('FELIPE AGUIAR MENDES DO NASCIMENTO', 'feaguiar@gruporoveri.com', 'operator', true),
('ANA KATIA DA SILVA', 'ankatia@gruporoveri.com', 'operator', true),
('CATARINA ALVES SILVA', 'catsilva@gruporoveri.com', 'operator', true),
('PEDRO HENRIQUE LAVORATO', 'pelavorato@gruporoveri.com', 'operator', true),
('EDER NASCIMENTO ALVES', 'edalves@gruporoveri.com', 'operator', true),
('MELISSA BALBINO DA SILVA GOMES', 'megomes@gruporoveri.com', 'operator', true),
('LARISSA NASARIO PEREIRA', 'lapereira@gruporoveri.com', 'operator', true),
('RENAN DA SILVA BULGARELLI', 'rebulgarelli@gruporoveri.com', 'operator', true),
('ANA CAROLINE SOUZA OLIVIA', 'anolivia@gruporoveri.com', 'operator', true),
('PEDRO HENRIQUE NASCIMENTO DA SILVA', 'phenrique@gruporoveri.com', 'operator', true),
('LIVIA NOBREGA PIGHIN', 'lipighin@gruporoveri.com', 'operator', true),
('KARINA MUNIZ VIEIRA', 'kamuniz@gruporoveri.com', 'operator', true),
('VITOR HUGO ALVARENGA FACCIOLO', 'vifacciolo@gruporoveri.com', 'operator', true),
('BRENDA MORGAN ESTRELA DA SILVA', 'brestrela@gruporoveri.com', 'operator', true),
('GABRIELLY SANTOS OLIVEIRA', 'gbsoliveira@gruporoveri.com', 'operator', true),
('JADE ALVES DE ARAUJO', 'jaaraujo@gruporoveri.com', 'operator', true),
('ISABELA CRISTINA DE SOUZA', 'iscsouza@gruporoveri.com', 'operator', true),
('AMANDA CUER FERREIRA', 'amferreira@gruporoveri.com', 'operator', true),
('ANA KAROLINA PEREIRA CRUZ', 'ankcruz@gruporoveri.com', 'operator', true),
('LETICIA SIQUEIRA BISPO', 'lebispo@gruporoveri.com', 'operator', true),
('KAUE RAMOS PEREIRA', 'kapereira@gruporoveri.com', 'operator', true),
('DANIELLE LIMA DA COSTA', 'dacosta@gruporoveri.com', 'operator', true),
('NADJA GAMA DOS SANTOS', 'ngama@gruporoveri.com', 'operator', true),
('MAYSA DOS SANTOS NERES', 'maneres@gruporoveri.com', 'operator', true),
('TAMIRES NEVES DOS SANTOS', 'tansantos@gruporoveri.com', 'operator', true),
('MAXINE LUARA RODRIGUES BATISTA DA SILVA', 'maluara@gruporoveri.com', 'operator', true),
('FABIANA APARECIDA BASILIO', 'fabasilio@gruporoveri.com', 'operator', true),
('STEFANIE PAMPOLINI DE ASSIS', 'stassis@gruporoveri.com', 'operator', true),
('LUANA DIAS BRAZ', 'lubraz@gruporoveri.com', 'operator', true),
('FRANCIELE QUERCIA DE OLIVEIRA DOS REIS', 'frreis@gruporoveri.com', 'operator', true),
('YASMIN MACHADO DA SILVA', 'yasmachado@gruporoveri.com', 'operator', true),
('DAVI JOSE NIETTO DE SOUZA', 'danietto@gruporoveri.com', 'operator', true),
('VITOR MENDONCA LOPES', 'vilopes@gruporoveri.com', 'operator', true),
('CAROLINA NUNES DA SILVA', 'carsnunes@gruporoveri.com', 'operator', true),
('PRISCILA FONTES DE AZEVEDO', 'prazevedo@gruporoveri.com', 'operator', true),
('ERIKA MACIEL PEREIRA', 'ermpereira@gruporoveri.com', 'operator', true),
('MARCOS VINICIUS DE LIMA COSTA', 'mavcosta@gruporoveri.com', 'operator', true),
('THAIS SANTOS LOURENCO', 'thlourenco@gruporoveri.com', 'operator', true),
('DEISY KIMBERLLY SATILITE ARAUJO', 'dearaujo@gruporoveri.com', 'operator', true),
('BRENO ALVES NOGUEIRA', 'brenogueira@gruporoveri.com', 'operator', true),
('DANIELLE DA SILVA WENCESLAU', 'dawenceslau@gruporoveri.com', 'operator', true),
('FABIO EISHIMA DE CASTRO GUIRRA', 'faguirra@gruporoveri.com', 'operator', true),
('GEOVANA SILVA MATARUCO DE GODOY', 'gegodoy@gruporoveri.com', 'operator', true),
('HAYANE DE MOURA GOMES', 'hagomes@gruporoveri.com', 'operator', true),
('DANIELA MOURA ANDRADE', 'daneto@gruporoveri.com', 'operator', true),
('CARLOS VINICIUS DIAS DA SILVA', 'cavinicius@gruporoveri.com', 'operator', true),
('GEOVANA DE JESUS SANTOS', 'geovjesus@gruporoveri.com', 'operator', true),
('GIOVANNA FERRAIULI', 'giferraiuli@gruporoveri.com', 'operator', true),
('MARIA EDUARDA SARAIVA BARBOSA', 'marsaraiva@gruporoveri.com', 'operator', true),
('MARINA SOARES DA SILVA', 'marisoares@gruporoveri.com', 'operator', true),
('REBECA CIARELLI GUERRA TERTO', 'reterto@gruporoveri.com', 'operator', true),
('CAMILLY VITORIA SILVA', 'casvitoria@gruporoveri.com', 'operator', true),
('AMANDA LUIZA DIAS SANTOS', 'amsantos@gruporoveri.com', 'operator', true),
('KAYLLANE MYRELLE MOTA SILVA', 'kaylsilva@gruporoveri.com', 'operator', true),
('CRISTIANE PAIZ LYRA', 'crpaiz@gruporoveri.com', 'operator', true),
('GUSTAVO HENRIQUE NASCIMENTO DE SOUZA', 'gutsouza@gruporoveri.com', 'operator', true),
('GABRIEL DA SILVA SANDRAN', 'gasandran@gruporoveri.com', 'operator', true),
('JULIA CAVALCANTI DA COSTA', 'jucavalcante@gruporoveri.com', 'operator', true),
('VERONICA CAVALCANTE LAGE', 'velage@gruporoveri.com', 'operator', true),
('PEDRO FERREIRA DE FREITAS', 'pefreitas@gruporoveri.com', 'operator', true),
('MARIANI SILVA DE LIMA', 'marilima@gruporoveri.com', 'operator', true),
('ELETICIA SOUZA DA SILVA', 'elesilva@gruporoveri.com', 'operator', true),
('BIANCA FARIAS DE OLIVEIRA', 'bifoliveira@gruporoveri.com', 'operator', true),
('NICOLAS WITKOWSKI', 'niwitkowaki@gruporoveri.com', 'operator', true),
('MIRELLA DE ARAUJO AMARAL', 'miamaral@gruporoveri.com', 'operator', true),
('KAUANY SILVA LIMA', 'kanslima@gruporoveri.com', 'operator', true),
('QUEZIA SILVA DOS SANTOS', 'quezsantos@gruporoveri.com', 'operator', true),
('JENIFER MARTINS DA SILVA', 'jenisilva@gruporoveri.com', 'operator', true),
('SIMONE DE CARVALHO SILVA', 'sicarvalho@gruporoveri.com', 'operator', true),
('GISELE NERI RIBEIRO', 'gineribeiro@gruporoveri.com', 'operator', true),
('THAINA LORRANNE NICOLAU BEZERRA', 'thbezerra@gruporoveri.com', 'operator', true),
('TAMARA PEREIRA SANTOS', 'tapsantos@gruporoveri.com', 'operator', true),
('ANDREY MATOS FERREIRA DA SILVA', 'anmasilva@gruporoveri.com', 'operator', true),
('CAROLINA VITORIA DE ARAUJO SANTOS', 'cavisantos@gruporoveri.com', 'operator', true),
('KARIN FIRMO DE LIMA', 'kaflima@gruporoveri.com', 'operator', true),
('CAMILA FIRMO DE LIMA', 'calima@gruporoveri.com', 'operator', true),
('HENRIQUE LINO DA SILVA', 'helisilva@gruporoveri.com', 'operator', true),
('INGRID ANISIO DA SILVA', 'inanisilva@gruporoveri.com', 'operator', true),
('ANA PAULA RODRIGUES', 'anparodrigues@gruporoveri.com', 'operator', true),
('DERICK RIBEIRO DE SALES', 'desales@gruporoveri.com', 'operator', true),
('KATHELLYN IASMIM ROSA SANTANA', 'kasantana@gruporoveri.com', 'operator', true),
('LAURA AMURIM ESTAPINA MOLLER', 'lamoller@gruporoveri.com', 'operator', true),
('FLAVIA BERNARDES STOLFO DOS SANTOS', 'flsantos@gruporoveri.com', 'operator', true),
('VANESSA PINTO', 'vapereira@gruporoveri.com', 'operator', true),
('STEPHANIE GOMES SOARES', 'stgsoares@gruporoveri.com', 'operator', true),
('GRAZIELLI CRISTINA PEREIRA DE OLIVEIRA', 'groliveira@gruporoveri.com', 'operator', true),
('JACKSON CINTRA RAIMUNDO', 'jaraimundo@gruporoveri.com', 'operator', true),
('LUCIANA BARBOSA DA SILVA SANTOS', 'lubarsantos@gruporoveri.com', 'operator', true),
('FATIMA CRISTINA SILVA DE JESUS', 'fajesus@gruporoveri.com', 'operator', true),
('NOEMY BESERRA DA SILVA DE SOUSA', 'nosousa@gruporoveri.com', 'operator', true),
('EDUARDA SILVA DE TOLEDO PINTO', 'edtoledo@gruporoveri.com', 'operator', true),
('JOSE CARLOS DA SILVA', 'jclsilva@gruporoveri.com', 'operator', true),
('MARIA LUIZA FREITAS DOS SANTOS', 'mrlfreitas@gruporoveri.com', 'operator', true),
('DEBORA DA SILVA TELLES', 'detelles@gruporoveri.com', 'operator', true),
('VINICIUS DOS SANTOS PEREIRA POMPEU', 'vipompeu@gruporoveri.com', 'operator', true),
('JOAQUIM RODRIGUES ZARBINATI', 'jozarbinati@gruporoveri.com', 'operator', true),
('VITOR GABRIEL BRANDAO RODRIGUES', 'vgrodrigues@gruporoveri.com', 'operator', true),
('JOICE VITAL CAETANO', 'jocaetano@gruporoveri.com', 'operator', true),
('EVELLYN SILVA PEREIRA', 'evspereira@gruporoveri.com', 'operator', true),
('GIOVANNA LAMBIASI DE ARAUJO', 'glaraujo@gruporoveri.com', 'operator', true),
('LETICIA ANTUNES VIEIRA', 'levieira@gruporoveri.com', 'operator', true),
('SILMEIA SANTANA NEVES', 'sineves@gruporoveri.com', 'operator', true),
('SIRLEI APARECIDA MOTA', 'simota@gruporoveri.com', 'operator', true),
('AMANDA FERNANDES DA SILVA SOUZA', 'amsouza@gruporoveri.com', 'operator', true),
('MARIA DE FATIMA FLORENCIO DE ATHAYDE', 'maathayde@gruporoveri.com', 'operator', true),
('STEPHANIE XAVIER DE OLIVEIRA', 'stexavier@gruporoveri.com', 'operator', true),
('TABATA SAMANTHA AGUIAR BUSTOS', 'tabustos@gruporoveri.com', 'operator', true),
('TALITA REBECA ALBUQUERQUE DE LIMA', 'trebeca@gruporoveri.com', 'operator', true),
('VITOR DA SILVA OLIVEIRA', 'vitsilva@gruporoveri.com', 'operator', true),
('RENATA HORVATH', 'rehorvath@gruporoveri.com', 'operator', true),
('RICHARD MENDES LUCINDO', 'rilucindo@gruporoveri.com', 'operator', true),
('LARISSA OLIVEIRA CARVALHO', 'larcsilva@gruporoveri.com', 'operator', true),
('LETICIA RANY MENDES LUCINDO', 'lelucindo@gruporoveri.com', 'operator', true),
('LUCAS DELLA BIANCA ABREU', 'luabreu@gruporoveri.com', 'operator', true),
('MARIA SUSYANE DO NASCIMENTO', 'msusyane@gruporoveri.com', 'operator', true),
('GUILHERME MODESTO LOPES DA SILVA', 'gmodesto@gruporoveri.com', 'operator', true),
('MARIA EDUARDA DE BRITO SILVA', 'mbrito@gruporoveri.com', 'operator', true),
('BRUNA ONTIVEROS JESUS', 'bontiveros@gruporoveri.com', 'operator', true),
('CARLOS EDUARDO LUNGUINHO DE OLIVEIRA', 'clunguinho@gruporoveri.com', 'operator', true),
('ERIC CATINO RFATO', 'errfato@gruporoveri.com', 'operator', true),
('ARTUR ALVES ADEO', 'aradeo@gruporoveri.com', 'operator', true),
('BEATRIZ CAMILLO SANCIULIS', 'besanciulis@gruporoveri.com', 'operator', true),
('BEATTRIZ PENACCHIO RIBEIRO SILVA', 'bpenacchio@gruporoveri.com', 'operator', true),
('GABRIELLA POSSEBOM LOPES', 'gapossebom@gruporoveri.com', 'operator', true),
('LUIS FERNANDO OSUNA SOLDA', 'lusolda@gruporoveri.com', 'operator', true),
('GABRIELA TEIXEIRA DO NASCIMENTO', 'gabrteixeira@gruporoveri.com', 'operator', true),
('ANA LARISSA EVANGELISTA DA SILVA', 'anevangelista@gruporoveri.com', 'operator', true),
('DENISE DA SILVA', 'denisilva@gruporoveri.com', 'operator', true),
('MARCOS VINICIUS JOVINO DOS SANTOS', 'majovino@gruporoveri.com', 'operator', true),
('RUAN PABLO DA SILVA', 'rupablo@gruporoveri.com', 'operator', true),
('SOPHIA ANDRADE PEREIRA', 'sopereira@gruporoveri.com', 'operator', true),
('ANDRE DA ROCHA BARRETO', 'anbarreto@gruporoveri.com', 'operator', true),
('BEATRIZ DORINE YUSMY DA SILVA', 'beyusmy@gruporoveri.com', 'operator', true),
('CARINA SIMOES', 'casimoes@gruporoveri.com', 'operator', true),
('ISADORA DE OLIVEIRA FERREIRA', 'isaferreira@gruporoveri.com', 'operator', true),
('THAINA GUIMARAES FERREIRA', 'thferreira@gruporoveri.com', 'operator', true),
('KAUAN DURAES DE ABREU', 'kaabreu@gruporoveri.com', 'operator', true),
('GEOVANNA APARECIDA ALMEIDA DA SILVA', 'gealmeida@gruporoveri.com', 'operator', true),
('ALINE TEIXEIRA DE AMORIM', 'alamorim@gruporoveri.com', 'operator', true),
('INGRID LARA CESAR LIMA', 'inlima@gruporoveri.com', 'operator', true),
('RITA DE CASSIA DOS SANTOS', 'risantos@gruporoveri.com', 'operator', true),
('SARA SARTORIO ALVES GARCIA', 'sagarcia@gruporoveri.com', 'operator', true),
('LOHANY DO NASCIMENTO LEOCADIO JUVINO', 'lojuvino@gruporoveri.com', 'operator', true),
('LORENA FACHINCONI DA SILVA', 'lachinconi@gruporoveri.com', 'operator', true),
('GIULIANA CAVLAK NAVARRO', 'ginavaro@gruporoveri.com', 'operator', true),
('KATHLLEN LIMA DE MELO', 'kamelo@gruporoveri.com', 'operator', true),
('BIANCA ARRIATE DA SILA FLAMINIO', 'biflaminio@gruporoveri.com', 'operator', true),
('JHENNYFER PEGO FERNANDES', 'jhfernandes@gruporoveri.com', 'operator', true),
('LUCIANA RAPOZO NEVES', 'luneves@gruporoveri.com', 'operator', true),
('MONIQUE CORREIA', 'mocorreia@gruporoveri.com', 'operator', true),
('PEDRO LUIGI PALMA SANCHES', 'pesanches@gruporoveri.com', 'operator', true),
('RICHARD VITOR SILVA DOS REIS', 'rireis@gruporoveri.com', 'operator', true),
('KEYANE VELOSO PAIVA', 'kepaiva@gruporoveri.com', 'operator', true),
('SILVIA REGINA DE OLIVEIRA', 'sioliveira@gruporoveri.com', 'operator', true),
('YASMIN YOUSSEF ABOU OSMAN', 'yaosman@gruporoveri.com', 'operator', true),
('MARISA FRANCIS GUILHERME TARTARI', 'matartari@gruporoveri.com', 'operator', true),
('MATHEUS DE MARTIN XIMENES', 'maximenes@gruporoveri.com', 'operator', true),
('PEDRO HENRYQUE SILVA', 'pehesilva@gruporoveri.com', 'operator', true),
('PRISCILA NUNES LEITE', 'prleite@gruporoveri.com', 'operator', true),
('PRISCILA PRATES', 'prprates@gruporoveri.com', 'operator', true),
('KETILY CRISTINI DA SILVA LIMA', 'ketlima@gruporoveri.com', 'operator', true),
('LARISSA GONCALVES ORLANDO', 'laorlando@gruporoveri.com', 'operator', true),
('LUCAS DE SOUSA MELO', 'lumelo@gruporoveri.com', 'operator', true),
('LUCAS EIRISDAN OLIVEIRA LIMA', 'lueilima@gruporoveri.com', 'operator', true),
('JOAO PEDRO MARVALHO GALINDO', 'jogalindo@gruporoveri.com', 'operator', true),
('ANDRESSA ROCHA ARAUJO', 'androcha@gruporoveri.com', 'operator', true),
('ARTUR LUCIANO CASAL', 'arcasal@gruporoveri.com', 'operator', true),
('VITOR FRANCIA MATANO', 'vimatano@gruporoveri.com', 'operator', true),
('ANA VITORIA DOS SANTOS OLIVEIR', 'anoliveir@gruporoveri.com', 'operator', true),
('EVELLYN SOARES MARTINEZ', 'evmartinez@gruporoveri.com', 'operator', true),
('PRISCILA PEREIRA', 'prpereira@gruporoveri.com', 'operator', true),
('ANNA CLARA PAWLUK', 'anpawluk@gruporoveri.com', 'operator', true),
('GABRIEL POSTIGO', 'gapostigo@gruporoveri.com', 'operator', true),
('GLEICE QUELLI CONCEICAO DOS SA', 'glsa@gruporoveri.com', 'operator', true),
('EMMANUELLE ALEIXO BRITO', 'embrito@gruporoveri.com', 'operator', true),
('FELIPE ZULEGER RABETTI', 'ferabetti@gruporoveri.com', 'operator', true),
('HELOISA FREITAS DOS SANTOS', 'hefrsantos@gruporoveri.com', 'operator', true),
('LILIAN CRISTINA REZENDE', 'lirezende@gruporoveri.com', 'operator', true),
('RAUL ANTONIO ROQUE E SILVA', 'rarosilva@gruporoveri.com', 'operator', true),
('RYAN MATA DA SILVA', 'rymsilva@gruporoveri.com', 'operator', true),
('SUZANA SANTOS ARAUJO', 'suaraujo@gruporoveri.com', 'operator', true),
('TAINA SANTOS DE OLIVEIRA', 'tasoliveira@gruporoveri.com', 'operator', true),
('TALITA FERNANDA DA SILVA DE JE', 'taje@gruporoveri.com', 'operator', true),
('THAYNA PEREIRA COSTA', 'thpecosta@gruporoveri.com', 'operator', true),
('VANESSA LIMA DA COSTA', 'valicosta@gruporoveri.com', 'operator', true),
('JOSE EMERSON VARJAO', 'jovarjao@gruporoveri.com', 'operator', true),
('BRUNO LORENZO RODRIGUES', 'brlorodrigues@gruporoveri.com', 'operator', true),
('DAVID RANGEL GONCALVES DE SOUS', 'dasous@gruporoveri.com', 'operator', true),
('CAMILA MICAELE GONCALVES', 'camigoncalves@gruporoveri.com', 'operator', true),
('ADRISIA SANTOS DE OLIVEIRA', 'adroliveira@gruporoveri.com', 'operator', true),
('JESSICA DA CONCEICAO MARTINS', 'jemartins@gruporoveri.com', 'operator', true),
('LARISSA MYUKI OLIVEIRA SOUZA', 'lamysouza@gruporoveri.com', 'operator', true),
('LUCAS ARAUJO HOFER', 'luhofer@gruporoveri.com', 'operator', true),
('MARIA CRISTINA GRECCO MOURA PI', 'mapi@gruporoveri.com', 'operator', true),
('MATHEUS APARECIDO ANDREOTTI', 'maandreotti@gruporoveri.com', 'operator', true),
('REBECA NOGUEIRA DA SILVA', 'rbnogueira@gruporoveri.com', 'operator', true),
('RENATA SILVA ROCHA', 'rerocha@gruporoveri.com', 'operator', true),
('RYAN DE SOUSA BERNARDINO', 'rybernardino@gruporoveri.com', 'operator', true),
('VIVIANE SILVA COSTA', 'vivcosta@gruporoveri.com', 'operator', true),
('YASMIN MATTAR DOS SANTOS LOPES', 'yalopes@gruporoveri.com', 'operator', true),
('ISABELA PEREIRA DA SILVA', 'ispsilva@gruporoveri.com', 'operator', true),
('JADSON CONCEICAO SANTOS', 'jadsantos@gruporoveri.com', 'operator', true),
('JOAO VICTOR FONOLOSA DE OLIVEIRA', 'jovoliveira@gruporoveri.com', 'operator', true),
('JULIA SILVESTRE YETIKA', 'juyetika@gruporoveri.com', 'operator', true),
('KAREN CRISTINA SOARES', 'kcrsoares@gruporoveri.com', 'operator', true),
('KEMELLY GONCALVES DA SILVA', 'kmgoncalves@gruporoveri.com', 'operator', true),
('LUANA JANUARIO SANTOS DE ALMEIDA', 'lualmeida@gruporoveri.com', 'operator', true),
('DAVI HIDALGO DA SILVA', 'dahidalgo@gruporoveri.com', 'operator', true),
('GABRIELLA SCAVONE BRITO', 'gsbrito@gruporoveri.com', 'operator', true),
('BRUNA APARECIDA SILVA SANTOS', 'bnsantos@gruporoveri.com', 'operator', true),
('BRUNA MOURA PINTO DE SOUZA', 'bmsouza@gruporoveri.com', 'operator', true),
('GIOVANNA RIBEIRO FOGATO PEREIRA', 'grpereira@gruporoveri.com', 'operator', true),
('JAQUELINE DELLVALD FARIAS', 'jafarias@gruporoveri.com', 'operator', true),
('ARTHUR LISBOA CAIRES', 'arcaires@gruporoveri.com', 'operator', true),
('DANIEL TELES JUNIOR', 'dajunior@gruporoveri.com', 'operator', true),
('LARISSA DA SILVA FRAGA', 'lafraga@gruporoveri.com', 'operator', true),
('NATHALIA REGINA SILVA NOVAES', 'nanovaes@gruporoveri.com', 'operator', true),
('NICOLE CAVALCANTE DE ALBUQUERQUE', 'nialbuquerque@gruporoveri.com', 'operator', true),
('VITORIA SILVA BATISTA', 'vtrbatista@gruporoveri.com', 'operator', true)
ON CONFLICT (email) DO NOTHING;
