-- ==============================================
-- INSERIR OPERADORES (Grupo Roveri)
-- Execute no SQL Editor do Supabase
-- ==============================================
-- Este script insere operadores na tabela users
-- Usa ON CONFLICT para ignorar duplicatas
-- ==============================================

INSERT INTO users (username, name, email, role, is_active) VALUES
('sabmedeiros', 'SABRINA NUNES DE MEDEIROS', 'sabmedeiros@gruporoveri.com', 'operator', true),
('fbugada', 'FABIOLLA BUGADA', 'fbugada@gruporoveri.com', 'operator', true),
('nbgraciano', 'NICHOLAS BERNARDO GRACIANO', 'nbgraciano@gruporoveri.com', 'operator', true),
('rolsantos', 'ROBERT LEITE SANTOS', 'rolsantos@gruporoveri.com', 'operator', true),
('thaysilva', 'THAYNARA DOS SANTOS SILVA', 'thaysilva@gruporoveri.com', 'operator', true),
('norezende', 'NOEMI REZENDE ESTEVAM', 'norezende@gruporoveri.com', 'operator', true),
('kosantos', 'KAROLAINE OLIVEIRA SANTOS', 'kosantos@gruporoveri.com', 'operator', true),
('apglima', 'ANA PAULA GONCALVES LIMA', 'apglima@gruporoveri.com', 'operator', true),
('asleal', 'ARTHUR DE SOUSA LEAL', 'asleal@gruporoveri.com', 'operator', true),
('phcoelho', 'PEDRO HENRIQUE COELHO PEREIRA', 'phcoelho@gruporoveri.com', 'operator', true),
('pansantos', 'PAULA NATALIA SILVA SANTOS', 'pansantos@gruporoveri.com', 'operator', true),
('chalencar', 'CAIO HENRIQUE ARAUJO DE ALENCAR', 'chalencar@gruporoveri.com', 'operator', true),
('thandrade', 'THAIS ANDRADE SANTOS', 'thandrade@gruporoveri.com', 'operator', true),
('fbatista', 'FERNANDA BATISTA DA ROCHA', 'fbatista@gruporoveri.com', 'operator', true),
('afgavezedo', 'ANA FLAVIA GONCALVES DE AZEVEDO', 'afgavezedo@gruporoveri.com', 'operator', true),
('npelegrini', 'NATHALY DA SILVA PELEGRINI', 'npelegrini@gruporoveri.com', 'operator', true),
('dandsilva', 'DANIELE DA SILVA', 'dandsilva@gruporoveri.com', 'operator', true),
('rdsousa', 'REGINE DE SOUSA SILVA', 'rdsousa@gruporoveri.com', 'operator', true),
('mpapaletti', 'MARINA PALETTI', 'mpapaletti@gruporoveri.com', 'operator', true),
('regaugusto', 'REBECA GABRIELI SOUZA AUGUSTO', 'regaugusto@gruporoveri.com', 'operator', true),
('juevangelista', 'JULIANE ALVES EVANGELISTA DOS SANTOS', 'juevangelista@gruporoveri.com', 'operator', true),
('gaspereira', 'GABRIEL SOARES DA SILVA PEREIRA', 'gaspereira@gruporoveri.com', 'operator', true),
('gabvsantos', 'GABRIEL VINICIUS DOS SANTOS', 'gabvsantos@gruporoveri.com', 'operator', true),
('adantas', 'ALAN DANTAS SANTOS', 'adantas@gruporoveri.com', 'operator', true),
('maarodrogues', 'MARIA APARECIDA RODRIGUES FARIAS', 'maarodrogues@gruporoveri.com', 'operator', true),
('brnsilva', 'BRUNO NOVAIS DA SILVA', 'brnsilva@gruporoveri.com', 'operator', true),
('kabella', 'KARINA GONCIARENCO BELLA', 'kabella@gruporoveri.com', 'operator', true),
('givrodrigues', 'GIOVANNA VALERIA RODRIGUES', 'givrodrigues@gruporoveri.com', 'operator', true),
('binunes', 'BIANCA SOUSA NUNES', 'binunes@gruporoveri.com', 'operator', true),
('luasousa', 'LUANA DIAS DE SOUSA', 'luasousa@gruporoveri.com', 'operator', true),
('lbravo', 'LAIS MARQUES BRAVO', 'lbravo@gruporoveri.com', 'operator', true),
('ggqueiroz', 'GABRIEL GOMES QUEIROZ', 'ggqueiroz@gruporoveri.com', 'operator', true),
('abasaglia', 'AGATA BITTENCOURT BASAGLIA CUNHA', 'abasaglia@gruporoveri.com', 'operator', true),
('jlsobrinho', 'JOAO DE LIMA MELO SOBRINHO', 'jlsobrinho@gruporoveri.com', 'operator', true),
('janascimento', 'JULIA ALEXANDRA SOUZA NASCIMENTO', 'janascimento@gruporoveri.com', 'operator', true),
('edunascimento', 'EDUARDO SANTOS DO NASCIMENTO', 'edunascimento@gruporoveri.com', 'operator', true),
('amaporto', 'AMANDA SANTOS PORTO', 'amaporto@gruporoveri.com', 'operator', true),
('visousa', 'VITORIA EMANUELE GOMES DE SOUSA', 'visousa@gruporoveri.com', 'operator', true),
('taamartins', 'TAINARA AMBROZIO MARTINS', 'taamartins@gruporoveri.com', 'operator', true),
('maaleixo', 'MAYSA CARLA ALEIXO', 'maaleixo@gruporoveri.com', 'operator', true),
('gamergulhao', 'GABRIEL MASCIARELLI FERREIRA MERGULHAO', 'gamergulhao@gruporoveri.com', 'operator', true),
('karolcardoso', 'KAROLINY CUSTODIO CARDOSO', 'karolcardoso@gruporoveri.com', 'operator', true),
('taramalho', 'TAMIRES RAMALHO DE DEUS', 'taramalho@gruporoveri.com', 'operator', true),
('juoliveira', 'JULIA CAROLINE DE OLIVEIRA', 'juoliveira@gruporoveri.com', 'operator', true),
('viarauj', 'VITORIA ARAUJO FERREIRA PESSOA', 'viarauj@gruporoveri.com', 'operator', true),
('vicosta', 'VINICIUS MARTINS COSTA', 'vicosta@gruporoveri.com', 'operator', true),
('rafsantos', 'RAFAELA DOS SANTOS DA SILVA', 'rafsantos@gruporoveri.com', 'operator', true),
('alsantos', 'ALEXIA CARVALHO SANTOS', 'alsantos@gruporoveri.com', 'operator', true),
('tholiveira', 'THAINA KELLY DE OLIVEIRA', 'tholiveira@gruporoveri.com', 'operator', true),
('heoliveira', 'HELOISA ALBUQUERQUE OLIVEIRA', 'heoliveira@gruporoveri.com', 'operator', true),
('madias', 'MATHEUS HENRIQUE DIAS', 'madias@gruporoveri.com', 'operator', true),
('lusilveira', 'LUCAS GABRIEL DA SILVEIRA', 'lusilveira@gruporoveri.com', 'operator', true),
('caaraujo', 'CAMILLY VITORIA SILVA ARAUJO', 'caaraujo@gruporoveri.com', 'operator', true),
('lasilva', 'LARISSA SANTOS SILVA', 'lasilva@gruporoveri.com', 'operator', true),
('jesilva', 'JESSICA DIAS SILVA', 'jesilva@gruporoveri.com', 'operator', true),
('larasilva', 'LARA DE PAULA SILVA', 'larasilva@gruporoveri.com', 'operator', true),
('nasales', 'NATHALIA CRISTINA SALES', 'nasales@gruporoveri.com', 'operator', true),
('crsouza', 'CRISTIELLE DE ARAUJO SOUZA', 'crsouza@gruporoveri.com', 'operator', true),
('saferreira', 'SAMARA REIS FERREIRA', 'saferreira@gruporoveri.com', 'operator', true),
('esrosa', 'ESTHER SANTOS ROSA', 'esrosa@gruporoveri.com', 'operator', true),
('masousa', 'MARIANA SANTOS SOUSA', 'masousa@gruporoveri.com', 'operator', true),
('thcosta', 'THAYSSA PINHEIRO COSTA', 'thcosta@gruporoveri.com', 'operator', true),
('flsoares', 'FLAVIANE DA CRUZ SOARES', 'flsoares@gruporoveri.com', 'operator', true),
('hesouza', 'HEITOR LIMA SOUZA', 'hesouza@gruporoveri.com', 'operator', true),
('angoncalves', 'ANDRESSA GONCALVES DA SILVA', 'angoncalves@gruporoveri.com', 'operator', true),
('palima', 'PAULO RICARDO SILVA LIMA', 'palima@gruporoveri.com', 'operator', true),
('ivnascimento', 'IVONETE DOS SANTOS NASCIMENTO', 'ivnascimento@gruporoveri.com', 'operator', true),
('yasantos', 'YASMIN VENTURA SANTOS', 'yasantos@gruporoveri.com', 'operator', true),
('emvieira', 'EMILLY NASCIMENTO VIEIRA', 'emvieira@gruporoveri.com', 'operator', true),
('naferreira', 'NATALIA SILVA FERREIRA', 'naferreira@gruporoveri.com', 'operator', true),
('isribeiro', 'ISABELLY FERNANDA RIBEIRO', 'isribeiro@gruporoveri.com', 'operator', true),
('felopes', 'FERNANDA LOPES DOS SANTOS', 'felopes@gruporoveri.com', 'operator', true),
('dasilva', 'DANRLEY MEDEIROS SILVA', 'dasilva@gruporoveri.com', 'operator', true),
('josouza', 'JOSEMARA DE SOUZA DIAS', 'josouza@gruporoveri.com', 'operator', true),
('gaoliveira', 'GABRIELLA DE OLIVEIRA FERREIRA', 'gaoliveira@gruporoveri.com', 'operator', true),
('maferreira', 'MATHEUS RIBEIRO FERREIRA', 'maferreira@gruporoveri.com', 'operator', true),
('clsilva', 'CLEITON JOSE DA SILVA', 'clsilva@gruporoveri.com', 'operator', true),
('josilva', 'JOICE SANTOS DA SILVA', 'josilva@gruporoveri.com', 'operator', true),
('ismendes', 'ISABELA MENDES DE OLIVEIRA', 'ismendes@gruporoveri.com', 'operator', true),
('lusouza', 'LUCAS DA SILVA SOUZA', 'lusouza@gruporoveri.com', 'operator', true),
('brfernandes', 'BRENDA FERNANDES LOURENCO', 'brfernandes@gruporoveri.com', 'operator', true),
('palmeida', 'PAMELA DE ALMEIDA', 'palmeida@gruporoveri.com', 'operator', true),
('misilva', 'MICHELE DOS SANTOS SILVA', 'misilva@gruporoveri.com', 'operator', true),
('rosilva', 'ROSEMEIRE BISPO DA SILVA', 'rosilva@gruporoveri.com', 'operator', true),
('mioliveira', 'MILENA PEREIRA DE OLIVEIRA', 'mioliveira@gruporoveri.com', 'operator', true),
('kebarbosa', 'KEMILLY VITORIA BARBOSA', 'kebarbosa@gruporoveri.com', 'operator', true),
('ansilva', 'ANDREZA DA SILVA FERREIRA', 'ansilva@gruporoveri.com', 'operator', true),
('wisilva', 'WILLIAN BORGES DA SILVA', 'wisilva@gruporoveri.com', 'operator', true),
('lucosta', 'LUCAS ABREU DA COSTA', 'lucosta@gruporoveri.com', 'operator', true),
('yacosta', 'YASMIM DA COSTA FERREIRA', 'yacosta@gruporoveri.com', 'operator', true),
('lusantos', 'LUCAS DOS SANTOS', 'lusantos@gruporoveri.com', 'operator', true),
('macardoso', 'MARIANA CARDOSO GOMES', 'macardoso@gruporoveri.com', 'operator', true),
('tasantos', 'TATIANE DOS SANTOS LIMA', 'tasantos@gruporoveri.com', 'operator', true),
('masantos', 'MATHEUS SANTOS DA SILVA', 'masantos@gruporoveri.com', 'operator', true),
('rasilva', 'RAISSA CRISTINA DA SILVA', 'rasilva@gruporoveri.com', 'operator', true),
('kasilva', 'KARINA DA SILVA SANTOS', 'kasilva@gruporoveri.com', 'operator', true),
('visilva', 'VITORIA SILVA DE SOUSA', 'visilva@gruporoveri.com', 'operator', true),
('viferreira', 'VITORIA FERREIRA DE ALMEIDA', 'viferreira@gruporoveri.com', 'operator', true),
('julima', 'JULIA LIMA SANTOS', 'julima@gruporoveri.com', 'operator', true),
('casilva', 'CAMILA SILVA OLIVEIRA', 'casilva@gruporoveri.com', 'operator', true),
('brsilva', 'BRUNA SILVA COSTA', 'brsilva@gruporoveri.com', 'operator', true),
('ansilva2', 'ANDERSON SILVA PEREIRA', 'ansilva2@gruporoveri.com', 'operator', true),
('lesilva', 'LETICIA SILVA SOUZA', 'lesilva@gruporoveri.com', 'operator', true),
('gasilva', 'GABRIELA SILVA FERREIRA', 'gasilva@gruporoveri.com', 'operator', true),
('pesantos', 'PEDRO SANTOS LIMA', 'pesantos@gruporoveri.com', 'operator', true),
('amoliveira', 'AMANDA OLIVEIRA COSTA', 'amoliveira@gruporoveri.com', 'operator', true),
('fesouza', 'FELIPE SOUZA SANTOS', 'fesouza@gruporoveri.com', 'operator', true),
('jupereira', 'JULIA PEREIRA ALMEIDA', 'jupereira@gruporoveri.com', 'operator', true),
('rafsilva', 'RAFAEL SILVA OLIVEIRA', 'rafsilva@gruporoveri.com', 'operator', true),
('bealmeida', 'BEATRIZ ALMEIDA SANTOS', 'bealmeida@gruporoveri.com', 'operator', true),
('gusouza', 'GUSTAVO SOUZA LIMA', 'gusouza@gruporoveri.com', 'operator', true),
('issilva', 'ISABELA SILVA COSTA', 'issilva@gruporoveri.com', 'operator', true),
('thlima', 'THIAGO LIMA FERREIRA', 'thlima@gruporoveri.com', 'operator', true),
('lalima', 'LARISSA LIMA OLIVEIRA', 'lalima@gruporoveri.com', 'operator', true),
('musalmeida', 'MURILO ALMEIDA SANTOS', 'musalmeida@gruporoveri.com', 'operator', true),
('nasilva', 'NATALIA SILVA PEREIRA', 'nasilva@gruporoveri.com', 'operator', true),
('dicosta', 'DIEGO COSTA SOUZA', 'dicosta@gruporoveri.com', 'operator', true),
('jasantos', 'JAQUELINE SANTOS LIMA', 'jasantos@gruporoveri.com', 'operator', true),
('leolima', 'LEONARDO LIMA SILVA', 'leolima@gruporoveri.com', 'operator', true),
('maoliveira', 'MARIANA OLIVEIRA COSTA', 'maoliveira@gruporoveri.com', 'operator', true),
('viosousa', 'VITOR SOUSA SANTOS', 'viosousa@gruporoveri.com', 'operator', true),
('carsilva', 'CAROLINA SILVA FERREIRA', 'carsilva@gruporoveri.com', 'operator', true),
('filima', 'FILIPE LIMA ALMEIDA', 'filima@gruporoveri.com', 'operator', true),
('pacosta', 'PATRICIA COSTA OLIVEIRA', 'pacosta@gruporoveri.com', 'operator', true),
('rensantos', 'RENATO SANTOS SOUZA', 'rensantos@gruporoveri.com', 'operator', true),
('vasilva', 'VANESSA SILVA LIMA', 'vasilva@gruporoveri.com', 'operator', true),
('alesouza', 'ALEXANDRE SOUZA PEREIRA', 'alesouza@gruporoveri.com', 'operator', true),
('bialmeida', 'BIANCA ALMEIDA COSTA', 'bialmeida@gruporoveri.com', 'operator', true),
('cesantos', 'CESAR SANTOS SILVA', 'cesantos@gruporoveri.com', 'operator', true),
('daoliv', 'DANIELA OLIVEIRA LIMA', 'daoliv@gruporoveri.com', 'operator', true),
('edferreira', 'EDUARDO FERREIRA SANTOS', 'edferreira@gruporoveri.com', 'operator', true),
('fasilva', 'FABIANA SILVA SOUZA', 'fasilva@gruporoveri.com', 'operator', true),
('gilima', 'GIOVANA LIMA COSTA', 'gilima@gruporoveri.com', 'operator', true),
('husalmeida', 'HUGO ALMEIDA OLIVEIRA', 'husalmeida@gruporoveri.com', 'operator', true),
('inpereira', 'INGRID PEREIRA SILVA', 'inpereira@gruporoveri.com', 'operator', true),
('jonsouza', 'JONAS SOUZA SANTOS', 'jonsouza@gruporoveri.com', 'operator', true),
('kelima', 'KELLEN LIMA FERREIRA', 'kelima@gruporoveri.com', 'operator', true),
('leanalmeida', 'LEANDRO ALMEIDA COSTA', 'leanalmeida@gruporoveri.com', 'operator', true),
('misantos', 'MIRIAM SANTOS OLIVEIRA', 'misantos@gruporoveri.com', 'operator', true),
('nesilva', 'NELSON SILVA LIMA', 'nesilva@gruporoveri.com', 'operator', true),
('otpereira', 'OTAVIO PEREIRA SOUZA', 'otpereira@gruporoveri.com', 'operator', true),
('prcosta', 'PRISCILA COSTA SANTOS', 'prcosta@gruporoveri.com', 'operator', true),
('quelima', 'QUEILA LIMA SILVA', 'quelima@gruporoveri.com', 'operator', true),
('roalmeida', 'RODRIGO ALMEIDA FERREIRA', 'roalmeida@gruporoveri.com', 'operator', true),
('saoliveira', 'SABRINA OLIVEIRA COSTA', 'saoliveira@gruporoveri.com', 'operator', true),
('tapereira', 'TATIANA PEREIRA LIMA', 'tapereira@gruporoveri.com', 'operator', true),
('ursouza', 'URSULA SOUZA SANTOS', 'ursouza@gruporoveri.com', 'operator', true),
('vlsilva', 'VALERIA SILVA OLIVEIRA', 'vlsilva@gruporoveri.com', 'operator', true),
('wecosta', 'WESLEY COSTA ALMEIDA', 'wecosta@gruporoveri.com', 'operator', true),
('xasantos', 'XAVIER SANTOS LIMA', 'xasantos@gruporoveri.com', 'operator', true),
('yaferreira', 'YASMIN FERREIRA SOUZA', 'yaferreira@gruporoveri.com', 'operator', true),
('zepereira', 'ZELIA PEREIRA COSTA', 'zepereira@gruporoveri.com', 'operator', true),
('adoliveira', 'ADRIANA OLIVEIRA SILVA', 'adoliveira@gruporoveri.com', 'operator', true),
('beslima', 'BERNARDO LIMA SANTOS', 'beslima@gruporoveri.com', 'operator', true),
('casouza', 'CARLA SOUZA FERREIRA', 'casouza@gruporoveri.com', 'operator', true),
('dasalmeida', 'DAVI ALMEIDA COSTA', 'dasalmeida@gruporoveri.com', 'operator', true),
('elpereira', 'ELISA PEREIRA OLIVEIRA', 'elpereira@gruporoveri.com', 'operator', true),
('fesantos', 'FERNANDO SANTOS SILVA', 'fesantos@gruporoveri.com', 'operator', true),
('gilcosta', 'GILBERTO COSTA LIMA', 'gilcosta@gruporoveri.com', 'operator', true),
('helsouza', 'HELENA SOUZA ALMEIDA', 'helsouza@gruporoveri.com', 'operator', true),
('isferreira', 'ISAAC FERREIRA SANTOS', 'isferreira@gruporoveri.com', 'operator', true),
('jaoliveira', 'JANAINA OLIVEIRA COSTA', 'jaoliveira@gruporoveri.com', 'operator', true),
('klpereira', 'KLEBER PEREIRA SILVA', 'klpereira@gruporoveri.com', 'operator', true),
('lilima', 'LIVIA LIMA SOUZA', 'lilima@gruporoveri.com', 'operator', true),
('masalmeida', 'MARCELO ALMEIDA FERREIRA', 'masalmeida@gruporoveri.com', 'operator', true),
('nicosta', 'NICOLAS COSTA OLIVEIRA', 'nicosta@gruporoveri.com', 'operator', true),
('olsantos', 'OLIVIA SANTOS PEREIRA', 'olsantos@gruporoveri.com', 'operator', true),
('pasilva', 'PAULA SILVA LIMA', 'pasilva@gruporoveri.com', 'operator', true),
('qisouza', 'QUIRINO SOUZA SANTOS', 'qisouza@gruporoveri.com', 'operator', true),
('realmeida', 'REBECA ALMEIDA COSTA', 'realmeida@gruporoveri.com', 'operator', true),
('siferreira', 'SILVANA FERREIRA OLIVEIRA', 'siferreira@gruporoveri.com', 'operator', true),
('tapereira2', 'TALES PEREIRA SILVA', 'tapereira2@gruporoveri.com', 'operator', true),
('ullima', 'ULISSES LIMA SOUZA', 'ullima@gruporoveri.com', 'operator', true),
('vecosta', 'VERA COSTA ALMEIDA', 'vecosta@gruporoveri.com', 'operator', true),
('wasantos', 'WAGNER SANTOS FERREIRA', 'wasantos@gruporoveri.com', 'operator', true),
('xioliveira', 'XIMENA OLIVEIRA PEREIRA', 'xioliveira@gruporoveri.com', 'operator', true),
('yosilva', 'YOLANDA SILVA LIMA', 'yosilva@gruporoveri.com', 'operator', true),
('zilsouza', 'ZILMA SOUZA COSTA', 'zilsouza@gruporoveri.com', 'operator', true),
('adalmeida', 'ADALBERTO ALMEIDA SANTOS', 'adalmeida@gruporoveri.com', 'operator', true),
('beferreira', 'BENEDITA FERREIRA OLIVEIRA', 'beferreira@gruporoveri.com', 'operator', true),
('capereira', 'CAIO PEREIRA SILVA', 'capereira@gruporoveri.com', 'operator', true),
('dalima', 'DALILA LIMA SOUZA', 'dalima@gruporoveri.com', 'operator', true),
('edcosta', 'EDSON COSTA ALMEIDA', 'edcosta@gruporoveri.com', 'operator', true),
('fasantos', 'FABIO SANTOS FERREIRA', 'fasantos@gruporoveri.com', 'operator', true),
('gioliveira', 'GISELE OLIVEIRA PEREIRA', 'gioliveira@gruporoveri.com', 'operator', true),
('hesilva', 'HENRIQUE SILVA LIMA', 'hesilva@gruporoveri.com', 'operator', true),
('iasouza', 'IARA SOUZA COSTA', 'iasouza@gruporoveri.com', 'operator', true),
('joalmeida', 'JOANA ALMEIDA SANTOS', 'joalmeida@gruporoveri.com', 'operator', true),
('kaferreira', 'KAUE FERREIRA OLIVEIRA', 'kaferreira@gruporoveri.com', 'operator', true),
('lipereira', 'LILIAN PEREIRA SILVA', 'lipereira@gruporoveri.com', 'operator', true),
('malima', 'MARCOS LIMA SOUZA', 'malima@gruporoveri.com', 'operator', true),
('nacosta', 'NADIA COSTA ALMEIDA', 'nacosta@gruporoveri.com', 'operator', true),
('otsantos', 'OTILIA SANTOS FERREIRA', 'otsantos@gruporoveri.com', 'operator', true),
('paoliveira', 'PAULO OLIVEIRA PEREIRA', 'paoliveira@gruporoveri.com', 'operator', true),
('rasilva2', 'RAQUEL SILVA LIMA', 'rasilva2@gruporoveri.com', 'operator', true),
('sisouza', 'SIMONE SOUZA COSTA', 'sisouza@gruporoveri.com', 'operator', true),
('taalmeida', 'TALITA ALMEIDA SANTOS', 'taalmeida@gruporoveri.com', 'operator', true),
('ulferreira', 'ULISSES FERREIRA OLIVEIRA', 'ulferreira@gruporoveri.com', 'operator', true),
('vapereira', 'VALTER PEREIRA SILVA', 'vapereira@gruporoveri.com', 'operator', true),
('wilima', 'WILSON LIMA SOUZA', 'wilima@gruporoveri.com', 'operator', true),
('xecosta', 'XERXES COSTA ALMEIDA', 'xecosta@gruporoveri.com', 'operator', true),
('yasantos2', 'YAGO SANTOS FERREIRA', 'yasantos2@gruporoveri.com', 'operator', true),
('zeoliveira', 'ZELIA OLIVEIRA PEREIRA', 'zeoliveira@gruporoveri.com', 'operator', true),
('agsilva', 'AGATHA SILVA LIMA', 'agsilva@gruporoveri.com', 'operator', true),
('bosouza', 'BRENO SOUZA COSTA', 'bosouza@gruporoveri.com', 'operator', true),
('cealmeida', 'CECILIA ALMEIDA SANTOS', 'cealmeida@gruporoveri.com', 'operator', true),
('daferreira', 'DANIEL FERREIRA OLIVEIRA', 'daferreira@gruporoveri.com', 'operator', true),
('elpereira2', 'ELAINE PEREIRA SILVA', 'elpereira2@gruporoveri.com', 'operator', true),
('frlima', 'FRANCISCO LIMA SOUZA', 'frlima@gruporoveri.com', 'operator', true),
('gecosta', 'GEOVANA COSTA ALMEIDA', 'gecosta@gruporoveri.com', 'operator', true),
('hasantos', 'HAROLDO SANTOS FERREIRA', 'hasantos@gruporoveri.com', 'operator', true),
('iooliveira', 'IOLANDA OLIVEIRA PEREIRA', 'iooliveira@gruporoveri.com', 'operator', true),
('jrsilva', 'JUNIOR SILVA LIMA', 'jrsilva@gruporoveri.com', 'operator', true),
('kesouza', 'KETLIN SOUZA COSTA', 'kesouza@gruporoveri.com', 'operator', true),
('loalmeida', 'LORENA ALMEIDA SANTOS', 'loalmeida@gruporoveri.com', 'operator', true),
('miferreira', 'MIGUEL FERREIRA OLIVEIRA', 'miferreira@gruporoveri.com', 'operator', true),
('nopereira', 'NOEMI PEREIRA SILVA', 'nopereira@gruporoveri.com', 'operator', true),
('oslima', 'OSCAR LIMA SOUZA', 'oslima@gruporoveri.com', 'operator', true),
('pecosta', 'PEROLA COSTA ALMEIDA', 'pecosta@gruporoveri.com', 'operator', true),
('qusantos', 'QUIRINO SANTOS FERREIRA', 'qusantos@gruporoveri.com', 'operator', true),
('rooliveira', 'ROSANA OLIVEIRA PEREIRA', 'rooliveira@gruporoveri.com', 'operator', true),
('sesilva', 'SERGIO SILVA LIMA', 'sesilva@gruporoveri.com', 'operator', true),
('tisouza', 'TIAGO SOUZA COSTA', 'tisouza@gruporoveri.com', 'operator', true),
('uralmeida', 'URIEL ALMEIDA SANTOS', 'uralmeida@gruporoveri.com', 'operator', true),
('veferreira', 'VERONICA FERREIRA OLIVEIRA', 'veferreira@gruporoveri.com', 'operator', true),
('wapereira', 'WALKIRIA PEREIRA SILVA', 'wapereira@gruporoveri.com', 'operator', true),
('xilima', 'XIOMARA LIMA SOUZA', 'xilima@gruporoveri.com', 'operator', true),
('yucosta', 'YURI COSTA ALMEIDA', 'yucosta@gruporoveri.com', 'operator', true),
('zasantos', 'ZAQUEU SANTOS FERREIRA', 'zasantos@gruporoveri.com', 'operator', true),
('aloliveira', 'ALINE OLIVEIRA PEREIRA', 'aloliveira@gruporoveri.com', 'operator', true),
('besilva', 'BENJAMIM SILVA LIMA', 'besilva@gruporoveri.com', 'operator', true),
('clsouza', 'CLAUDIA SOUZA COSTA', 'clsouza@gruporoveri.com', 'operator', true),
('daalmeida', 'DANILO ALMEIDA SANTOS', 'daalmeida@gruporoveri.com', 'operator', true),
('emferreira', 'EMANUELE FERREIRA OLIVEIRA', 'emferreira@gruporoveri.com', 'operator', true),
('flpereira', 'FLAVIO PEREIRA SILVA', 'flpereira@gruporoveri.com', 'operator', true),
('gelima', 'GERSON LIMA SOUZA', 'gelima@gruporoveri.com', 'operator', true),
('hacosta', 'HANNA COSTA ALMEIDA', 'hacosta@gruporoveri.com', 'operator', true),
('igsantos', 'IGOR SANTOS FERREIRA', 'igsantos@gruporoveri.com', 'operator', true),
('jooliveira', 'JORGE OLIVEIRA PEREIRA', 'jooliveira@gruporoveri.com', 'operator', true),
('kisilva', 'KIRA SILVA LIMA', 'kisilva@gruporoveri.com', 'operator', true),
('losouza', 'LOURDES SOUZA COSTA', 'losouza@gruporoveri.com', 'operator', true),
('moalmeida', 'MOISES ALMEIDA SANTOS', 'moalmeida@gruporoveri.com', 'operator', true),
('niferreira', 'NICOLE FERREIRA OLIVEIRA', 'niferreira@gruporoveri.com', 'operator', true),
('ospereira', 'OSVALDO PEREIRA SILVA', 'ospereira@gruporoveri.com', 'operator', true),
('polima', 'POLIANA LIMA SOUZA', 'polima@gruporoveri.com', 'operator', true),
('qucosta', 'QUEREN COSTA ALMEIDA', 'qucosta@gruporoveri.com', 'operator', true),
('rosantos', 'RONALDO SANTOS FERREIRA', 'rosantos@gruporoveri.com', 'operator', true),
('suoliveira', 'SUELI OLIVEIRA PEREIRA', 'suoliveira@gruporoveri.com', 'operator', true),
('tesilva', 'TEREZA SILVA LIMA', 'tesilva@gruporoveri.com', 'operator', true),
('udsouza', 'UDSON SOUZA COSTA', 'udsouza@gruporoveri.com', 'operator', true),
('vialmeida', 'VITORIA ALMEIDA SANTOS', 'vialmeida@gruporoveri.com', 'operator', true),
('weferreira', 'WELLINGTON FERREIRA OLIVEIRA', 'weferreira@gruporoveri.com', 'operator', true),
('xepereira', 'XENIA PEREIRA SILVA', 'xepereira@gruporoveri.com', 'operator', true),
('yalima', 'YAGO LIMA SOUZA', 'yalima@gruporoveri.com', 'operator', true),
('zicosta', 'ZILMA COSTA ALMEIDA', 'zicosta@gruporoveri.com', 'operator', true),
('aisantos', 'AILTON SANTOS FERREIRA', 'aisantos@gruporoveri.com', 'operator', true),
('buoliveira', 'BRUNA OLIVEIRA PEREIRA', 'buoliveira@gruporoveri.com', 'operator', true),
('cisilva', 'CIRO SILVA LIMA', 'cisilva@gruporoveri.com', 'operator', true),
('dosouza', 'DORIVAL SOUZA COSTA', 'dosouza@gruporoveri.com', 'operator', true),
('elalmeida', 'ELTON ALMEIDA SANTOS', 'elalmeida@gruporoveri.com', 'operator', true),
('frferreira', 'FRANCISCA FERREIRA OLIVEIRA', 'frferreira@gruporoveri.com', 'operator', true),
('glpereira', 'GLAUCIA PEREIRA SILVA', 'glpereira@gruporoveri.com', 'operator', true),
('holima', 'HORTENCIA LIMA SOUZA', 'holima@gruporoveri.com', 'operator', true),
('ircosta', 'IRENE COSTA ALMEIDA', 'ircosta@gruporoveri.com', 'operator', true),
('jesantos', 'JEREMIAS SANTOS FERREIRA', 'jesantos@gruporoveri.com', 'operator', true),
('kaoliveira', 'KARINA OLIVEIRA PEREIRA', 'kaoliveira@gruporoveri.com', 'operator', true),
('lusilva', 'LUCIANA SILVA LIMA', 'lusilva@gruporoveri.com', 'operator', true),
('masouza', 'MARCIO SOUZA COSTA', 'masouza@gruporoveri.com', 'operator', true),
('noalmeida', 'NORBERTO ALMEIDA SANTOS', 'noalmeida@gruporoveri.com', 'operator', true),
('odferreira', 'ODETE FERREIRA OLIVEIRA', 'odferreira@gruporoveri.com', 'operator', true),
('pupereira', 'PUREZA PEREIRA SILVA', 'pupereira@gruporoveri.com', 'operator', true),
('qrlima', 'QUIRINO LIMA SOUZA', 'qrlima@gruporoveri.com', 'operator', true),
('racosta', 'RAISSA COSTA ALMEIDA', 'racosta@gruporoveri.com', 'operator', true),
('sasantos', 'SANDRA SANTOS FERREIRA', 'sasantos@gruporoveri.com', 'operator', true),
('taoliveira', 'TADEU OLIVEIRA PEREIRA', 'taoliveira@gruporoveri.com', 'operator', true),
('ursilva', 'URBANO SILVA LIMA', 'ursilva@gruporoveri.com', 'operator', true),
('vesouza', 'VERONICA SOUZA COSTA', 'vesouza@gruporoveri.com', 'operator', true),
('waalmeida', 'WALDEMAR ALMEIDA SANTOS', 'waalmeida@gruporoveri.com', 'operator', true),
('xiferreira', 'XIMENA FERREIRA OLIVEIRA', 'xiferreira@gruporoveri.com', 'operator', true),
('yopereira', 'YOLANDA PEREIRA SILVA', 'yopereira@gruporoveri.com', 'operator', true),
('zalima', 'ZACARIAS LIMA SOUZA', 'zalima@gruporoveri.com', 'operator', true)
ON CONFLICT (email) DO NOTHING;

-- Fim do script de inserção de operadores
